### ISSUE TITLE
掌上公交有的开屏广告和运行中的广告不能自动跳过

### ISSUE THREAD

**Issue by kunanhai5888** [AIsouler/GKD_subscription#102]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

https://i.gkd.li/import/14546373
https://i.gkd.li/import/14546388

**Comment by AIsouler** [comment]
86fce9e11ca2479b473aad37cb03988914579e90

**Comment by kunanhai5888** [comment]
You're really amazing,thank you very much!
