### ISSUE TITLE
微信-分段广告-订阅号消息页面广告会误触其他内容

### ISSUE THREAD

**Issue by tiki-007** [AIsouler/GKD_subscription#103]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

环境：华为mate30 pro手机，鸿蒙4系统
微信版本：8.0.47
规则：微信-分段广告-订阅号消息页面广告
描述：该规则本身不对实际的订阅号消息页面广告触发，但会误触常看的号
快照：https://i.gkd.li/import/14548771
![Uploading Screenshot_20240310_120235_li.songe.gkd.jpg…]()

**Comment by tiki-007** [comment]
![Screenshot_20240310_120235_li songe gkd](https://github.com/AIsouler/GKD_subscription/assets/78672990/36641b6b-8a6e-41d0-bdae-c520e4543fb1)

**Comment by AIsouler** [comment]
9bb5138fedf2f728fe8b016fc75240d5eb988924

**Comment by tiki-007** [comment]
您好，代码修改后，上述问题误触解决了，但没解决全部问题且出现新问题，目前情况如下：

环境：华为mate30 pro手机，鸿蒙4系统
微信版本：8.0.47
规则：微信-分段广告-订阅号消息页面广告
描述：1.该规则本身不对实际的订阅号消息页面广告触发，但会误触广告链接，导致跳转；
2.屏幕中尚未出现广告时，一直触发跳过广告的提示信息
https://i.gkd.li/import/14549532
https://i.gkd.li/import/14549534
https://i.gkd.li/import/14549535
![Screenshot_20240310_165357_li songe gkd](https://github.com/AIsouler/GKD_subscription/assets/78672990/4d611053-e265-432b-b074-19739850540f)

**Comment by AIsouler** [comment]
能否再补充一下广告的快照，你的快照信息不全

**Comment by AIsouler** [comment]
还没发布更新

**Comment by tiki-007** [comment]
好的，这个可以吗？
https://i.gkd.li/import/14549583

**Comment by AIsouler** [comment]
> 好的，这个可以吗？ https://i.gkd.li/import/14549583

今晚更新后就没问题了

**Comment by tiki-007** [comment]
> > 好的，这个可以吗？ https://i.gkd.li/import/14549583
> 
> 今晚更新后就没问题了

好的，辛苦了

**Comment by tiki-007** [comment]
> > 好的，这个可以吗？ https://i.gkd.li/import/14549583
> 
> 今晚更新后就没问题了

抱歉，更新后还存在我后续补充的情况，不误触常用的号了，也不会在订阅号页面未出现广告时一直提示跳过信息，但仍存在我后续补充的情况1：会在广告处误触广告链接导致跳转

**Comment by AIsouler** [comment]
你好，我这边计算出来的坐标是在```广告```按钮的范围内的，我不知道哪里出了问题

**Comment by tiki-007** [comment]
> 你好，我这边计算出来的坐标是在`广告`按钮的范围内的，我不知道哪里出了问题

此时微信订阅号暂时没有广告内容，等后续有广告的时候我再补充下快照、日志等信息

**Comment by AIsouler** [comment]
请问更新到最新版本GKD能正常跳过了吗，我这边测试是能跳过的

**Comment by tiki-007** [comment]
> 请问更新到最新版本GKD能正常跳过了吗，我这边测试是能跳过的

抱歉，最近忙忘了，但刚看了下，还是有问题，会误触常看的视频；
由于未遇见广告推送，所以订阅号消息中的广告推送是否可以正常跳过暂时无法反馈
![1](https://github.com/AIsouler/GKD_subscription/assets/78672990/b4bbf55b-5b47-4f09-9588-8ff31b0af828)
![2](https://github.com/AIsouler/GKD_subscription/assets/78672990/0bcce756-8bb1-4827-91b3-e47d6c583a7e)

**Comment by tiki-007** [comment]
> 请问更新到最新版本GKD能正常跳过了吗，我这边测试是能跳过的

另外，订阅号消息界面有时会一直触发点击，但却未有广告，导致卡住，无法正常上下浏览；有时会有点击跳过广告提示，有时没有提示，但gkd中可以看到有点击记录
![3](https://github.com/AIsouler/GKD_subscription/assets/78672990/10a44b0e-28ee-4e9e-9213-ee15c9dac73b)
![4](https://github.com/AIsouler/GKD_subscription/assets/78672990/bda31aa2-6d7a-4b72-9f36-811fac2560bc)

**Comment by AIsouler** [comment]
麻烦发一下快照，截图没有任何作用

**Comment by tiki-007** [comment]
今天遇到订阅号消息页面广告，发现能点击广告，但不进行后续点击（不感兴趣-与我无关-确定）
；查看触发记录却是有触发点击的，但界面没有触发
https://i.gkd.li/i/14716727
![1](https://github.com/AIsouler/GKD_subscription/assets/78672990/f32a45bb-7548-49c5-9d7e-e24e72e3559f)
