### ISSUE TITLE
掌上公交新弹出广告窗口跳不过去

### ISSUE THREAD

**Issue by kunanhai5888** [AIsouler/GKD_subscription#106]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

https://i.gkd.li/import/14587392
https://i.gkd.li/import/14587397
https://i.gkd.li/import/14587363

**Comment by AIsouler** [comment]
0d9253f107862aaf8d03cff32674ffe2354c4d09
