### ISSUE TITLE
oppo软件商店适配需求

### ISSUE THREAD

**Issue by Martinxux** [AIsouler/GKD_subscription#115]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

[软件商店_MainTabActivity-1710947775227.zip](https://github.com/AIsouler/GKD_subscription/files/14669213/_MainTabActivity-1710947775227.zip)
链接：https://i.gkd.li/i/14668997

**Comment by Martinxux** [comment]
> 试试这个
> ```
> {
>   id: 'com.heytap.market',
>   name: '软件商店',
>   groups: [
>     {
>       key: 1,
>       name: '开屏广告',
>       matchTime: 10000,
>       actionMaximum: 1,
>       resetMatch: 'app',
>       rules: [
>         {
>           quickFind: true,
>           matches: '@[clickable=true] > [text*="跳过"][text.length<10][visibleToUser=true]',
>           snapshotUrls: 'https://i.gkd.li/i/14668997',
>         },
>       ],
>     },
>   ],
> }
> ```

这个可以的大佬

**Comment by AIsouler** [comment]
69952c72418b70dafe50aa3364ce700a7557d788
