### ISSUE TITLE
优酷历史记录有广告

### ISSUE THREAD

**Issue by suppermanzero** [AIsouler/GKD_subscription#116]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

历史记录上边的广告https://i.gkd.li/i/14670383

**Comment by AIsouler** [comment]
70c9c91e2b04dbd569d5902a232826c27ddcab1c
