### ISSUE TITLE
蕃茄免费小说以下页面从后台切到前台误触"跳过头尾"按钮，

### ISSUE THREAD

**Issue by kunanhai5888** [AIsouler/GKD_subscription#117]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

https://i.gkd.li/i/14675746
蕃茄兔费小说以下页面从后台切到前台误触"跳过头尾"按钮，建议跳过开屏规则过滤器加上逻辑与运算≠跳过头尾，以免误触跳过头尾按钮，弹出设置头尾页面

**Comment by AIsouler** [comment]
点击记录-在此页面禁用
加上其他运算会拖慢速度

**Comment by kunanhai5888** [comment]
谢谢！


风花雪月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AIsouler/GKD_subscription"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月21日(星期四) 上午9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AIsouler/GKD_subscription] 蕃茄免费小说以下页面从后台切到前台误触"跳过头尾"按钮， (Issue #117)





 
点击记录-在此页面禁用
 加上其他运算会拖慢速度
