### ISSUE TITLE
优酷点开搜索页面

### ISSUE THREAD

**Issue by suppermanzero** [AIsouler/GKD_subscription#118]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

点开搜索页面上边有广告，这吃相越来越难看，开了会员只是播放前没有广告，剩下哪哪都是广告，这个之前还没有呢
https://i.gkd.li/i/14680702

**Comment by AIsouler** [comment]
4ec3ad30f6f36f7925182966bf39b07116ddcd94
