### ISSUE TITLE
通知：停止接受微信订阅号广告适配

### ISSUE THREAD

**Issue by AIsouler** [AIsouler/GKD_subscription#120]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

误触概率太大且原因不明

**Comment by zxpp01** [comment]
请帮忙适配KMB.LWB(香港巴士到站软件）这软件，开屏有，感谢付出。一直都只用这个订阅，很好用。非常感谢

**Comment by AIsouler** [comment]
> 请帮忙适配KMB.LWB(香港巴士到站软件）这软件，开屏有，里面也有，广告太多了，感谢付出。一直都只用这个订阅，很好用。非常感谢

想要适配软件你应该新开一个issue并附上快照，规则是根据快照写的，你不提供快照给我我也没办法
