### ISSUE TITLE
开启微信的 全屏广告-小程序-青桔单车-弹出广告 会和瑞幸小程序的领券页面冲突，一直自动订阅

### ISSUE THREAD

**Issue by D-Jancy** [AIsouler/GKD_subscription#121]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

[微信_AppBrandUI00-1711610177046.zip](https://github.com/AIsouler/GKD_subscription/files/14785402/_AppBrandUI00-1711610177046.zip)

**Comment by AIsouler** [comment]
346f363e819d8d5390f7b4443b5f60856a5905a9
