### ISSUE TITLE
彩云天气

### ISSUE THREAD

**Issue by TianMiao8152** [AIsouler/GKD_subscription#130]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

# 目前只能点击开屏广告，插片广告失效
## 以下是相关截图和快照

广告
[snapshot-1711863959769.zip](https://github.com/Adpro-Team/GKD_subscription/files/14814246/snapshot-1711863959769.zip)

***

广告
[snapshot-1711863943562.zip](https://github.com/Adpro-Team/GKD_subscription/files/14814247/snapshot-1711863943562.zip)

***

广告
[snapshot-1711863851042.zip](https://github.com/Adpro-Team/GKD_subscription/files/14814248/snapshot-1711863851042.zip)

***

点击收起顶部工具栏
[snapshot-1711863804219.zip](https://github.com/Adpro-Team/GKD_subscription/files/14814249/snapshot-1711863804219.zip)

***

广告
[snapshot-1711863756851.zip](https://github.com/Adpro-Team/GKD_subscription/files/14814250/snapshot-1711863756851.zip)

**Comment by AIsouler** [comment]
顶部工具栏收起后的快照发一下

**Comment by TianMiao8152** [comment]
> 顶部工具栏收起后的快照发一下

[Uploading snapshot-1711866001297.zip…]()

**Comment by TianMiao8152** [comment]
补充一个不同样式的广告
[snapshot-1711865983949.zip](https://github.com/AIsouler/GKD_subscription/files/14814357/snapshot-1711865983949.zip)

**Comment by AIsouler** [comment]
![image](https://github.com/AIsouler/GKD_subscription/assets/57941037/5b8e6fc0-0949-4768-afa7-61a340a81c02)
这个有二次弹窗吗

**Comment by TianMiao8152** [comment]
> ![image](https://private-user-images.githubusercontent.com/57941037/318246696-5b8e6fc0-0949-4768-afa7-61a340a81c02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4Njc1MjcsIm5iZiI6MTcxMTg2NzIyNywicGF0aCI6Ii81Nzk0MTAzNy8zMTgyNDY2OTYtNWI4ZTZmYzAtMDk0OS00NzY4LWFmYTctNjFhMzQwYTgxYzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA2NDAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkM2E5ZjJjN2JkNmVhMDU3ZDY2NjYyYmQwYjBhMTI2ZDdkNWU3Y2ZlMTkwYzFkNTA3YWI5MDIzYjBhNTUwMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GPdnzd51ymwba-Vt8qTnOA9qMbafB1TLgbTsD3QcMc8) 这个有二次弹窗吗

二次弹窗是指？点击完关闭就没了

**Comment by AIsouler** [comment]
1d634a1558d7eb4fb8f61ca01727ec06a908e327
