### ISSUE TITLE
求适配小米应用商店-开启推送弹窗

### ISSUE THREAD

**Issue by pheotry** [AIsouler/GKD_subscription#131]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

必要性，不开启推送的情况下，每次重启商店更新软件都会弹出该弹窗。
返回即可关闭该弹窗

快照https://i.gkd.li/i/14814456

[应用商店_UpdateListActivity-1711868596881.zip](https://github.com/AIsouler/GKD_subscription/files/14814457/_UpdateListActivity-1711868596881.zip)

**Comment by AIsouler** [comment]
现有规则有效
![image](https://github.com/AIsouler/GKD_subscription/assets/57941037/e945d635-6407-466a-957c-e3260a4211c2)

**Comment by pheotry** [comment]
> 现有规则有效 ![image](https://private-user-images.githubusercontent.com/57941037/318247774-e945d635-6407-466a-957c-e3260a4211c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NjkxMzAsIm5iZiI6MTcxMTg2ODgzMCwicGF0aCI6Ii81Nzk0MTAzNy8zMTgyNDc3NzQtZTk0NWQ2MzUtNjQwNy00NjZhLTk1N2MtZTMyNjBhNDIxMWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA3MDcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZGI2OWYxNWE4NDMzMGE1Yzc5OTVjMmI1YzAwOTIwYzhiYWY0MmM3NWMzNmE0Nzg2ODdmYWE0NDZlZDQxYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kjvPgLqX07HEddJN-dTd2mOOnta1lLOqPEGqQEiFJSI)

不好意思，是我搞错了
