### ISSUE TITLE
牛客开屏广告

### ISSUE THREAD

**Issue by pheotry** [AIsouler/GKD_subscription#132]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

牛客开屏广告第二种形式。

目前的规则只适配了右边圆形跳过广告，左边圆形跳过则不起作用。
https://i.gkd.li/i/14819443

[牛客_SplashActivity-1711946684449.zip](https://github.com/AIsouler/GKD_subscription/files/14819467/_SplashActivity-1711946684449.zip)

**Comment by AIsouler** [comment]
94fab45f7987f6693a63c09c4e0170d04e24d8e8
