### ISSUE TITLE
丰声协作文档登录和新文档登录

### ISSUE THREAD

**Issue by windong** [AIsouler/GKD_subscription#137]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

https://i.gkd.li/i/14830682
https://i.gkd.li/i/14830687

**Comment by AIsouler** [comment]
cff795796238f3b9e81df8463801bb6baa46530c
