### ISSUE TITLE
99手游加速器首页弹窗广告失效

### ISSUE THREAD

**Issue by xoevdv** [AIsouler/GKD_subscription#139]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

https://i.gkd.li/i/14855686

**Comment by AIsouler** [comment]
896f8bb864be156a6bd4286b3de40721b79502ca
