### ISSUE TITLE
头条里总是“误点”，在搜索框总是命中带有“跳过”的搜索词条，并且这个还归类到开屏广告里，不能单独关闭

### ISSUE THREAD

**Issue by Kurt-Shiwz** [AIsouler/GKD_subscription#143]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

![Screenshot_20240404_165704_com ss android article news](https://github.com/AIsouler/GKD_subscription/assets/7554917/2963551c-c018-471c-a434-5ac3cb820dee)
[今日头条_SearchActivity-1712220929621.zip](https://github.com/AIsouler/GKD_subscription/files/14863948/_SearchActivity-1712220929621.zip)

**Comment by AIsouler** [comment]
点击记录-在此页面禁用
![b22ec1d6fd858b76c5122248fe817de8](https://github.com/AIsouler/GKD_subscription/assets/57941037/f2bac75b-be89-4d2c-8804-dabb279b8ab6)
