### ISSUE TITLE
两步路户外助手的开屏广告规则不执行

### ISSUE THREAD

**Issue by cloudpanl** [AIsouler/GKD_subscription#145]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

两步路户外助手有两个开屏广告，第一个全屏的会执行，第二个非全屏的开屏广告则不执行。用那条规则，在浏览器中“执行选择器”，手机里又能生效，大佬看看是怎么回事
https://i.gkd.li/i/14866147

**Comment by AIsouler** [comment]
9b4a15fa1dd723fa2936fe96d86c531df08c11f3

**Comment by cloudpanl** [comment]
更新了最新的V53版本还是不行，不是matches那行规则的问题，在浏览器中“执行选择器”是生效的，这份是刚抓的快照https://i.gkd.li/i/14895545，大佬要下个APP来研究下才行

**Comment by cloudpanl** [comment]
> 试试这个
> 
> ```
> {
>   id: 'com.lolaage.tbulu.tools',
>   name: '两步路户外助手',
>   groups: [
>     {
>       key: 1,
>       name: '全屏广告-弹窗广告',
>       rules: [
>         {
>           key: 0,
>           name: '腾讯广告',
>           forcedTime: 10000,
>           activityIds: [
>             'com.lolaage.tbulu.tools.ui.activity.WelcomeActivity',
>             'com.lolaage.tbulu.tools.ui.activity.main.MainActivity',
>           ],
>           matches:
>             '[id="android:id/content"] >(3,4) FrameLayout[childCount>4] > FrameLayout[childCount=1] > ImageView',
>           snapshotUrls: [
>             'https://i.gkd.li/i/13627861',
>             'https://i.gkd.li/i/13650732',
>             'https://i.gkd.li/i/14866147',
>           ],
>         },
>       ],
>     },
>   ],
> }
> ```

这个没问题了，请教下forcedTime: 10000是啥意思？
