### ISSUE TITLE
vivo手机 i主题 应用广告

### ISSUE THREAD

**Issue by fxzxmicah** [AIsouler/GKD_subscription#150]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

https://i.gkd.li/i/14904036
https://i.gkd.li/i/14904298

**Comment by AIsouler** [comment]
fe98e2555d4a2176b39214c9889b523112a24f61
