### ISSUE TITLE
小米商店开屏广告

### ISSUE THREAD

**Issue by SteveSteve666** [AIsouler/GKD_subscription#154]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

https://i.gkd.li/i/14927422
[智能服务-1712724092788.zip](https://github.com/AIsouler/GKD_subscription/files/14927174/-1712724092788.zip)

**Comment by AIsouler** [comment]
全局规则有效

**Comment by SteveSteve666** [comment]
> 全局规则有效

其他的全局都有效，就这个跳不过去

**Comment by AIsouler** [comment]
请确保小米智能服务的开屏广告全局规则开启

**Comment by AIsouler** [comment]
> > 请确保小米智能服务的开屏广告全局规则开启
> 
> 都开着的，我看了一下，全局开着，规则里面也有它，但就是跳不了，可能是我手机有bug!?

这个开了？
![Screenshot_2024-04-10-18-41-08-503_li songe gkd-edit](https://github.com/AIsouler/GKD_subscription/assets/57941037/c6116368-be29-4939-963e-cdeb07ee257d)

**Comment by SteveSteve666** [comment]
> > > 请确保小米智能服务的开屏广告全局规则开启
> > 
> > 都开着的，我看了一下，全局开着，规则里面也有它，但就是跳不了，可能是我手机有bug!?
> 
> 这个开了？
> ![Screenshot_2024-04-10-18-41-08-503_li songe gkd-edit](https://github.com/AIsouler/GKD_subscription/assets/57941037/c6116368-be29-4939-963e-cdeb07ee257d)
> 

![Screenshot_2024-04-10-18-45-34-404_li.songe.gkd.jpg](https://github.com/AIsouler/GKD_subscription/assets/125954390/e1586584-078d-4aa1-8b00-c1558c3875fa)

开着的，好像是识别不到这个界面，快照没有它的界面id

**Comment by AIsouler** [comment]
为什么你这个应用少一个全局规则，你用的是我的订阅吗？

**Comment by SteveSteve666** [comment]
> 为什么你这个应用少一个全局规则，你用的是我的订阅吗？

更新那个我没开，是你的😂

**Comment by SteveSteve666** [comment]
> 更新到最新版订阅看看能不能跳过

还是不行，他们的订阅也试过了，也是不行

**Comment by SteveSteve666** [comment]
> 更新到最新版订阅看看能不能跳过

有其他人的可以跳，等我试试回来报告

**Comment by AIsouler** [comment]
明天我再看看

**Comment by SteveSteve666** [comment]
> 明天我再看看

甘霖的可以跳，其他人的都不行https://github.com/ganlinte/GKD-subscription

这个是触发记录找到的规则
{
  name: '开屏广告',
  key: 0,
  matchTime: 10000,
  actionMaximum: 2,
  resetMatch: 'app',
  actionCdKey: 0,
  actionMaximumKey: 0,
  order: -10,
  apps: [
    {
      id: 'com.android.systemui',
      enable: false
    },
    {
      id: 'com.android.settings',
      enable: false
    },
    {
      id: 'com.miui.aod',
      enable: false
    },
    {
      id: 'miui.systemui.plugin',
      enable: false
    },
    {
      id: 'com.tencent.mm',
      enable: false
    },
    {
      id: 'li.songe.gkd',
      enable: false
    },
    {
      id: 'com.magicalstory.AppStore',
      enable: false
    },
    {
      id: 'mark.via',
      enable: false
    },
    {
      id: 'com.mycompany.app.soulbrowser',
      enable: false
    },
    {
      id: 'com.mmbox.xbrowser',
      enable: false
    },
    {
      id: 'info.muge.appshare',
      enable: false
    },
    {
      id: 'net.csdn.csdnplus',
      enable: false
    },
    {
      id: 'make.more.r2d2.cellular_z',
      enable: false
    },
    {
      id: 'com.eco.global.app',
      enable: false
    },
    {
      id: 'com.superrhino.rarering',
      enable: false
    },
    {
      id: 'com.ksf.yyx',
      enable: false
    },
    {
      id: 'com.cyl.musiccy.ou',
      enable: false
    },
    {
      id: 'com.picacomic.fregata',
      enable: false
    },
    {
      id: 'com.tencent.mobileqq',
      enable: false
    },
    {
      id: 'cn.soulapp.android',
      enable: false
    },
    {
      id: 'com.taptap',
      enable: false
    },
    {
      id: 'com.dubox.drive',
      enable: false
    },
    {
      id: 'dxwt.questionnaire.ui',
      enable: false
    },
    {
      id: 'com.mfcloudcalculate.networkdisk',
      enable: false
    },
    {
      id: 'com.dfsly.bbs',
      enable: false
    },
    {
      id: 'com.chunqiu.ah',
      enable: false
    },
    {
      id: 'gov.pianzong.androidnga',
      enable: false
    },
    {
      id: 'com.tencent.mtt',
      enable: false
    },
    {
      id: 'com.tencent.androidqqmail',
      enable: false
    },
    {
      id: 'com.UCMobile',
      enable: false
    },
    {
      id: 'com.upupoo.apu.mobile',
      enable: false
    },
    {
      id: 'com.midea.vm.washer',
      enable: false
    },
    {
      id: 'com.qiyi.video',
      enable: false
    },
    {
      id: 'com.qiyi.video.lite',
      enable: false
    },
    {
      id: 'com.hanweb.android.sdzwfw.activity',
      enable: false
    },
    {
      id: 'com.shanghaionstar',
      enable: false
    },
    {
      id: 'com.baidu.tieba',
      enable: false
    },
    {
      id: 'com.byfen.market',
      enable: false
    },
    {
      id: 'tv.danmaku.bili',
      enable: false
    },
    {
      id: 'tv.danmaku.bilibilihd',
      enable: false
    },
    {
      id: 'com.sfacg',
      enable: false
    },
    {
      id: 'com.kuangxiangciweimao.novel',
      enable: false
    },
    {
      id: 'cn.damai',
      enable: false
    },
    {
      id: 'com.delicloud.app.smartoffice',
      enable: false
    },
    {
      id: 'com.zlfcapp.batterymanager',
      enable: false
    },
    {
      id: 'com.dianxinai.mobile',
      enable: false
    },
    {
      id: 'com.didapinche.booking',
      enable: false
    },
    {
      id: 'com.citiccard.mobilebank',
      enable: false
    },
    {
      id: 'com.dongqiudi.news',
      enable: false
    },
    {
      id: 'com.diershoubing.erbing',
      enable: false
    },
    {
      id: 'com.feeyo.vz.pro.cdm',
      enable: false
    },
    {
      id: 'com.fbank.mobile',
      enable: false
    },
    {
      id: 'com.xpx365.projphoto',
      enable: false
    },
    {
      id: 'com.huawei.browser',
      enable: false
    },
    {
      id: 'com.huawei.himovie',
      enable: false
    },
    {
      id: 'com.huawei.android.totemweather',
      enable: false
    },
    {
      id: 'com.huawei.music',
      enable: false
    },
    {
      id: 'com.android.mediacenter',
      enable: false
    },
    {
      id: 'com.huawei.health',
      enable: false
    },
    {
      id: 'com.huawei.android.thememanager',
      enable: false
    },
    {
      id: 'com.handsgo.jiakao.android',
      enable: false
    },
    {
      id: 'com.yek.android.kfc.activitys',
      enable: false
    },
    {
      id: 'com.kkeji.news.client',
      enable: false
    },
    {
      id: 'com.coolapk.market',
      enable: false
    },
    {
      id: 'com.kugou.android',
      enable: false
    },
    {
      id: 'com.ecellsz.watch.guard',
      enable: false
    },
    {
      id: 'com.hxak.liangongbao',
      enable: false
    },
    {
      id: 'com.manmanbuy.bijia',
      enable: false
    },
    {
      id: 'com.antfortune.wealth',
      enable: false
    },
    {
      id: 'com.paokeji.yiqu',
      enable: false
    },
    {
      id: 'com.motoband',
      enable: false
    },
    {
      id: 'com.mostone.life',
      enable: false
    },
    {
      id: 'com.nowcoder.app.florida',
      enable: false

**Comment by AIsouler** [comment]
试试这个
```
{
  id: 'com.miui.systemAdSolution',
  name: '智能服务',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      quickFind: true,
      matchTime: 10000,
      resetMatch: 'app',
      actionMaximum: 1,
      rules: [
        {
          matches: '[text*="跳过"][text.length<10][visibleToUser=true]',
          snapshotUrls: 'https://i.gkd.li/i/14927422',
        },
      ],
    },
  ],
}
```

**Comment by SteveSteve666** [comment]
> 试试这个
> ```
> {
>   id: 'com.miui.systemAdSolution',
>   name: '智能服务',
>   groups: [
>     {
>       key: 1,
>       name: '开屏广告',
>       quickFind: true,
>       matchTime: 10000,
>       resetMatch: 'app',
>       actionMaximum: 1,
>       rules: [
>         {
>           matches: '[text*="跳过"][text.length<10][visibleToUser=true]',
>           snapshotUrls: 'https://i.gkd.li/i/14927422',
>         },
>       ],
>     },
>   ],
> }
> ```

这个可以👍

**Comment by AIsouler** [comment]
> > 试试这个
> > ```
> > {
> >   id: 'com.miui.systemAdSolution',
> >   name: '智能服务',
> >   groups: [
> >     {
> >       key: 1,
> >       name: '开屏广告',
> >       quickFind: true,
> >       matchTime: 10000,
> >       resetMatch: 'app',
> >       actionMaximum: 1,
> >       rules: [
> >         {
> >           matches: '[text*="跳过"][text.length<10][visibleToUser=true]',
> >           snapshotUrls: 'https://i.gkd.li/i/14927422',
> >         },
> >       ],
> >     },
> >   ],
> > }
> > ```
> 
> 这个可以👍

这个就是全局规则里的

**Comment by SteveSteve666** [comment]
> > > 试试这个
> > > ```
> > > {
> > >   id: 'com.miui.systemAdSolution',
> > >   name: '智能服务',
> > >   groups: [
> > >     {
> > >       key: 1,
> > >       name: '开屏广告',
> > >       quickFind: true,
> > >       matchTime: 10000,
> > >       resetMatch: 'app',
> > >       actionMaximum: 1,
> > >       rules: [
> > >         {
> > >           matches: '[text*="跳过"][text.length<10][visibleToUser=true]',
> > >           snapshotUrls: 'https://i.gkd.li/i/14927422',
> > >         },
> > >       ],
> > >     },
> > >   ],
> > > }
> > > ```
> > 
> > 这个可以👍
> 
> 这个就是全局规则里的
全局还是不跳，这个规则单拎出来就可以

**Comment by SteveSteve666** [comment]
> 更新到最新版后能跳了吗，把其他订阅和本地规则关闭试试看

可以了

**Comment by zaonie** [comment]
新情况
我的手机未root，miui 14.0.7
智能服务的第一个开屏选项打不开，显示内置应用无法修改。。
下方的第二个开屏选项就能打开。如图。
![Screenshot_2024-04-12-06-20-22-131_li.songe.gkd.jpg](https://github.com/AIsouler/GKD_subscription/assets/48220895/fd129ee6-c18b-40ba-b86f-5269a986f9dc)



尝试用甘霖的订阅呢，就能打开唯一的这个开屏选项。不知道他对应的是您的第一项还是第二项。
![Screenshot_2024-04-12-06-22-05-132_li.songe.gkd.jpg](https://github.com/AIsouler/GKD_subscription/assets/48220895/925094c9-1813-4380-bdeb-4136f712d65c)



原因未知。

**Comment by AIsouler** [comment]
> 感谢作者以及楼上的各位网友。
> 
> 新情况 我的手机未root，miui 14.0.7。 智能服务的第一个开屏选项打不开，显示内置禁用无法修改。。 下方的第二个开屏选项就能打开。如图。 ![Screenshot_2024-04-12-06-20-22-131_li.songe.gkd.jpg](https://private-user-images.githubusercontent.com/48220895/321800870-fd129ee6-c18b-40ba-b86f-5269a986f9dc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODU3MDUsIm5iZiI6MTcxMjg4NTQwNSwicGF0aCI6Ii80ODIyMDg5NS8zMjE4MDA4NzAtZmQxMjllZTYtYzE4Yi00MGJhLWI4NmYtNTI2OWE5ODZmOWRjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAxMzAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MDAwNDkwODkyNThiYzlmM2Y5OGYyMDkxMmNkYzc5ZWM0MmFlNDc3NzA2OTRlM2Y4ZmY3YTdmOGMzYTE1YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ef6ZJqaQtKoN2UiWXi-rnLby-blSeTExovaUD1ajKYI)
> 
> 尝试用甘霖的订阅呢，就能打开唯一的这个开屏选项。不知道他对应的是您的第一项还是第二项。 ![Screenshot_2024-04-12-06-22-05-132_li.songe.gkd.jpg](https://private-user-images.githubusercontent.com/48220895/321800956-925094c9-1813-4380-bdeb-4136f712d65c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODU3MDUsIm5iZiI6MTcxMjg4NTQwNSwicGF0aCI6Ii80ODIyMDg5NS8zMjE4MDA5NTYtOTI1MDk0YzktMTgxMy00MzgwLWJkZWItNDEzNmY3MTJkNjVjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAxMzAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYTAwYjI3NjVmMWMzYzZlZDNjZTU5MDFlMTlhOWE2MmEzOWQ5MjExMmU1NDhmMGM4ZDZlZjQ0ZjNhYjg4ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ce_a2OQXIjO5ptgvy_HxiKlMXhdo2L8YIKvKnBS6qhQ)
> 
> 原因未知。

开启下面那个就行了，横线上面那几个是全局规则https://github.com/AIsouler/GKD_subscription/blob/a6cf1febb7bfd91aa4941e18efb974f87a8b25fe/src/globalDefaultApps.ts#L139
