### ISSUE TITLE
两步路户外助手没有适配到的两个弹框

### ISSUE THREAD

**Issue by cloudpanl** [AIsouler/GKD_subscription#158]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

偶尔会出现的两个东西
https://i.gkd.li/i/14952803
https://i.gkd.li/i/14952807

**Comment by AIsouler** [comment]
284df7f240e6d438b5c3d573b8c591392a97817d
