### ISSUE TITLE
微信农信易扫小程序付款完成后弹出的广告

### ISSUE THREAD

**Issue by 1celife** [AIsouler/GKD_subscription#159]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

https://i.gkd.li/i/14954516
点击右上角X

**Comment by adproqwq** [comment]
不予适配

**Comment by AIsouler** [comment]
#120
