### ISSUE TITLE
酷安分段广告新卡片弹窗

### ISSUE THREAD

**Issue by pheotry** [AIsouler/GKD_subscription#160]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

https://i.gkd.li/i/14964859
[酷安_DynamicNodePageActivity-1712972496020.zip](https://github.com/AIsouler/GKD_subscription/files/14964872/_DynamicNodePageActivity-1712972496020.zip)

**Comment by AIsouler** [comment]
c52b9af11433449cf644dd1d47e1748fd427e9bd
