### ISSUE TITLE
快手青少年弹窗不执行规则

### ISSUE THREAD

**Issue by SteveSteve666** [AIsouler/GKD_subscription#161]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

https://i.gkd.li/i/14965930
[快手_HomeActivity-1712999977829.zip](https://github.com/AIsouler/GKD_subscription/files/14965944/_HomeActivity-1712999977829.zip)

**Comment by SteveSteve666** [comment]
![Screenshot_2024-04-13-17-56-30-557_li.songe.gkd.jpg](https://github.com/AIsouler/GKD_subscription/assets/125954390/23525f81-50b4-4b70-9700-dd16497de19b)

全局正常开启

**Comment by AIsouler** [comment]
无法适配
