### ISSUE TITLE
皮皮喵的开屏广告点击有问题

### ISSUE THREAD

**Issue by Invincible-World** [AIsouler/GKD_subscription#167]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

皮皮喵的开屏广告点击有问题,只会第一步点击右上角的叉,不会后面的点击放弃奖励和点击关闭喵
https://i.gkd.li/i/15008493 放弃奖励
https://i.gkd.li/i/15008500 关闭喵

**Comment by AIsouler** [comment]
b0cbc61f2355caa2b7d3bfc29958b90167ae6a03
