### ISSUE TITLE
lofter的开屏广告无法跳过，点击记录内没有跳过的记录

### ISSUE THREAD

**Issue by Unbengabled** [AIsouler/GKD_subscription#170]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

图片分别为点击记录、跳过选项的设置以及该广告本身的界面
![Screenshot_20240418_184600_li songe gkd](https://github.com/AIsouler/GKD_subscription/assets/103240622/6e3d3819-fc4f-41d2-9d3c-d37b1af10652)
![Screenshot_20240418_184521_li songe gkd](https://github.com/AIsouler/GKD_subscription/assets/103240622/2afd1c1e-ec27-47b0-b653-3d4abf189667)
![Screenshot_20240418_125457_com lofter android](https://github.com/AIsouler/GKD_subscription/assets/103240622/48b6a7fe-ba14-42db-9d4d-dae271904aa5)

[snapshot-1713415457701.zip](https://github.com/AIsouler/GKD_subscription/files/15023581/snapshot-1713415457701.zip)

**Comment by AIsouler** [comment]
ab8227538799caa7ede85be6e5572ae455087e12
