### ISSUE TITLE
全局跳过开屏广告问题

### ISSUE THREAD

**Issue by Invincible-World** [AIsouler/GKD_subscription#177]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

全局跳过开屏广告误触概率太高了,只有app有里跳过两字就点,一般开屏广告只是在打开app的开始阶段,可不可让全局规则像李跳跳一样只在打开app一开始的几秒进行识别呢

**Comment by AIsouler** [comment]
全局规则匹配时间是进入软件后的10s内，遇到误触在点击记录里选择```在此页面禁用```或```在此应用禁用```就行了，规则太宽泛就会有这样的问题，目前没有很好的解决办法

**Comment by AIsouler** [comment]
108版本已解决全局规则（开屏广告）在应用搜索页误触的问题

**Comment by filusilia** [comment]
去哪旅行app，在进入购买订单详情页会自动点击取消订单，
![9895bfdafbaeb370a2742d88b398308](https://github.com/user-attachments/assets/b1f976ee-28dc-4c95-9793-46ac6f28731c)
