### ISSUE TITLE
百度贴吧：功能类-贴吧内签到并关闭弹窗 失效

### ISSUE THREAD

**Issue by LingEmberMaple** [AIsouler/GKD_subscription#185]
### 请输入 误触/不执行规则 的界面的快照或者生成的快照链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

从打开百度贴吧到进入贴吧页的触发记录
![从打开百度贴吧到进入贴吧页的触发记录](https://github.com/AIsouler/GKD_subscription/assets/69679868/d2a258b4-de83-48bd-b740-5338ac1d7226)
[快照（贴吧页签到）](https://i.gkd.li/i/15087289)
[快照（签到成功-弹窗）](https://i.gkd.li/i/15087327)

目标节点clickable属性值变为false

**Comment by AIsouler** [comment]
5008c81b20ab5f77b6215fbe32ee384a8f7c1f81
