### ISSUE TITLE
华为应用市场

### ISSUE THREAD

**Issue by Tensor33** [AIsouler/GKD_subscription#208]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

[华为应用市场_MainActivity-1715261926334.zip](https://github.com/AIsouler/GKD_subscription/files/15265505/_MainActivity-1715261926334.zip)

**Comment by AIsouler** [comment]
https://github.com/orgs/gkd-kit/discussions/615

**Comment by AIsouler** [comment]
你试试手动关闭再打开后能不能生效
