### ISSUE TITLE
希望增加抖音打开默认切换到列表模式功能

### ISSUE THREAD

**Issue by wonderfulweather** [AIsouler/GKD_subscription#226]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

https://i.gkd.li/i/15444198，快照链接如上。点下首页旁边的切换按钮就可以切换，希望大大适配一下

**Comment by AIsouler** [comment]
切换后的快照发一下

**Comment by wonderfulweather** [comment]
切换后好像还是在mainactivity里面，快照截不到。
![image](https://github.com/AIsouler/GKD_subscription/assets/170818680/03df9fdb-f0e7-418e-8881-8e165ba0917b)

**Comment by AIsouler** [comment]
> 切换后好像还是在mainactivity里面，快照截不到。

这个界面获取不到快照？

**Comment by wonderfulweather** [comment]
用同样的方法，截不到
