### ISSUE TITLE
请增加上海农商银行跳过开屏读秒广告

### ISSUE THREAD

**Issue by free-diy** [AIsouler/GKD_subscription#228]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 确保提供正确的快照, 否则我同意维护者直接关闭issue
- [X] 确保已阅读[#120](https://github.com/AIsouler/GKD_subscription/issues/120)，并确认需适配的快照不在不予适配的范围内，否则我同意维护者直接关闭问题

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

快照：
https://i.gkd.li/i/15491928

**Comment by AIsouler** [comment]
全局规则有效，开屏的时候有跳过提示吗？

**Comment by free-diy** [comment]
> 全局规则有效，开屏的时候有跳过提示吗？

开屏有读秒提示，可点击跳过，但是全屏规则无效。
还是读完3秒后才会进主界面，或者手动点跳过才进主界面

**Comment by AIsouler** [comment]
我的意思是有没有点击提示，也就是触发了点击没有

**Comment by free-diy** [comment]
> 我的意思是有没有点击提示，也就是触发了点击没有

没有点击提示

**Comment by AIsouler** [comment]
```
{
  id: 'com.srcb.pmbank',
  name: '上海农商银行',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      quickFind: true,
      matchTime: 10000,
      resetMatch: 'app',
      actionMaximum: 1,
      rules: [
        {
          action: 'clickCenter',
          matches: '[text*="跳过"][text.length<10][visibleToUser=true]',
          snapshotUrls: 'https://i.gkd.li/i/15491928',
        },
      ],
    },
  ],
}
```
导入本地规则试试

**Comment by free-diy** [comment]
> ```
> {
>   id: 'com.srcb.pmbank',
>   name: '上海农商银行',
>   groups: [
>     {
>       key: 1,
>       name: '开屏广告',
>       quickFind: true,
>       matchTime: 10000,
>       resetMatch: 'app',
>       actionMaximum: 1,
>       rules: [
>         {
>           action: 'clickCenter',
>           matches: '[text*="跳过"][text.length<10][visibleToUser=true]',
>           snapshotUrls: 'https://i.gkd.li/i/15491928',
>         },
>       ],
>     },
>   ],
> }
> ```
> 
> 导入本地规则试试

试了，还是不行

**Comment by free-diy** [comment]
{"com.srcb.pmbank":[{"activityName":"com.yitong.mobile.biz.launcher.app.SplashActivity","className":"android.widget.Chronometer","clickable":true,"description":"0秒钟","idName":"com.srcb.pmbank:id/chronometer","onlyClick":false,"packageName":"com.srcb.pmbank","position":{"bottom":181,"left":1164,"right":1407,"top":80},"text":"跳过 3s"}]}
李跳跳用这个能跳过去，gkd不知道怎么改

**Comment by free-diy** [comment]
> > 我的意思是有没有点击提示，也就是触发了点击没有
> 
> 没有点击提示

有点击提示，可还是不行

**Comment by free-diy** [comment]
![微信图片_20240531093829](https://github.com/AIsouler/GKD_subscription/assets/71208560/6931e8e0-666a-4fde-af91-32d12d148cdf)
可是还是跳不过去

**Comment by AIsouler** [comment]
我下载了这个软件，经测试无法跳过，这个软件可能使用了某种特殊手段

**Comment by free-diy** [comment]
> 我下载了这个软件，经测试无法跳过，这个软件可能使用了某种特殊手段

我用了gkd1.67 https://github.com/tlw00988/gkd/releases 自带的开屏广告能跳过去，蛮怪的

**Comment by AIsouler** [comment]
> 我用了gkd1.67 https://github.com/tlw00988/gkd/releases 自带的开屏广告能跳过去，蛮怪的

我这边使用这个版本还是有跳不过的情况

**Comment by free-diy** [comment]
> > 我用了gkd1.67 https://github.com/tlw00988/gkd/releases 自带的开屏广告能跳过去，蛮怪的
> 
> 我这边使用这个版本还是有跳不过的情况

确实，有点怪，有时能跳过有时却失效，时好时坏的。

**Comment by free-diy** [comment]
李跳跳里用下面规则能100%跳过
{"com.srcb.pmbank":[{"activityName":"com.yitong.mobile.biz.launcher.app.SplashActivity","className":"android.widget.Chronometer","clickable":true,"description":"0秒钟","idName":"com.srcb.pmbank:id/chronometer","onlyClick":false,"packageName":"com.srcb.pmbank","position":{"bottom":181,"left":1164,"right":1407,"top":80},"text":"跳过 3s"}]}

**Comment by AIsouler** [comment]
你这个规则格式是错的

**Comment by free-diy** [comment]
> 这不是规则吧

我不是很懂，这个是雷跳跳生成的，然后我把它导入到李跳跳里就可以跳过上海农商银行的开屏广告

**Comment by AIsouler** [comment]
这个软件生成的规则并不能导入到李跳跳

**Comment by free-diy** [comment]
> 这个软件生成的规则并不能导入到李跳跳

![Screenshot_20240601_205417](https://github.com/AIsouler/GKD_subscription/assets/71208560/0d2ac1db-4316-43cc-854c-26975fba7de1)

**Comment by AIsouler** [comment]
我的意思是李跳跳并不能识别这个软件生成的规则，格式和李跳跳的规则不一样

**Comment by free-diy** [comment]
> 我的意思是李跳跳并不能识别这个软件生成的规则，格式和李跳跳的规则不一样

要修改一下的
[{"activityName":"com.yitong.mobile.biz.launcher.app.SplashActivity","className":"android.widget.Chronometer","clickable":true,"description":"0秒钟","idName":"com.srcb.pmbank:id/chronometer","onlyClick":false,"packageName":"com.srcb.pmbank","position":{"bottom":181,"left":1164,"right":1407,"top":80},"text":"跳过 3s"}]

**Comment by free-diy** [comment]
> 我的意思是李跳跳并不能识别这个软件生成的规则，格式和李跳跳的规则不一样

[{"activityName":"com.yitong.mobile.biz.launcher.app.SplashActivity","className":"android.widget.Chronometer","clickable":true,"description":"0秒钟","idName":"com.srcb.pmbank:id/chronometer","onlyClick":false,"packageName":"com.srcb.pmbank","position":{"bottom":181,"left":1164,"right":1407,"top":80},"text":"跳过 3s"}]

**Comment by AIsouler** [comment]
> [{"activityName":"com.yitong.mobile.biz.launcher.app.SplashActivity","className":"android.widget.Chronometer","clickable":true,"description":"0秒钟","idName":"com.srcb.pmbank:id/chronometer","onlyClick":false,"packageName":"com.srcb.pmbank","position":{"bottom":181,"left":1164,"right":1407,"top":80},"text":"跳过 3s"}]

使用李跳跳导入这条规则还是会有跳不过的情况
