### ISSUE TITLE
微信朋友圈广告只点开广告标签，不会点关闭广告

### ISSUE THREAD

**Issue by maxqq001** [AIsouler/GKD_subscription#231]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的

- [X] 确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

微信朋友圈广告只点开广告标签，不会点关闭广告
请问这是什么情况呢？
[Uploading 微信_ImproveSnsTimelineUI-1717402472324.zip…]()

**Comment by AIsouler** [comment]
你的快照链接打不开

**Comment by maxqq001** [comment]
[微信_ImproveSnsTimelineUI-1717402472324.zip](https://github.com/user-attachments/files/15531230/_ImproveSnsTimelineUI-1717402472324.zip)
这个可以吗？

**Comment by AIsouler** [comment]
>  这个可以吗？
可以，发一下第一段的快照

**Comment by maxqq001** [comment]
请问，什么是第一段快照？

**Comment by AIsouler** [comment]
就是需要点击```广告```按钮的页面的快照

**Comment by maxqq001** [comment]
[微信_ImproveSnsTimelineUI-1717405424589.zip](https://github.com/user-attachments/files/15531528/_ImproveSnsTimelineUI-1717405424589.zip)
这个吗？

**Comment by maxqq001** [comment]
[Uploading log-1717405317528.zip…]()
日志

**Comment by maxqq001** [comment]
[log-1717405317528.zip](https://github.com/user-attachments/files/15531572/log-1717405317528.zip)
日志文件

**Comment by maxqq001** [comment]
谢谢
