### ISSUE TITLE
Turrit 误触

### ISSUE THREAD

**Issue by beipuo** [AIsouler/GKD_subscription#233]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的

- [X] 确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

包名：org.telegram.group
错误行为：打开频道自动点击页面上方。
[Uploading Turrit_HomeActivity-1717421646814.zip…]()

**Comment by beipuo** [comment]
https://github.com/AIsouler/GKD_subscription/assets/100417978/f23e1f8b-a110-477e-a3f5-040970c665f2

**Comment by AIsouler** [comment]
你的快照链接打不开，是不是还没上传完就提交了

**Comment by AIsouler** [comment]
说明是哪一条规则误触，点击记录里可以看到

**Comment by beipuo** [comment]
https://i.gkd.li/i/15536175
https://i.gkd.li/i/15536179
第一个链接为点击前页面
第二个链接为点击后页面
属于开屏广告

**Comment by AIsouler** [comment]
a06fb3c85c9392f27b7d6725ad10556203f59b8d
