### ISSUE TITLE
快对开屏广告跳过失效

### ISSUE THREAD

**Issue by chinese-wzq** [AIsouler/GKD_subscription#235]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的

- [X] 确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

快照：https://i.gkd.li/i/15741399
现象：程序会尝试点击两次跳过按钮，但广告无法被跳过。之后及时人工点击跳过按钮，也无法跳过广告。倒计时结束后，广告仍然存在永远不会消失，必须在后台划掉快对，进入后人工抢在gkd前面单击跳过按钮。已开启shizuku

**Comment by adproqwq** [comment]
看起来跟微信订阅号列表广告有些相同

**Comment by AIsouler** [comment]
导入到本地试试
```
{
  id: 'com.kuaiduizuoye.scan',
  name: '快对',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      rules: [
        {
          quickFind: true,
          action: 'clickCenter',
          matches: 'FrameLayout > FrameLayout[childCount>2] > @View[clickable=true][visibleToUser=true] + TextView[text=null] <<n [id="android:id/content"]',
          snapshotUrls: 'https://i.gkd.li/i/15741399',
        },
      ],
    },
  ],
}
```

**Comment by chinese-wzq** [comment]
> 导入到本地试试
> 
> ```
> {
>   id: 'com.kuaiduizuoye.scan',
>   name: '快对',
>   groups: [
>     {
>       key: 1,
>       name: '开屏广告',
>       matchTime: 10000,
>       actionMaximum: 1,
>       resetMatch: 'app',
>       rules: [
>         {
>           quickFind: true,
>           action: 'clickCenter',
>           matches: 'FrameLayout > FrameLayout[childCount>2] > @View[clickable=true][visibleToUser=true] + TextView[text=null] <<n [id="android:id/content"]',
>           snapshotUrls: 'https://i.gkd.li/i/15741399',
>         },
>       ],
>     },
>   ],
> }
> ```

导入后对于圆形按钮的可以跳过了，但之后又出现了长条形的跳过，gkd无法识别所以跳过又失效了。
这是长条形跳过的快照：https://i.gkd.li/i/15746254
不得不说快对是真恶心，吃相太难看了，开vip还有广告

**Comment by AIsouler** [comment]
5e308209f296e4b89a5b9eb0307d40407e3dd654

**Comment by chinese-wzq** [comment]
实测可用了
