### ISSUE TITLE
youtube app问题

### ISSUE THREAD

**Issue by free-diy** [AIsouler/GKD_subscription#237]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的

- [X] 确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

开屏广告规则问题，每次打开youtube app会自动播放视频。 关了开屏广告后，打开app就不会自动播放视频了

**Comment by AIsouler** [comment]
需要误触界面快照

**Comment by free-diy** [comment]
![Screenshot_20240610_064422](https://github.com/AIsouler/GKD_subscription/assets/71208560/e5ae125e-9b14-4200-9936-57cb8299b7ac)

**Comment by AIsouler** [comment]
你知道快照是什么吗？提issue的时候一大堆说明为什么不看？

**Comment by free-diy** [comment]
> 你知道快照是什么吗？提issue的时候一大堆说明为什么不看？

https://i.gkd.li/i/15756618

**Comment by free-diy** [comment]
我不知道要保存哪个快照，反正进app界面后不用点就直接播放第一个视频了

**Comment by AIsouler** [comment]
> 我不知道要保存哪个快照，反正进app界面后不用点就直接播放第一个视频了，具体看不到是误点哪里了，速度太快了

关闭误触的规则再截快照

**Comment by free-diy** [comment]
> > 我不知道要保存哪个快照，反正进app界面后不用点就直接播放第一个视频了，具体看不到是误点哪里了，速度太快了
> 
> 关闭误触的规则再截快照

https://i.gkd.li/i/15756688 这个是关闭规则，打开app快照

**Comment by AIsouler** [comment]
哪条规则误触？点击记录里可以看到

**Comment by AIsouler** [comment]
3728cff3842ac68d717044b0f435059a7a9a38a6

**Comment by free-diy** [comment]
> 哪条规则误触？点击记录里可以看到

开屏广告误触

**Comment by free-diy** [comment]
> [3728cff](https://github.com/AIsouler/GKD_subscription/commit/3728cff3842ac68d717044b0f435059a7a9a38a6)

刚更新了下规则，还是会自动播放app里第一个视频。试了下梦念逍遥的开屏广告规则，他的没这个问题。

**Comment by AIsouler** [comment]
我还没发布更新你从哪更新的？

**Comment by AIsouler** [comment]
https://github.com/AIsouler/GKD_subscription/releases/tag/v93
