### ISSUE TITLE
Luka阅读养成的通知服务提醒

### ISSUE THREAD

**Issue by hpliu01** [AIsouler/GKD_subscription#240]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 我确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 我确保已阅读[#120](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue
- [X] 我确保提供正确的快照, 否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

[snapshot-1718155726204.zip](https://github.com/user-attachments/files/15796595/snapshot-1718155726204.zip)
快照如附件，需要点击取消，谢谢！

**Comment by AIsouler** [comment]
95be78ef5813d6143a3a63320f2bf2e8da9678d1
