### ISSUE TITLE
CamHipro

### ISSUE THREAD

**Issue by pidanpro** [AIsouler/GKD_subscription#243]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 我确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 我确保已阅读[#120](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue
- [X] 我确保提供正确的快照, 否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/i/15843926

监控软件，下方广告窗口。

**Comment by AIsouler** [comment]
你的快照没有截图，请授予gkd截图权限后再截快照

**Comment by pidanpro** [comment]
https://i.gkd.li/i/15847732

**Comment by pidanpro** [comment]
> 你的快照没有截图，请授予gkd截图权限后再截取快照

https://i.gkd.li/i/15847732

**Comment by AIsouler** [comment]
45f2317e71e43f290619088015c2ac6237741f0a

**Comment by pidanpro** [comment]
> [45f2317](https://github.com/AIsouler/GKD_subscription/commit/45f2317e71e43f290619088015c2ac6237741f0a)

![微信图片_20240615213049](https://github.com/AIsouler/GKD_subscription/assets/131292481/1bf7d2a1-e7ae-437a-9b23-84bcac86a2da)
是从导入数据 文件进去吗？ 为什么显示是黑的 导不进去 我不太理解 小白 不好意思 求指教

**Comment by AIsouler** [comment]
需要等我发布更新https://github.com/AIsouler/GKD_subscription/releases

**Comment by pidanpro** [comment]
> 需要等我发布更新https://github.com/AIsouler/GKD_subscription/releases电影等我发布更多https://github.com/AIsouler/GKD_subscription/releases

嗷嗷，好的。咱们这个有没有lsp模块

**Comment by pidanpro** [comment]
> 需要等我发布更新https://github.com/AIsouler/GKD_subscription/releases

嗷嗷，好的。咱们这个软件 有没有lsp模块

**Comment by AIsouler** [comment]
> 嗷嗷，好的。咱们这个软件 有没有lsp模块

没有
