### ISSUE TITLE
最右APP 启动广告

### ISSUE THREAD

**Issue by declandragon** [AIsouler/GKD_subscription#245]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 我确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 我确保已阅读[#120](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue
- [X] 我确保提供正确的快照, 否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

[最右_SplashActivity-1718512595698.zip](https://github.com/user-attachments/files/15856184/_SplashActivity-1718512595698.zip)

**Comment by AIsouler** [comment]
导入这条规则，然后关闭全局规则，然后把不能跳的页面或误触页面的快照发过来
```
{
  id: 'cn.xiaochuankeji.tieba',
  name: '最右',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      rules: [
        {
          quickFind: true,
          position: {
            left: 'width * 0.8903',
            top: 'width * 0.1271',
          },
          matches: '[vid="contentView"]',
          snapshotUrls: 'https://i.gkd.li/i/15856190',
        },
      ],
    },
  ],
}
```

**Comment by declandragon** [comment]
[最右_SplashActivity-1718525542559.zip](https://github.com/user-attachments/files/15856639/_SplashActivity-1718525542559.zip)

**Comment by declandragon** [comment]
> [最右_SplashActivity-1718525542559.zip](https://github.com/user-attachments/files/15856639/_SplashActivity-1718525542559.zip)

这个关闭了所有的规则，可能是错误的

**Comment by declandragon** [comment]
这个只开启了上面那条本地规则

[最右_SplashActivity-1718526026394.zip](https://github.com/user-attachments/files/15856662/_SplashActivity-1718526026394.zip)

**Comment by AIsouler** [comment]
只开上面那条本地规则，多次打开软件看看有没有跳不过的，然后截快照

**Comment by AIsouler** [comment]
快照可以直接发链接的

**Comment by declandragon** [comment]
> 这个只开启了上面那条本地规则
> 
> [最右_SplashActivity-1718526026394.zip](https://github.com/user-attachments/files/15856662/_SplashActivity-1718526026394.zip)



这次识别到了，截图里面有 『GKD』 的提示，但是并没有跳过。

只开这个规则，尝试了很多次，只有一次成功跳过了。

很多时候，并没有提示 『GKD』 ，没识别到，谢谢

**Comment by AIsouler** [comment]
更新到最新版规则看看

**Comment by declandragon** [comment]
> 更新到最新版规则看看

更新了，同时开启本地规则和订阅规则，识别到了👏👏👏

有个特殊情况，就是一开始广告没出来，已经提示了 『GKD』，等广告出来后 并没有跳过😂

**Comment by declandragon** [comment]
https://github.com/AIsouler/GKD_subscription/assets/37643710/7e282b13-c30e-4455-aa93-ac6e9ee7fcea

**Comment by AIsouler** [comment]
> 就是一开始广告没出来，已经提示了 『GKD』

发一下这个时候的快照

**Comment by declandragon** [comment]
https://i.gkd.li/i/15860806  广告出来后

https://i.gkd.li/i/15860818  广告出来前

**Comment by AIsouler** [comment]
导入测试
```
{
  id: 'cn.xiaochuankeji.tieba',
  name: '最右',
  groups: [
    {
      key: -1,
      name: '开屏广告',
      quickFind: true,
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      actionMaximumKey: 0,
      rules: [
        {
          key: 0,
          matches: '[text*="跳过"][text.length<10][visibleToUser=true]',
          snapshotUrls: [
            'https://i.gkd.li/i/15858014',
            'https://i.gkd.li/i/15858024',
          ],
        },
        {
          key: 1,
          matches:
            'FrameLayout > FrameLayout[childCount>2] > @View[clickable=true][visibleToUser=true] + TextView[text=null] <<n [id="android:id/content"]',
          snapshotUrls: 'https://i.gkd.li/i/15858023',
        },
        {
          key: 2,
          actionDelay: 2000,
          position: {
            left: 'width * 0.8903',
            top: 'width * 0.1342',
          },
          matches: '[vid="contentView"][visibleToUser=true]',
          snapshotUrls: [
            'https://i.gkd.li/i/15856190',
            'https://i.gkd.li/i/15858008',
          ],
        },
      ],
    },
  ],
}
```

**Comment by declandragon** [comment]
尝试了十多次，感觉没问题了。表现是等跳过按钮出现后，过一秒左右自动跳过。谢谢。

**Comment by AIsouler** [comment]
我这边测试是能跳过的，你可以尝试更新一下该软件

**Comment by declandragon** [comment]
我更新一下试试

**Comment by AIsouler** [comment]
> 我更新一下试试

把刚才导入的那条规则先关闭再测试

**Comment by declandragon** [comment]
> > 我更新一下试试
> 
> 把刚才导入的那条规则先关闭再测试

好的嘞

**Comment by declandragon** [comment]
更新之后表现好多了，都是秒跳过，谢谢
以前 用 李跳跳养成了不更新 app 的习惯，版本都比较旧
