### ISSUE TITLE
麦当劳获取设备信息弹窗

### ISSUE THREAD

**Issue by hpliu01** [AIsouler/GKD_subscription#254]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 我确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 我确保已阅读[#120](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue
- [X] 我确保提供正确的快照, 否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

需要点击不允许，快照如下：

https://i.gkd.li/snapshot/1718941421078

**Comment by adproqwq** [comment]
> [i.gkd.li/snapshot/1718941421078](https://i.gkd.li/snapshot/1718941421078)

快照链接是错的，这个快照链接只有你自己能打开。正确的快照链接应该是以https://i.gkd.li/import/开头

**Comment by hpliu01** [comment]
[snapshot-1718941421078.zip](https://github.com/user-attachments/files/15944139/snapshot-1718941421078.zip)


> > [i.gkd.li/snapshot/1718941421078](https://i.gkd.li/snapshot/1718941421078)
> 
> 快照链接是错的，这个快照链接只有你自己能打开。正确的快照链接应该是以[https://i.gkd.li/import/开头](https://i.gkd.li/import/%E5%BC%80%E5%A4%B4)

**Comment by adproqwq** [comment]
> [snapshot-1718941421078.zip](https://github.com/user-attachments/files/15944139/snapshot-1718941421078.zip)

无activityId

**Comment by hpliu01** [comment]
> > [snapshot-1718941421078.zip](https://github.com/user-attachments/files/15944139/snapshot-1718941421078.zip)
> 
> 无activityId

那就是无法跳过还是我的快照不对？

**Comment by adproqwq** [comment]
> 那就是无法跳过还是我的快照不对？

你的快照问题，你开shizuku再打一个

**Comment by hpliu01** [comment]
> > 那就是无法跳过还是我的快照不对？
> 
> 你的快照问题，你开shizuku再打一个

[Uploading snapshot-1719142267327.zip…]()

**Comment by hpliu01** [comment]
> > 那就是无法跳过还是我的快照不对？
> 
> 你的快照问题，你开shizuku再打一个

[snapshot-1719142267327.zip](https://github.com/user-attachments/files/15944339/snapshot-1719142267327.zip)

**Comment by adproqwq** [comment]
> [snapshot-1719142267327.zip](https://github.com/user-attachments/files/15944339/snapshot-1719142267327.zip)

点【不允许】还是点【好】
