### ISSUE TITLE
烦请适配，工程相机部分开屏广告不能跳过

### ISSUE THREAD

**Issue by kongxl2020** [AIsouler/GKD_subscription#263]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 我确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 我确保已阅读[#120](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue
- [X] 我确保提供正确的快照, 否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

部分广告不能跳过，尝试自己编写规则失败，烦请适配造福机油，感谢敬礼！
https://i.gkd.li/i/15963258
https://i.gkd.li/i/15963550
https://i.gkd.li/i/16009667
https://i.gkd.li/i/16030413

**Comment by AIsouler** [comment]
73f005b19b75dd971525036d6b06e164f2596fd6

**Comment by kongxl2020** [comment]
感谢
