### ISSUE TITLE
小米视频

### ISSUE THREAD

**Issue by Z-fly** [AIsouler/GKD_subscription#264]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 我确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 我确保已阅读[#120](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue
- [X] 我确保提供正确的快照, 否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

![1719749762286](https://github.com/AIsouler/GKD_subscription/assets/10470892/0f35842d-31e6-4bc9-8899-d853e5b51d2c)
https://i.gkd.li/i/16044569
![08bdc778ec7db3760c5cd9a233cc6e0d](https://github.com/AIsouler/GKD_subscription/assets/10470892/43cf6915-2522-4619-b357-7f724a83bc3e)
https://i.gkd.li/i/16044602
https://i.gkd.li/i/16044603

**Comment by Z-fly** [comment]
页面有两个广告，广告点两次才能关闭。

**Comment by AIsouler** [comment]
导入试试
```
{
  id: 'com.miui.video',
  name: '小米视频',
  groups: [
    {
      key: 1,
      name: '局部广告',
      rules: [
        {
          quickFind: true,
          activityIds: 'com.miui.video.feature.detail.NewShortVideoDetailActivity',
          matches: '[vid="v_banner_bottom_right"]',
          exampleUrls: 'https://m.gkd.li/57941037/c672bf16-78a1-4d1e-8419-c59b37a85ce0',
          snapshotUrls: 'https://i.gkd.li/i/16044569',
        },
      ],
    },
  ],
}
```

**Comment by AIsouler** [comment]
第二段是属于另一个软件叫智能服务，你看看智能服务这个软件的规则开启了没有

**Comment by AIsouler** [comment]
你也可以直接冻结智能服务这个软件，小米系统应用的部分广告就是这个软件提供的

**Comment by Z-fly** [comment]
> 第二段是属于另一个软件叫智能服务，你看看智能服务这个软件的规则开启了没有
这个可以了

但是这里应该没有生效
![QQ_1719838498083](https://github.com/AIsouler/GKD_subscription/assets/10470892/5b8c56e2-7d4f-4ef2-88ce-de7e46c24cba)

**Comment by AIsouler** [comment]
> 但是这里应该没有生效 ![QQ_1719838498083](https://private-user-images.githubusercontent.com/10470892/344681238-5b8c56e2-7d4f-4ef2-88ce-de7e46c24cba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4Mzg5MjIsIm5iZiI6MTcxOTgzODYyMiwicGF0aCI6Ii8xMDQ3MDg5Mi8zNDQ2ODEyMzgtNWI4YzU2ZTItN2Q0Zi00ZWYyLTg4Y2UtZGU3ZTQ2YzI0Y2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEyNTcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMjEwMTFkMjZjMjBiYzE1Y2Q5MWMyMzgyOTRlYzE3NjQ0YWE4MDM0MjA2NzMyYjc1MGFjMjY4Njc5ZGM4NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.heC_sisvI8KJm7hSsOTVmZMfCBbxMCfVFguC9zhoVoQ)

点这个能关吗

**Comment by Z-fly** [comment]
我刚刚手动点击了这个，然后智能服务规则打开，第二段弹出被gkd关闭了

**Comment by AIsouler** [comment]
9fea3730ddb66c9e7d276227c5f7aa483d8680ae
29683360e27d2bbec27246d04d21dfc483fc1e6c
