### ISSUE TITLE
QQ浏览器页面卡片广告只点击广告不会点击关闭

### ISSUE THREAD

**Issue by kuxia** [AIsouler/GKD_subscription#266]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的

- [X] 我确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 我确保已阅读[#120](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue
- [X] 我确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭issue
- [X] 我确保提供 误触/不执行规则 的界面的快照, 否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/i/16062680

**Comment by kuxia** [comment]
修改部分规则后可以了
{
  id: 'com.tencent.mtt',
  name: 'QQ浏览器',
  groups: [
    {
      key: 0,
      name: '开屏广告',
      activityIds: 'com.tencent.mtt.MainActivity',
      rules: [
        '@View[id=null] + ImageView + FrameLayout TextView[text=`向上滑动或点击查看`]',
        {
          matches: '@LinearLayout[clickable=true] > TextView[text="跳过"]',
          snapshotUrls: ['https://gkd-kit.gitee.io/import/12472630'],
        },
      ],
    },
    {
      key: 10,
      name: '小说阅读页面-卡片广告',
      activityIds: 'com.tencent.mtt.MainActivity',
      cd: 3000,  //加入规则冷却
      rules: [
        {
          key: 0,
          matches: '@ViewGroup[visibleToUser=true] > ViewGroup > [desc="广告"]',
          snapshotUrls: [
            'https://gkd-kit.gitee.io/import/12907446',
            'https://gkd-kit.gitee.io/import/12907445', // 限定 visibleToUser=true，防止在节点不可见时触发规则
          ],
        },
        {
          preKeys: 0,
          key: 1,
          matches: '@ViewGroup > [desc="关闭此广告"]',
          snapshotUrls: [
            'https://gkd-kit.gitee.io/import/12907654',
            'https://gkd-kit.gitee.io/import/12907651',
          ],
        },
        {
          preKeys: 1,
          key: 2,
          matches: '@ViewGroup > [desc="不感兴趣"]',
          snapshotUrls: [
            'https://gkd-kit.gitee.io/import/12907655',
            'https://gkd-kit.gitee.io/import/12907653',
          ],
        },
 {
          preKeys: 1,
          key: 2,
          matches: '@ViewGroup > [desc="直接关闭"]',
          snapshotUrls: [
            'https://gkd-kit.gitee.io/import/12907655',
            'https://gkd-kit.gitee.io/import/12907653',
          ],
        },
      ],
    },
    {
      key: 11,
      name: '小说阅读页面-视频广告',
      activityIds: 'com.qq.e.tg.RewardvideoPortraitADActivity',
      rules: [
        {
          key: 0,
          matches: '[text="腾讯广告"] >n [id^="button_close"]',
          snapshotUrls: 'https://gkd-kit.gitee.io/import/12909822',
        },
        {
          preKeys: 0,
          key: 1,
          matches: '[id="com.tencent.mtt:id/reward_dialog_close"]',
          snapshotUrls: 'https://gkd-kit.gitee.io/import/12908955',
        },
      ],
    },
  ],
}

**Comment by AIsouler** [comment]
快照无activityid

**Comment by kuxia** [comment]
com.tencent.mtt.MainActivity
![1719904388458_temp](https://github.com/AIsouler/GKD_subscription/assets/63484692/7a606eb0-ee16-4388-920a-c371d0e20dcd)

**Comment by AIsouler** [comment]
你那个快照里没有activityid，重新截一个

**Comment by AIsouler** [comment]
00746287bd0e0bfd249e4112960caa7622c65a88
