### ISSUE TITLE
[天翼云盘] 首页弹窗广告误触

### ISSUE THREAD

**Issue by tangwenlongNO1** [AIsouler/GKD_subscription#267]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的

- [X] 我确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 我确保已阅读[#120](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue
- [X] 我确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭issue
- [X] 我确保提供 误触/不执行规则 的界面的快照, 否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

![Screenshot_2024-07-02-17-55-50-97_befd3b55c427022](https://github.com/AIsouler/GKD_subscription/assets/106858241/09135d6b-0443-4f8f-bda1-48e47069c1a5)

https://github.com/AIsouler/GKD_subscription/assets/106858241/a88970d5-ffd9-4a7a-a8ec-fc10a94c85ed

**Comment by tangwenlongNO1** [comment]
https://i.gkd.li/i/16106097
https://i.gkd.li/i/16106105

**Comment by AIsouler** [comment]
09471bab9d3f974070d3d942a7c9a7de74b2635e

**Comment by tangwenlongNO1** [comment]
又出现误触https://i.gkd.li/i/16647898

**Comment by AIsouler** [comment]
能截一个这个弹窗广告的快照吗，我优化一下

![image](https://github.com/user-attachments/assets/f98d9dca-17e9-4bbf-86fd-7d9eb959a836)

**Comment by AIsouler** [comment]
828571457ba12489fd6c286052496ee85ab404fd
