### ISSUE TITLE
RQrun 每日签到

### ISSUE THREAD

**Issue by 1celife** [AIsouler/GKD_subscription#269]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 我确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 我确保已阅读[#120](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue
- [X] 我确保提供正确的快照, 否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

每日签到，点击右侧中间  签到福利
https://i.gkd.li/i/16105502

**Comment by AIsouler** [comment]
签到后的快照也发一下

**Comment by 1celife** [comment]
> 签到后的快照也发一下


点进去自己就签到了，不用点别的了。返回首页，就没有签到福利按钮了。

https://i.gkd.li/i/16105938
https://i.gkd.li/i/16105942

**Comment by AIsouler** [comment]
这个页面能直接点返回关闭吗，还是先要点击```我知道了```之后才能返回？

**Comment by 1celife** [comment]
> 这个页面能直接点返回关闭吗，还是先要点击```我知道了```之后才能返回？
> ![image](https://github.com/AIsouler/GKD_subscription/assets/57941037/2e32dad7-cce9-4dfd-a134-e4ec71b691c7)
> 

不能直接返回，要先点击我知道了。

**Comment by AIsouler** [comment]
827cd7cfdb858b400d90d0fec4e93de2b55fc8dc
