### ISSUE TITLE
请求适配点心云开屏广告跳过

### ISSUE THREAD

**Issue by lxming95** [AIsouler/GKD_subscription#270]
### 一些验证

- [X] 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建issue
- [X] 我确认知晓并同意维护者直接关闭不符合规范的issue
- [X] 我确保已阅读[#120](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue
- [X] 我确保提供正确的快照, 否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/i/16115075

**Comment by AIsouler** [comment]
这个看起来不是跳过按钮，点这个能关闭吗？

**Comment by lxming95** [comment]
> 这个看起来不是跳过按钮，点这个能关闭吗？ ![image](https://private-user-images.githubusercontent.com/57941037/346273121-48ba8a60-fd8e-4f9e-8ba6-93e597a8266f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyODEzMDcsIm5iZiI6MTcyMDI4MTAwNywicGF0aCI6Ii81Nzk0MTAzNy8zNDYyNzMxMjEtNDhiYThhNjAtZmQ4ZS00ZjllLThiYTYtOTNlNTk3YTgyNjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDE1NTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYTk0ZWYyZDg2ZDMwNDAzMGY3MGM2NzI3M2I2YTMyNjVmN2U3YTc1MDY5OWE5NjY0MjA5YTJhMWFhNzA1MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6zzigR2NLk4R5Mlv6-IXvtJiWIaloYnPMotNPQPcxp4)

可以关闭

**Comment by AIsouler** [comment]
现有规则是有效的，开屏的时候有点击提示吗

**Comment by AIsouler** [comment]
导入这个试试
```
{
  id: 'com.dianxinai.mobile',
  name: '点心云',
  groups: [
    {
      key: 0,
      name: '开屏广告',
      quickFind: true,
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      rules: [
        {
          matches: '[text$="s"][text.length=2]',
          exampleUrls:
            'https://m.gkd.li/57941037/a4b9c558-1d1f-4964-9545-95533253c9d1',
          snapshotUrls: 'https://i.gkd.li/i/16115075',
        },
      ],
    },
  ],
}
```

**Comment by lxming95** [comment]
> 导入这个试试
> 
> ```
> {
>   id: 'com.dianxinai.mobile',
>   name: '点心云',
>   groups: [
>     {
>       key: 0,
>       name: '开屏广告',
>       quickFind: true,
>       matchTime: 10000,
>       actionMaximum: 1,
>       resetMatch: 'app',
>       rules: [
>         {
>           matches: '[text$="s"][text.length=2]',
>           exampleUrls:
>             'https://m.gkd.li/57941037/a4b9c558-1d1f-4964-9545-95533253c9d1',
>           snapshotUrls: 'https://i.gkd.li/i/16115075',
>         },
>       ],
>     },
>   ],
> }
> ```

这个导入本地后开启是有效的，感谢适配
