### ISSUE TITLE
驾考宝典app规则补充

### ISSUE THREAD

**Issue by sheng-ri** [AIsouler/GKD_subscription#274]
### 一些验证

- [X] 我确保提供 误触/不执行规则 的界面的快照, 否则我同意维护者直接关闭issue
- [X] 我确保使用的是[最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest)
- [X] 检查这个问题是否属于[本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读[#120](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

偶尔弹出的开屏广告不能自动跳过

https://i.gkd.li/i/16283385

**Comment by AIsouler** [comment]
c4814879c94cd521ae451ce60ac5496789f62d2a
