### ISSUE TITLE
头条新闻，经常自动出现“心跳过快”的搜索 ，多次调到这个搜索，直接变的不可用。

### ISSUE THREAD

**Issue by chenjingxiong** [AIsouler/GKD_subscription#275]
### 一些验证

- [X] 我确保提供 误触/不执行规则 的界面的快照, 否则我同意维护者直接关闭issue
- [X] 我确保使用的是[最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest)
- [X] 检查这个问题是否属于[本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读[#120](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

头条新闻，经常自动出现“心跳过快”的搜索 ，多次调到这个搜索，直接变的不可用。

**Comment by AIsouler** [comment]
最新版订阅已解决
