### ISSUE TITLE
请求适配移除美团外卖的直播悬浮框

### ISSUE THREAD

**Issue by BennettChina** [AIsouler/GKD_subscription#280]
### 一些验证

- [X] 我确保 **提供正确的快照**, 否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/i/16359035

**Comment by AIsouler** [comment]
这个窗口会在其他页面出现吗，如果有请发一下其他页面的快照

**Comment by BennettChina** [comment]
> 这个窗口会在其他页面出现吗，如果有请发一下其他页面的快照

应该不会，没在其他页面看到过。

**Comment by AIsouler** [comment]
d1caff2adac4bf39ad1e8ce0dd230c6c31130481
