### ISSUE TITLE
网心云无法关闭广告弹窗

### ISSUE THREAD

**Issue by bocchi810** [AIsouler/GKD_subscription#282]
### 一些验证

- [X] 我确保 **提供 误触/不执行规则 的界面的快照**, 否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [x] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/snapshot/1722414923732

**Comment by AIsouler** [comment]
这个链接我访问不了，你应该从这里分享快照链接
![image](https://github.com/user-attachments/assets/a2de8cac-5027-4791-9a24-b3167c2476a7)

**Comment by AIsouler** [comment]
c2c31964d119f8bc6bd96eaf59e590844d82743d
