### ISSUE TITLE
雷神加速器开屏广告会偶发误触（有录制视频）

### ISSUE THREAD

**Issue by DeliciousLiMiao** [AIsouler/GKD_subscription#285]
### 一些验证

- [X] 我确保 **提供 误触/不执行规则 的界面的快照**, 否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

![Screenshot_2024-08-01-14-51-50-428_li songe gkd](https://github.com/user-attachments/assets/fbf5751e-9d67-4605-8f0b-859bfcd96386)
[雷神加速器_WelcomeActivity-1722495338097.zip](https://github.com/user-attachments/files/16451493/_WelcomeActivity-1722495338097.zip)

https://github.com/user-attachments/assets/cb001c95-9b03-4592-ba9f-b76077ee0e0b

如题，已经关闭加速传感器权限，不是因为晃动跳转

**Comment by AIsouler** [comment]
导入试试
```
{
  id: 'com.nn.accelerator.box',
  name: '雷神加速器',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      rules: [
        {
          fastQuery: true,
          matches: '[vid="tobid_splash_sound_and_skip_layout"]',
          exampleUrls: 'https://e.gkd.li/03b70de9-9e1d-4362-83df-08a95c2c224f',
          snapshotUrls: 'https://i.gkd.li/i/16451775',
        },
      ],
    },
  ],
}
```

**Comment by DeliciousLiMiao** [comment]
导入后无误触发了，感谢适配Thanks♪(･ω･)ﾉ
