### ISSUE TITLE
央视频的开屏广告无法跳过

### ISSUE THREAD

**Issue by Unbengabled** [AIsouler/GKD_subscription#286]
### 一些验证

- [X] 我确保 **提供 误触/不执行规则 的界面的快照**, 否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

![Screenshot_20240803_184915_li songe gkd](https://github.com/user-attachments/assets/67fe05ef-0dae-4b90-9d4f-7ccb6f92f369)
![snapshot-1722681929220](https://github.com/user-attachments/assets/4270ef33-7c46-4e32-8b20-0609a53a11b5)
[snapshot-1722681929220.zip](https://github.com/user-attachments/files/16479211/snapshot-1722681929220.zip)

**Comment by AIsouler** [comment]
41ac5a1b8651cc9e9e5baa0be3eced41de2c0f9b
