### ISSUE TITLE
彩虹多多

### ISSUE THREAD

**Issue by ssh1171266849** [AIsouler/GKD_subscription#288]
### 一些验证

- [X] 我确保 **提供正确的快照**, 否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/i/16491923

**Comment by AIsouler** [comment]
全局规则不能跳吗？

**Comment by AIsouler** [comment]
导入这个试试
```
{
  id: 'com.ddyc.lotterytool',
  name: '彩虹多多',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      fastQuery: true,
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      rules: [
        {
          matches: '[vid="tobid_splash_skip_ll"]',
          exampleUrls: 'https://e.gkd.li/dc1fead1-9ebc-4102-b78d-47a4fe76af8b',
          snapshotUrls: 'https://i.gkd.li/i/16491923',
        },
      ],
    },
  ],
}
```

**Comment by ssh1171266849** [comment]
我发现 这个应用的跳过 按钮回变大变小 左右位置都会随机变 老是点到广告 
我用那个规则试一下
