### ISSUE TITLE
百度输入法定制版（华为系统自带）的两种开屏广告

### ISSUE THREAD

**Issue by Unbengabled** [AIsouler/GKD_subscription#293]
### 一些验证

- [X] 我确保 **提供正确的快照**, 否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

华为系统自带的，包名和百度输入法普通版不一样，在gkd里默认隐藏，打开也只有全局规则
**问题是这玩意的开屏广告有好几种，并且随机出现，全局规则只能跳过一种圆形按钮的广告，下面这两种就不行**
[snapshot-1722796875623.zip](https://github.com/user-attachments/files/16493555/snapshot-1722796875623.zip)
[snapshot-1722797601139.zip](https://github.com/user-attachments/files/16493557/snapshot-1722797601139.zip)

**Comment by AIsouler** [comment]
截一下圆形按钮广告的快照，可以先关闭全局规则再截

**Comment by Unbengabled** [comment]
> 截一下圆形按钮广告的快照，可以先关闭全局规则再截

见鬼，现在又直接没有广告了

**Comment by AIsouler** [comment]
遇到了就截一下吧，不急

**Comment by AIsouler** [comment]
88752465e20a85f4610662c5a30210d505dcf808
