### ISSUE TITLE
华为运动健康 实时推送步数弹窗失效了

### ISSUE THREAD

**Issue by pheotry** [AIsouler/GKD_subscription#296]
### 一些验证

- [X] 我确保 **提供 误触/不执行规则 的界面的快照**, 否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/i/16494762

[华为运动健康_MainActivity-1722855272154.zip](https://github.com/user-attachments/files/16494758/_MainActivity-1722855272154.zip)

**Comment by AIsouler** [comment]
356c805afd0bd5012046ed56cf75032126a87db1

**Comment by AIsouler** [comment]
这两个发一个就行，推荐发链接

![image](https://github.com/user-attachments/assets/493c4fef-a73b-475f-98c0-ede7d7b2b865)

**Comment by pheotry** [comment]
> 这两个发其中一个就行，推荐发链接
> 
> ![image](https://private-user-images.githubusercontent.com/57941037/355082064-493c4fef-a73b-475f-98c0-ede7d7b2b865.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTcwMDEsIm5iZiI6MTcyMjg1NjcwMSwicGF0aCI6Ii81Nzk0MTAzNy8zNTUwODIwNjQtNDkzYzRmZWYtYTczYi00NzVmLTk4YzAtZWRlN2Q3YjJiODY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDExMTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYzNkYWViYjdkNmQ3Y2VlZDk5ODEyMmEwZmYwODhmNDRhZjU1ZWQyOGY5ZjA4ZmJkODY0MWY3ZmU1ZjY3NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5rc5mRY1s2x6zpVLdhwuAUBhMrZQ_SOmcHVuFhBfM4A)

好的
