### ISSUE TITLE
uc浏览器请大佬看看怎么回事

### ISSUE THREAD

**Issue by YnSen** [AIsouler/GKD_subscription#297]
### 一些验证

- [X] 我确保 **提供正确的快照**, 否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/snapshot/1722855931137
这个用最新GKD快照的但是，上面全是ImageView，没有获取到任何TextView信息，请大佬适配一下，谢谢

**Comment by AIsouler** [comment]
这种情况说明该应用没有提供完整的页面节点信息，需使用坐标点击

**Comment by AIsouler** [comment]
2ee96457f5f1526619d14bc91f49d3a8a8bb00bf
