### ISSUE TITLE
KMB.LWB(香港巴士到站软件）

### ISSUE THREAD

**Issue by zxpp01** [AIsouler/GKD_subscription#306]
### 一些验证

- [X] 我确保 **提供正确的快照**, 否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

请帮忙适配KMB.LWB(香港巴士到站软件）这软件，开屏有，里面也有，广告太多了，感谢付出。一直都只用这个订阅，很好用。非常感谢

感谢你的回复，因为是第一次注册github，所以，在google找不到ActivityID，找了一大圈，才发现，在issue里，有详细的操作说明。我真笨，感谢。我认真地看了上面的要求，希望我提供了完整的快照信息，尽量不浪费你的时间。

祝   一切顺利！

快照连接如下：
https://i.gkd.li/i/16608661
https://i.gkd.li/i/16608669
https://i.gkd.li/i/16608672
https://i.gkd.li/i/16608677
https://i.gkd.li/i/16608680
https://i.gkd.li/i/16608683
https://i.gkd.li/i/16608692
https://i.gkd.li/i/16608695
https://i.gkd.li/i/16609018
https://i.gkd.li/i/16609019

**Comment by AIsouler** [comment]
你的快照里没有截图，请授予gkd截图权限后再重新截取快照

**Comment by zxpp01** [comment]
morning,我打开截图，重新生成了帮忙再看一下.

https://i.gkd.li/i/16620110
​https://i.gkd.li/i/16620112
​https://i.gkd.li/i/16620113
​https://i.gkd.li/i/16620115
​https://i.gkd.li/i/16620119
​https://i.gkd.li/i/16620121
​https://i.gkd.li/i/16620122
​https://i.gkd.li/i/16620123

**Comment by AIsouler** [comment]
这些是点击关闭后出现的吗

![image](https://github.com/user-attachments/assets/03df4f70-42fa-4c44-a068-9ba6aa3532a8)
![image](https://github.com/user-attachments/assets/c8c2d1bb-accb-4918-8403-fa1cfcdacac5)

**Comment by zxpp01** [comment]
> 这些是点击关闭后出现的吗，这两个页面适配不了
> 
> ![image](https://private-user-images.githubusercontent.com/57941037/358058142-03df4f70-42fa-4c44-a068-9ba6aa3532a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODU1MTYsIm5iZiI6MTcyMzY4NTIxNiwicGF0aCI6Ii81Nzk0MTAzNy8zNTgwNTgxNDItMDNkZjRmNzAtNDJmYS00YzQ0LWEwNjgtOWJhNmFhMzUzMmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAxMjY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNWFhNGViMzMzNmEwNDJmOTYwMmJlMjU0NzQyODFiN2NiYzBhYTA3Y2M5NDc1OWE4ZmI5OTY1MjllZTkzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7y76KtxSlpG5BtMCGwSJhXb16Ahq8Y9OAF0emE0pM8I) ![image](https://private-user-images.githubusercontent.com/57941037/358058176-c8c2d1bb-accb-4918-8403-fa1cfcdacac5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODU1MTYsIm5iZiI6MTcyMzY4NTIxNiwicGF0aCI6Ii81Nzk0MTAzNy8zNTgwNTgxNzYtYzhjMmQxYmItYWNjYi00OTE4LTg0MDMtZmExY2ZjZGFjYWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAxMjY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwM2U5YmMyMDE4N2Y1MDMwODRkYTA3NDQ0YWIwZjMyOTkxMzBjNjk1MTJkYThlOGQ4OTExYTU0N2I0NjJlNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.43AAaOHm5klxc25BbXQ64XWmO1VfIP1MVeme2q7hipI)

这个是google的广告，点击关闭后会陆续弹出这两个框。最后这个框是保留在那里，但没有显示广告.

只要把首页的广告去了就可以了,因为首页的广告，他那个叉叉会等几秒才显示出来，有时候要点击关闭的那个字.

祝你一切顺利

**Comment by AIsouler** [comment]
复制后导入本地订阅试试
```
{
  id: 'com.kmb.app1933',
  name: 'KMB . LWB',
  groups: [
    {
      key: 1,
      name: '局部广告',
      rules: [
        {
          fastQuery: true,
          activityIds: ['com.mobilesoft.mybus.KMBMainView','com.mobilesoft.mybus.KMBRouteDetailView',],
          matches: 'WebView >2 View[childCount=2] > @Button[clickable=true] <<n [vid="adView"]',
          exampleUrls: 'https://e.gkd.li/982f7f10-7bdb-42f2-801b-37d2f3264610',
          snapshotUrls: 'https://i.gkd.li/i/16620110',
        },
      ],
    },
  ],
}
```

**Comment by zxpp01** [comment]
打开了，但是没有帮我关闭。那这个关闭的叉叉有时在左边，现在又在右边。
![Screenshot_2024-08-15-09-54-42-657_li songe gkd](https://github.com/user-attachments/assets/e3931635-02cb-4099-9985-0bcb01593a48)
![Screenshot_2024-08-15-09-54-28-466_com kmb app1933](https://github.com/user-attachments/assets/4b2249d4-dcb9-4f18-9266-80b175d07350)
上传截图，它变成上面这个链接的样子，你可以看到吗？

**Comment by AIsouler** [comment]
发快照

**Comment by zxpp01** [comment]
https://i.gkd.li/i/16620586

**Comment by AIsouler** [comment]
> https://i.gkd.li/i/16620586

这个是开屏广告还是点击其他关闭按钮后出现的

**Comment by zxpp01** [comment]
> > https://i.gkd.li/i/16620586
> 
> 这个是开屏广告还是点击其他关闭按钮后出现的

开屏广告

**Comment by AIsouler** [comment]
导入试试，如果发现有跳不过的就发快照
```
{
  id: 'com.kmb.app1933',
  name: 'KMB . LWB',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      actionMaximumKey: 0,
      rules: [
        {
          key: 0,
          activityIds: 'com.google.android.gms.ads.AdActivity',
          matches: '[desc="打开"] - View > [text="关闭"]',
          exampleUrls: 'https://e.gkd.li/14158b1c-88f3-4e5c-bbc1-193186e77b07',
          snapshotUrls: 'https://i.gkd.li/i/16620123',
        },
        {
          key: 1,
          activityIds: 'com.google.android.gms.ads.AdActivity',
          matches: '[desc="Interstitial close button"]',
          exampleUrls: 'https://e.gkd.li/3b5d7bcd-4629-44af-8ee9-5c8a1001ebad',
          snapshotUrls: 'https://i.gkd.li/i/16620586',
        }
      ],
    },
  ],
}
```

**Comment by zxpp01** [comment]
> 导入试试，如果发现有跳不过的就发快照
> 
> ```
> {
>   id: 'com.kmb.app1933',
>   name: 'KMB . LWB',
>   groups: [
>     {
>       key: 1,
>       name: '开屏广告',
>       matchTime: 10000,
>       actionMaximum: 1,
>       resetMatch: 'app',
>       actionMaximumKey: 0,
>       rules: [
>         {
>           key: 0,
>           activityIds: 'com.google.android.gms.ads.AdActivity',
>           matches: '[desc="打开"] - View > [text="关闭"]',
>           exampleUrls: 'https://e.gkd.li/14158b1c-88f3-4e5c-bbc1-193186e77b07',
>           snapshotUrls: 'https://i.gkd.li/i/16620123',
>         },
>         {
>           key: 1,
>           activityIds: 'com.google.android.gms.ads.AdActivity',
>           matches: '[desc="Interstitial close button"]',
>           exampleUrls: 'https://e.gkd.li/3b5d7bcd-4629-44af-8ee9-5c8a1001ebad',
>           snapshotUrls: 'https://i.gkd.li/i/16620586',
>         }
>       ],
>     },
>   ],
> }
> ```

可以跳过这个开屏页面了，谢谢

**Comment by AIsouler** [comment]
这个也是开屏广告吗

![image](https://github.com/user-attachments/assets/05bfdb66-d42e-47f5-a6ea-9b9206bb9bdf)

**Comment by zxpp01** [comment]
是的，开屏广告。（在上班，有时回复不及时，抱歉）

**Comment by AIsouler** [comment]
已适配 b25e628c6b8824bf9a3ac1aeb0a16637b34ec24f
软件内的底部横幅广告我没有适配，因为点击关闭后出现的内容适配不了

**Comment by zxpp01** [comment]
> 已适配 [b25e628](https://github.com/AIsouler/GKD_subscription/commit/b25e628c6b8824bf9a3ac1aeb0a16637b34ec24f) 软件内的底部横幅广告我没有适配，因为点击关闭后出现的内容适配不了

好的，感谢，祝你一切顺利

**Comment by zxpp01** [comment]
刚刚打开出现新的开屏页，关闭不了。
https://i.gkd.li/i/16621030

他这个开屏页的关闭按钮，有时候在左上角，有时候右上角，还有些时候就是在最下面显示关闭两个字

**Comment by AIsouler** [comment]
b134c21020c5de91930b05096c3b017d7015a306

**Comment by zxpp01** [comment]
![Screenshot_2024-08-15-11-19-13-520_li songe gkd](https://github.com/user-attachments/assets/a278879a-978e-41e8-aa45-7010916de945)


这个的code,b134c21.

复制到规则里，它提示如上图.请问要怎么加进最新的？

**Comment by AIsouler** [comment]
```
{
  id: 'com.kmb.app1933',
  name: 'KMB . LWB',
  groups: [
    {
      key: 0,
      name: '开屏广告',
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      actionMaximumKey: 0,
      rules: [
        {
          key: 0,
          activityIds: 'com.google.android.gms.ads.AdActivity',
          matches: '[desc="Interstitial close button"]',
          exampleUrls: 'https://e.gkd.li/3b5d7bcd-4629-44af-8ee9-5c8a1001ebad',
          snapshotUrls: 'https://i.gkd.li/i/16620586',
        },
        {
          key: 1,
          activityIds: 'com.google.android.gms.ads.AdActivity',
          matches: '[desc="打开"] - View > [text="关闭"]',
          exampleUrls: 'https://e.gkd.li/14158b1c-88f3-4e5c-bbc1-193186e77b07',
          snapshotUrls: 'https://i.gkd.li/i/16620123',
        },
        {
          key: 2,
          activityIds: 'com.google.android.gms.ads.AdActivity',
          matches:
            'WebView >2 View[childCount=3] >2 View[childCount=2] > View[childCount=2] > View[childCount=1] > Button[clickable=true]',
          exampleUrls: 'https://e.gkd.li/0be64275-23d1-4b13-b444-6e0c67fdd8fc',
          snapshotUrls: 'https://i.gkd.li/i/16621030',
        },
      ],
    },
  ],
}
```

**Comment by zxpp01** [comment]
> 删掉之前的重新导入这个
> 
> ```
> {
>   id: 'com.kmb.app1933',
>   name: 'KMB . LWB',
>   groups: [
>     {
>       key: 0,
>       name: '开屏广告',
>       matchTime: 10000,
>       actionMaximum: 1,
>       resetMatch: 'app',
>       actionMaximumKey: 0,
>       rules: [
>         {
>           key: 0,
>           activityIds: 'com.google.android.gms.ads.AdActivity',
>           matches: '[desc="Interstitial close button"]',
>           exampleUrls: 'https://e.gkd.li/3b5d7bcd-4629-44af-8ee9-5c8a1001ebad',
>           snapshotUrls: 'https://i.gkd.li/i/16620586',
>         },
>         {
>           key: 1,
>           activityIds: 'com.google.android.gms.ads.AdActivity',
>           matches: '[desc="打开"] - View > [text="关闭"]',
>           exampleUrls: 'https://e.gkd.li/14158b1c-88f3-4e5c-bbc1-193186e77b07',
>           snapshotUrls: 'https://i.gkd.li/i/16620123',
>         },
>         {
>           key: 2,
>           activityIds: 'com.google.android.gms.ads.AdActivity',
>           matches:
>             'WebView >2 View[childCount=3] >2 View[childCount=2] > View[childCount=2] > View[childCount=1] > Button[clickable=true]',
>           exampleUrls: 'https://e.gkd.li/0be64275-23d1-4b13-b444-6e0c67fdd8fc',
>           snapshotUrls: 'https://i.gkd.li/i/16621030',
>         },
>       ],
>     },
>   ],
> }
> ```

可以了，谢谢
