### ISSUE TITLE
微信小程序的广告不能消除

### ISSUE THREAD

**Issue by zhl111** [AIsouler/GKD_subscription#307]
### 一些验证

- [X] 我确保 **提供 误触/不执行规则 的界面的快照**, 否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/i/16634101
我刚看到说微信app有三条内置禁用，这是与第三方订阅有关吗？
https://f.gkd.li/16633703
![SmartSelect_20240816_142421_WeChat](https://github.com/user-attachments/assets/9bca63d8-f84a-4766-8693-6730422f9c00)

**Comment by AIsouler** [comment]
微信禁用了3条全局规则

**Comment by AIsouler** [comment]
抱歉是我误会了你，微信小程序开屏广告长这样，你那个属于小程序内部的弹窗广告，小程序一类的节点众多且又高度相似，且不能使用快速查询，点击速度很慢，误触概率高，所以不予适配
![image](https://github.com/user-attachments/assets/ad480f16-114a-4391-9131-e46296adf65b)
