### ISSUE TITLE
Ehviewer误触

### ISSUE THREAD

**Issue by ngo5** [AIsouler/GKD_subscription#308]
### 一些验证

- [X] 我确保 **提供 误触/不执行规则 的界面的快照**, 否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

Ehviewer是没有广告，GKD会把Ehviewer登录界面跳过直接进入软件。

https://github.com/xiaojieonly/Ehviewer_CN_SXJ/releases

gkd v1.8.0-beta.12：
![Screenshot_2024-08-17-13-16-21-618_li songe gkd-edit](https://github.com/user-attachments/assets/805adaf1-1188-423f-b234-7d791688175e)

gkd最新正式版：
![Screenshot_2024-08-17-12-37-34-930_li songe gkd-edit](https://github.com/user-attachments/assets/670f0a99-e295-4124-bd9c-aad02b7fa450)

**Comment by AIsouler** [comment]
69f22e4bfa3205b6bf352deddfcd5668b91d398e

**Comment by ngo5** [comment]
更新了订阅，还是会跳过登录界面。
![Screenshot_2024-08-17-14-11-52-312_li songe gkd-edit](https://github.com/user-attachments/assets/af47ba24-44d8-455e-8236-b88ba16dd3f2)
![Screenshot_2024-08-17-14-12-02-426_li songe gkd-edit](https://github.com/user-attachments/assets/f824ba8c-865f-47e1-bcfb-0f52513b8a0a)

**Comment by AIsouler** [comment]
最近的一次更新是在5天前 https://github.com/AIsouler/GKD_subscription/releases/latest

**Comment by ngo5** [comment]
> 最近的一次更新是在5天前 https://github.com/AIsouler/GKD_subscription/releases/latest

好的，我还以为立马会生效，谢谢。
