### ISSUE TITLE
懂球帝数据页现在不放广告了，所以规则里面的数据页这一项是否需要移除

### ISSUE THREAD

**Issue by ccav14** [AIsouler/GKD_subscription#32]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

懂球帝数据页现在不放广告了，所以规则里面的数据页这一项是否需要移除

**Comment by AIsouler** [comment]
不移除，无法确定所有用户的数据页都没有广告，软件的不同版本广告展示可能也不一样
