### ISSUE TITLE
米游社各版区打卡及绝区零版区签到规则

### ISSUE THREAD

**Issue by Lucas04-nhr** [AIsouler/GKD_subscription#321]
### 一些验证

- [X] 我确保 **提供正确的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接，也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

米游社-绝区零签到以及各个版区打卡
- **绝区零**签到：[链接](https://i.gkd.li/i/16765537)
- **绝区零**版区打卡：[链接](https://i.gkd.li/i/16765557)
- **星穹铁道**版区打卡：[链接](https://i.gkd.li/i/16765559)
- **原神**版区打卡：[链接](https://i.gkd.li/i/16765561)

**Comment by Lucas04-nhr** [comment]
原先的规则似乎已不再起作用

**Comment by AIsouler** [comment]
你发的是已打卡的快照，需要未打卡的快照

**Comment by Lucas04-nhr** [comment]
抱歉弄错了，这是没打过卡的快照
https://i.gkd.li/i/16797750
https://i.gkd.li/i/16797768
https://i.gkd.li/i/16797770

**Comment by AIsouler** [comment]
无法适配
