### ISSUE TITLE
Instagram 的自动点击查看翻译规则会导致打开“新帖子”

### ISSUE THREAD

**Issue by DustinWin** [AIsouler/GKD_subscription#323]
### 一些验证

- [X] 我确保 **提供 误触/不执行规则 的界面的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照，BUG描述及其复现步骤(视频/截图)或者生成的快照链接，也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

快照地址：https://i.gkd.li/i/14784095
复现步骤：
1. 将 Instagram 规则中的“功能类-自动点击[查看翻译]” 打开
2. 进入 Instagram APP ，在首页**慢慢滑动**页面
3. 当刷到带有“查看翻译”的帖子时就会触发这个规则
![Screenshot_2024-08-28-12-21-25-324_com instagram android-edit](https://github.com/user-attachments/assets/ba79f670-2f1a-4964-a9b1-83cfd381df09)

预期结果：  
仅翻译帖子，不打开“新帖子”页面  
实际结果：  
翻译了帖子且打开了“新帖子”页面
![Screenshot_2024-08-28-12-21-55-073_com instagram android-edit](https://github.com/user-attachments/assets/3ce0f51b-2cbf-45b4-a069-d9fe65765628)

**Comment by DustinWin** [comment]
还有一个问题，也是该规则和快照，在 Instagram 首页刷到带有“查看翻译”的帖子时，不等这个规则触发，马上向左滑动页面进入“消息”页面，这个规则仍然会被触发，然后自动打开与某个 UP 主的聊天页面。

**Comment by AIsouler** [comment]
你在首页手动点击查看翻译会进入帖子吗？

**Comment by DustinWin** [comment]
> 你在首页手动点击查看翻译会进入帖子吗？

不会，我将复现步骤中的“慢慢滑动”加粗是因为：  
慢慢滑动时，下方的“查看翻译”按钮还没有上来让你看到，就可以轻松复现问题（就会触发“自动[查看翻译]”规则）。

**Comment by AIsouler** [comment]
> 慢慢滑动时，下方的“查看翻译”按钮还没有上来让你看到

发一下这个时候的快照

**Comment by AIsouler** [comment]
> 快照地址：https://i.gkd.li/i/14784095

你应该重新截取出问题界面的快照，而不是拿规则里的快照发上来

**Comment by DustinWin** [comment]
> > 快照地址：https://i.gkd.li/i/14784095
> 
> 你应该重新截取出问题界面的快照，而不是拿规则里的快照发上来

不好意思！
快照地址：https://i.gkd.li/i/16776676
若使用“执行选择器”，输入 `[name="android.widget.TextView"][text$="查看翻译"]` 可以直接复现该问题

**Comment by AIsouler** [comment]
关掉规则里的导入这个试试
```
{
  id: 'com.instagram.android',
  name: 'Instagram',
  groups: [
    {
      key: 2,
      name: '功能类-自动点击[查看翻译]',
      fastQuery: true,
      activityIds: 'com.instagram.mainactivity.InstagramMainActivity',
      rules: [
        {
          key: 0,
          matches: '[text="查看翻译"][clickable=true]',
          exampleUrls:
            'https://m.gkd.li/57941037/e92702d8-8349-4718-aa4d-664bf3d2f6e5',
          snapshotUrls: 'https://i.gkd.li/i/14093211',
        },
        {
          key: 1,
          excludeMatches: '[text="查看翻译"]',
          matches: '[text$="查看翻译"][clickable=false][desc!=null][visibleToUser=true]',
          exampleUrls:
            'https://m.gkd.li/57941037/7d6da15b-1c3f-4160-a2d3-d8223bc55132',
          snapshotUrls: 'https://i.gkd.li/i/14784095',
        },
      ],
    },
  ],
}
```

**Comment by DustinWin** [comment]
> 关掉规则里的导入这个试试
> 
> ```
> {
>   id: 'com.instagram.android',
>   name: 'Instagram',
>   groups: [
>     {
>       key: 2,
>       name: '功能类-自动点击[查看翻译]',
>       fastQuery: true,
>       activityIds: 'com.instagram.mainactivity.InstagramMainActivity',
>       rules: [
>         {
>           key: 0,
>           matches: '[text="查看翻译"][clickable=true]',
>           exampleUrls:
>             'https://m.gkd.li/57941037/e92702d8-8349-4718-aa4d-664bf3d2f6e5',
>           snapshotUrls: 'https://i.gkd.li/i/14093211',
>         },
>         {
>           key: 1,
>           excludeMatches: '[text="查看翻译"]',
>           matches: '[text$="查看翻译"][clickable=false][desc!=null][visibleToUser=true]',
>           exampleUrls:
>             'https://m.gkd.li/57941037/7d6da15b-1c3f-4160-a2d3-d8223bc55132',
>           snapshotUrls: 'https://i.gkd.li/i/14784095',
>         },
>       ],
>     },
>   ],
> }
> ```

嗯，没问题了。

**Comment by AIsouler** [comment]
2fd2192ea0351650c0c1eb4be7a556454fa334da
