### ISSUE TITLE
微信公众号文章内广告点击失效

### ISSUE THREAD

**Issue by feiqingbiss** [AIsouler/GKD_subscription#327]
### 一些验证

- [X] 我确保 **提供 误触/不执行规则 的界面的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照，BUG描述及其复现步骤(视频/截图)或者生成的快照链接，也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

[微信_TmplWebViewMMUI-1724984630146.zip](https://github.com/user-attachments/files/16809430/_TmplWebViewMMUI-1724984630146.zip)
微信的文章广告下拉三角符已经消失了，只有小小的广告两个字，导致不点击或者报缓慢查询，希望修复一下，谢谢。

**Comment by feiqingbiss** [comment]
[微信_TmplWebViewMMUI-1724984830907.zip](https://github.com/user-attachments/files/16809717/_TmplWebViewMMUI-1724984830907.zip)
如果还需要更多，麻烦告诉我

**Comment by AIsouler** [comment]
对于广告节点```clickable=false```的不予适配，会导致误触
