### ISSUE TITLE
补充微博规则 软件内点赞弹窗验证

### ISSUE THREAD

**Issue by Vstory** [AIsouler/GKD_subscription#333]
### 一些验证

- [X] 我确保 **提供正确的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接，也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/i/16827119
https://i.gkd.li/i/16827853

`
{
  id: 'com.sina.weibo',
  name: '微博',
  groups: [
    {
      key: 1,
      name: '取消验证弹窗',
      //desc: '自动取消微博点赞时弹出的验证，以及微博猪手的提示窗口'
      activityIds: ['.MainTabActivity', '.geetest.GeetCheckActivityForNet'],
      rules: [
        {
          matches: '[id="android:id/content"] >n Button[text^="取消"]',
          snapshotUrls: 'https://i.gkd.li/i/16827119',
        },
        {
          matches: '[id="android:id/content"] >n Button[text^="关闭验证"]',
          snapshotUrls: [
            'https://i.gkd.li/i/16827853',
          ],
        },
      ],
    },
  ],
}
`

阅读规则编写文档摸索写好了，可是不会转换成类似这种的[提交](https://github.com/AIsouler/GKD_subscription/pull/331/commits/cbfb7f5d6fe3d6244d6d70b1a00c9a2b431d23b2)

**Comment by AIsouler** [comment]
e3241420ad8756a6674488add67e5a5c7e3b25c2

**Comment by Vstory** [comment]
谢谢大佬
