### ISSUE TITLE
[QQ] 局部广告-动态页-卡片广告

### ISSUE THREAD

**Issue by DeepChirp** [AIsouler/GKD_subscription#336]
### 一些验证

- [X] 我确保 **提供 误触/不执行规则 的界面的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照，BUG描述及其复现步骤(视频/截图)或者生成的快照链接，也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

快照：https://i.gkd.li/i/16834757
截图：https://e.gkd.li/f8fbcb8b-78c2-4fde-89a2-03d0d21af5c0
![卡片广告截图](https://e.gkd.li/f8fbcb8b-78c2-4fde-89a2-03d0d21af5c0)
关闭按钮似乎没有单独的控件，所以可能无法适配？

**Comment by AIsouler** [comment]
98230699493538193c4eb937c7db943f6a3daa08

**Comment by AIsouler** [comment]
可以使用坐标点击
