### ISSUE TITLE
求适配！华为桌面的云备份关闭提示

### ISSUE THREAD

**Issue by jerryc20** [AIsouler/GKD_subscription#344]
### 一些验证

- [X] 我确保 **提供正确的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接，也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/i/16897530 

关闭云备份

https://i.gkd.li/i/16897384

取消

非常感谢！！！

**Comment by AIsouler** [comment]
这个提示对用户来说挺重要的吧，你可以导入以下规则到本地订阅，不会合并到仓库
```
{
  id: 'com.huawei.hidisk',
  name: '云空间',
  groups: [
    {
      key: 1,
      name: '功能类-关闭云备份并取消删除云备份',
      fastQuery: true,
      activityIds: 'com.huawei.android.hicloud.ui.activity.BackupNotificationActivity',
      rules: [
        {
          key: 0,
          matches: '[text="关闭云备份，不再接收提醒"]',
          exampleUrls: 'https://e.gkd.li/b2ef9c18-2065-40cf-8036-99669634ceae',
          snapshotUrls: 'https://i.gkd.li/i/16897530',
        },
        {
          preKeys: [0],
          key: 1,
          matches: '[text="取消"]',
          exampleUrls: 'https://e.gkd.li/1ece73eb-1d36-42ef-9474-3c57c3944e9b',
          snapshotUrls: 'https://i.gkd.li/i/16897384',
        }
      ],
    },
  ],
}
```

**Comment by jerryc20** [comment]
> 这个提示对用户来说挺重要的吧，你可以导入以下规则到本地订阅，不会合并到仓库
> 
> ```
> {
>   id: 'com.huawei.hidisk',
>   name: '云空间',
>   groups: [
>     {
>       key: 1,
>       name: '功能类-关闭云备份并取消删除云备份',
>       fastQuery: true,
>       activityIds: 'com.huawei.android.hicloud.ui.activity.BackupNotificationActivity',
>       rules: [
>         {
>           key: 0,
>           matches: '[text="关闭云备份，不再接收提醒"]',
>           exampleUrls: 'https://e.gkd.li/b2ef9c18-2065-40cf-8036-99669634ceae',
>           snapshotUrls: 'https://i.gkd.li/i/16897530',
>         },
>         {
>           preKeys: [0],
>           key: 1,
>           matches: '[text="取消"]',
>           exampleUrls: 'https://e.gkd.li/1ece73eb-1d36-42ef-9474-3c57c3944e9b',
>           snapshotUrls: 'https://i.gkd.li/i/16897384',
>         }
>       ],
>     },
>   ],
> }
> ```

非常感谢，华为辣鸡，这是以前云盘活动的时候存了好些东西，后来没会员了他就老是弹窗诱导我删除，免得占用他云空间
