### ISSUE TITLE
高德地图首页的卡片广告

### ISSUE THREAD

**Issue by imaegoo** [AIsouler/GKD_subscription#345]
### 一些验证

- [X] 我确保 **提供正确的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接，也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

快照: https://i.gkd.li/i/16905114

1. "出行雷达·濮阳市窗外好景酒店榜" 右上角的×号
2. "商务内环热门商场推荐" 右上角的×号
3. 以及其他类似的卡片广告

我确定我已开启了高德地图的全部9组规则，但以上所述的卡片仍然不会自动关闭。

备注：这个卡片广告经常会在我点击 "常去地点" 时突然跳出，将 "常去地点" 挤到下方，导致我误触卡片广告，影响驾驶。

**Comment by AIsouler** [comment]
>备注：这个卡片广告经常会在我点击 "常去地点" 时突然跳出，将 "常去地点" 挤到下方，导致我误触卡片广告，影响驾驶。

需要误触界面的快照

**Comment by AIsouler** [comment]
导入到本地订阅试试
```
{
  id: 'com.autonavi.minimap',
  name: '高德地图',
  groups: [
    {
      key: 1,
      name: '局部广告',
      rules: [
        {
          fastQuery: true,
          matches: 
            'ViewGroup > ViewGroup[childCount=1] > ViewGroup[childCount=1] > ViewGroup[childCount=1] > ViewGroup[childCount=2] > @ViewGroup[childCount=1][visibleToUser=true][clickable=true][text=null][index=parent.childCount.minus(1)] > ImageView[childCount=0] <<n [vid="home_scroll_view"]',
          exampleUrls: 'https://e.gkd.li/aeba98ea-0dbe-442e-a999-45b92bc43e3b',
          snapshotUrls: 'https://i.gkd.li/i/16905114',
        },
      ],
    },
  ],
}
```

**Comment by imaegoo** [comment]
感谢，卡片被我手动关闭后短时间内不会出现，明天再测试反馈

**Comment by imaegoo** [comment]
![Screenshot_20240907_071133](https://github.com/user-attachments/assets/400972b2-2a97-4cae-90fa-f843453d37b8)

已导入本地订阅，没有效果

新的快照：https://i.gkd.li/i/16913613

**Comment by AIsouler** [comment]
这个页面太复杂了，写起来很可能误触
