### ISSUE TITLE
百度地图[功能类-通勤卡添加至桌面]与删除语音包冲突

### ISSUE THREAD

**Issue by DustinWin** [AIsouler/GKD_subscription#346]
### 一些验证

- [X] 我确保 **提供 误触/不执行规则 的界面的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照，BUG描述及其复现步骤(视频/截图)或者生成的快照链接，也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

删除语音包快照地址：  
https://i.gkd.li/i/16920986

[功能类-通勤卡添加至桌面]快照地址：  
https://i.gkd.li/i/13439258

Bug 描述：  
将百度地图中的[功能类-通勤卡添加至桌面]规则打开，在删除语音包时会自动触发此规则自动点击“取消”按钮

复现步骤：  
1. 进入 GKD 并开启百度地图中的[功能类-通勤卡添加至桌面]规则
2. 进入百度地图 -> 我的 -> 语音包 -> 我的，点击任一语音包后面的“⋮”按钮
3. 点击“删除”按钮

预期结果：  
弹出“确定要删除语音包？”提示窗，可以手动点击“取消”或“确定”按钮

实际结果：
自动触发[功能类-通勤卡添加至桌面]规则，自动点击“取消”按钮

**Comment by AIsouler** [comment]
7c319b9b3052e178e57e023fe9147e190df2f75c
