### ISSUE TITLE
车来了和同花顺

### ISSUE THREAD

**Issue by cloudpanl** [AIsouler/GKD_subscription#349]
### 一些验证

- [X] 我确保 **提供正确的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接，也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

车来了：
https://i.gkd.li/i/16956583(这个页面有两个广告)
https://i.gkd.li/i/16956570

同花顺：
https://i.gkd.li/i/16956623

**Comment by AIsouler** [comment]
38253b1e7e3430c4ff86149baf61b49d3227fa7b
同花顺无法适配

**Comment by cloudpanl** [comment]
车来了的这个页面的3个广告没有生效：https://i.gkd.li/i/16987313
![微信截图_20240913092835](https://github.com/user-attachments/assets/1df513a8-c2ef-43a0-aa76-02bc87f2f63b)

**Comment by AIsouler** [comment]
7fe54b6d7be402b2c490c62a4296b6ccab748f63
