### ISSUE TITLE
[微信] “开屏广告-微信小程序” 与 “全屏广告-小程序弹窗广告” 二者似乎不能同时发挥作用

### ISSUE THREAD

**Issue by DeepChirp** [AIsouler/GKD_subscription#350]
### 一些验证

- [ ] 我确保 **提供 误触/不执行规则 的界面的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照，BUG描述及其复现步骤(视频/截图)或者生成的快照链接，也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

该问题并非是规则无法匹配节点，因此无需快照。

有些小程序同时会有开屏广告，以及开屏广告结束后的弹窗广告。若同时启用了“开屏广告-微信小程序”与“全屏广告-小程序弹窗广告”，开屏广告能够跳过，而弹窗广告仍然存在。此时查看触发记录，发现二者均会触发，但弹窗广告触发的时间在开屏广告之前，可能因为界面遮挡等原因导致弹窗广告没有被关闭。（具体情况可见附上的视频）

个人想出的解决方法有二：
1. 去除“全屏广告-小程序弹窗广告”的`matchTime`以及`actionMaximum`，因为弹窗广告可能不止一次，并且目前的规则似乎应该不会存在误触的现象（我将我曾使用的小程序都测试了一遍，似乎不存在误触）。
2. 等待“开屏广告-微信小程序”规则执行完毕后，再执行“全屏广告-小程序弹窗广告”。不过目前似乎没有直接实现该功能的参数。`preKeys`要求前者执行完毕后再执行，但是可能会有用户没有启用该规则。使用`actionDelay`的话，似乎无法精确判断开屏广告是否已经关闭。

https://github.com/user-attachments/assets/cda07694-ea30-4d12-a29b-47a3b669d92f

**Comment by AIsouler** [comment]
>但弹窗广告触发的时间在开屏广告之前

发一下弹窗广告提前触发时的快照

**Comment by DeepChirp** [comment]
> > 但弹窗广告触发的时间在开屏广告之前
> 
> 发一下弹窗广告提前触发时的快照

https://i.gkd.li/i/16958795
<s>先前觉得没必要截取这个快照，因此就没有截取</s>

**Comment by AIsouler** [comment]
e845001ff5b0a7591aea233c8c5270bd149d7c73

**Comment by AIsouler** [comment]
导入试一下
```
{
  id: 'com.tencent.mm',
  name: '微信',
  groups: [
    {
      key: 37,
      name: '全屏广告-小程序弹窗广告',
      desc: '点击关闭',
      matchTime: 20000,
      actionMaximum: 1,
      resetMatch: 'app',
      rules: [
        {
          fastQuery: true,
          activityIds: 'com.tencent.mm.plugin.appbrand.ui.AppBrandUI',
          excludeMatches: '[text="跳过"][visibleToUser=true]', // 防止提前触发导致失效
          matches:
            '@ImageView[visibleToUser=true][childCount=0][text=null] < FrameLayout[childCount=1] < FrameLayout[childCount=1] <2 FrameLayout[childCount=2] - FrameLayout >4 [text="广告"]',
          exampleUrls: 'https://e.gkd.li/d2b12af6-c204-4da7-8553-4765ef8b8c31',
          snapshotUrls: [
            'https://i.gkd.li/i/13459614',
            'https://i.gkd.li/i/16943989',
            'https://i.gkd.li/i/16920797',
          ],
          excludeSnapshotUrls: 'https://i.gkd.li/i/16958795',
        },
      ],
    },
  ],
}
```

**Comment by DeepChirp** [comment]
可以正常触发规则，感谢。不过`matchTime`以及`actionMaximum`都是防止误触的吗？毕竟有的小程序会有多个弹窗广告。

**Comment by AIsouler** [comment]
有部分广告或弹窗是刚进入软件或刚进入某页面出现的，matchTime和actionMaximum就适用于这种情况，当然一定程度也可以减小误触概率，毕竟限制了匹配时间和次数
