### ISSUE TITLE
微信自动勾选发送原图后想取消勾选又会自动被勾上

### ISSUE THREAD

**Issue by hyue418** [AIsouler/GKD_subscription#353]
### 一些验证

- [X] 我确保 **提供 误触/不执行规则 的界面的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照，BUG描述及其复现步骤(视频/截图)或者生成的快照链接，也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

微信自动勾选发送原图后，部分图片/视频不想发送原图，点取消勾选然后又会被立刻再勾上，无法取消勾选。希望规则能改为只帮勾选一次。

**Comment by AIsouler** [comment]
关闭订阅的导入这个试试
```
{
  id: 'com.tencent.mm',
  name: '微信',
  groups: [
    {
      key: 7,
      name: '功能类-自动选中发送原图',
      desc: '图片和视频选择器-自动选中底部中间的发送原图',
      actionMaximum: 1,
      activityIds: [
        'com.tencent.mm.plugin.gallery.ui.AlbumPreviewUI',
        'com.tencent.mm.plugin.gallery.ui.ImagePreviewUI',
      ],
      rules: [
        {
          key: 1,
          fastQuery: true,
          excludeVersionNames: '8.0.15',
          matches: '@ImageButton[desc="未选中,原图,复选框"] + [text="原图"]',
          snapshotUrls: [
            'https://i.gkd.li/i/12686641', // 未选中
            'https://i.gkd.li/i/12840865', // 未选中
            'https://i.gkd.li/i/12686640', // 已选中
          ],
        },
        {
          key: 2,
          versionNames: '8.0.15',
          matches: '@[desc="未选中,原图,复选框"] + [text="原图"]',
          snapshotUrls: 'https://i.gkd.li/i/14661734',
        },
      ],
    },
  ],
}
```

**Comment by AIsouler** [comment]
9e044cc19456c625063984cb4f79ce990f4df7b6
