### ISSUE TITLE
QQ音乐版本13.9互动广告

### ISSUE THREAD

**Issue by 459902507** [AIsouler/GKD_subscription#365]
### 一些验证

- [X] 我确保 **提供正确的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接，也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/i/17056504
QQ音乐更新到新版之后，新的开屏互动广告无法跳过，QQ音乐版本号13.9

**Comment by AIsouler** [comment]
我这边测试是能正常跳过的

**Comment by AIsouler** [comment]
关掉订阅的导入下面这个到本地订阅试试
```
{
  id: 'com.tencent.qqmusic',
  name: 'QQ音乐',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      rules: [
        {
          fastQuery: true,
          action: 'clickCenter',
          matches: '[text*="跳过"][text.length<10][visibleToUser=true]',
          exampleUrls: 'https://e.gkd.li/bde5c1a5-3259-45d3-a6b8-8482f7818c6f',
          snapshotUrls: 'https://i.gkd.li/i/17056504',
        },
      ],
    },
  ],
}
```

**Comment by 459902507** [comment]
这个规则添加到本地可以跳过了，谢谢
