### ISSUE TITLE
喜马拉雅 开屏广告无法跳过 com.ximalaya.ting.android 971 9.2.90.3 com.ximalaya.ting.android.host.activity.MainActivity

### ISSUE THREAD

**Issue by ighlES** [AIsouler/GKD_subscription#366]
### 一些验证

- [X] 我确保 **提供 误触/不执行规则 的界面的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照，BUG描述及其复现步骤(视频/截图)或者生成的快照链接，也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/i/17068586
![{3A76C79A-03FE-4e2b-B4B0-771091949CD0}](https://github.com/user-attachments/assets/1efa1319-c15f-46b8-a76a-9d8c410d4505)

**Comment by AIsouler** [comment]
eea9965890403cd15d99dc8846d00b2a07e1e121

另外建议更新一下GKD
