### ISSUE TITLE
NGA玩家社区 开屏广告无法跳过

### ISSUE THREAD

**Issue by lzh12139** [AIsouler/GKD_subscription#370]
### 一些验证

- [X] 我确保 **提供正确的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接，也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/i/17082872
app版本 9.4.4

**Comment by InGramViking** [comment]
```
{
  id: 'gov.pianzong.androidnga',
  name: 'NGA玩家社区',
  groups: [
    {
      key: 1,
      name: '[ChangeMe]规则名称-2024-09-21 13:15:25',
      desc: '[ChangeMe]本规则由GKD网页端审查工具生成',
      rules: [
        {
          activityIds: 'gov.pianzong.androidnga.activity.LoadingActivity',
          matches: '[name="android.widget.TextView"][text.length=3][text="跳过 "]',
          snapshotUrls: 'https://i.gkd.li/i/17082872',
        },
      ],
    },
  ],
}
```

不知道行不行，刚开始看这个咋写，加个自定义试试

**Comment by AIsouler** [comment]
你把订阅里的关掉然后导入下面这个多打开几次软件试试，如果有跳不过的就发一下快照
```
{
  id: 'gov.pianzong.androidnga',
  name: 'NGA玩家社区',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      matchRoot: true,
      fastQuery: true,
      matchTime: 20000,
      actionMaximum: 1,
      resetMatch: 'app',
      rules: [
        {
          matches: '[vid="tv_tiaoguo" || vid="iv_tg_ad"]',
          exampleUrls: 'https://e.gkd.li/d7520bc7-588b-4654-b6aa-d2736ac200bf',
          snapshotUrls: 'https://i.gkd.li/i/17082872',
        },
      ],
    },
  ],
}
```

**Comment by lzh12139** [comment]
> 你把订阅里的关掉然后导入下面这个多打开几次软件试试，如果有跳不过的就发一下快照
> 
> ```
> {
>   id: 'gov.pianzong.androidnga',
>   name: 'NGA玩家社区',
>   groups: [
>     {
>       key: 1,
>       name: '开屏广告',
>       matchRoot: true,
>       fastQuery: true,
>       matchTime: 20000,
>       actionMaximum: 1,
>       resetMatch: 'app',
>       rules: [
>         {
>           matches: '[vid="tv_tiaoguo" || vid="iv_tg_ad"]',
>           exampleUrls: 'https://e.gkd.li/d7520bc7-588b-4654-b6aa-d2736ac200bf',
>           snapshotUrls: 'https://i.gkd.li/i/17082872',
>         },
>       ],
>     },
>   ],
> }
> ```

可以了

**Comment by AIsouler** [comment]
@lzh12139 你看看你那边会不会出现这种情况https://github.com/gkd-kit/gkd/issues/622#issuecomment-2365026541

**Comment by lzh12139** [comment]
刚刚点了十几次，没复现，我这加载的挺快的，不会卡几秒
可能跟nga版本有关，我一两年没更新了，后续使用过程中再留意这种情况吧

**Comment by wangshantao** [comment]
> 你把订阅里的关掉然后导入下面这个多打开几次软件试试，如果有跳不过的就发一下快照
> 
> ```
> {
>   id: 'gov.pianzong.androidnga',
>   name: 'NGA玩家社区',
>   groups: [
>     {
>       key: 1,
>       name: '开屏广告',
>       matchRoot: true,
>       fastQuery: true,
>       matchTime: 20000,
>       actionMaximum: 1,
>       resetMatch: 'app',
>       rules: [
>         {
>           matches: '[vid="tv_tiaoguo" || vid="iv_tg_ad"]',
>           exampleUrls: 'https://e.gkd.li/d7520bc7-588b-4654-b6aa-d2736ac200bf',
>           snapshotUrls: 'https://i.gkd.li/i/17082872',
>         },
>       ],
>     },
>   ],
> }
> ```

为啥本地导入就可以了，我看这个规则跟订阅的也一样啊。gkd本身的bug吗

**Comment by AIsouler** [comment]
>为啥本地导入就可以了，我看这个规则跟订阅的也一样啊。gkd本身的bug吗

这个issue提出的时候最新版订阅的版本号是135，你应该和135版本的代码比较

**Comment by wangshantao** [comment]
> > 为啥本地导入就可以了，我看这个规则跟订阅的也一样啊。gkd本身的bug吗
> 
> 这个issue提出的时候最新版订阅的版本号是135，你应该和135版本的代码比较

应该是我使用的问题，我导入规则的时候是139，发现无法跳过才来找issue的，不过当时gkd没授权应用列表权限，后面发现无法在订阅里找到nga并关闭才发现是要授权，授权后估计就正常了，但是我以为是本地导入规则才正常的。现在我启动订阅规则，关闭本地规则就是正常的。😂😂😂
