### ISSUE TITLE
大佬好，我写了几条关于酷狗概念版的规则，但我不清楚exampleUrls怎么填写，麻烦大佬了

### ISSUE THREAD

**Issue by xfljy** [AIsouler/GKD_subscription#374]
### 一些验证

- [X] 我确保 **提供正确的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接，也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

{
  key: 6,
  name: '功能类-播放页听歌领VIP',
  desc: '适配3.4.9及之前版本',
  fastQuery: true,
  rules: [
    {
      activityIds: 'com.kugou.android.app.MediaActivity',
      matches: '@LinearLayout[clickable=true] > TextView[text="听歌领VIP"]',
      exampleUrls: 'https://e.gkd.li/df927124-4e7a-43bd-8d42-3eb428eecf78',
      snapshotUrls: 'https://i.gkd.li/i/16554695',
    }
  ],
}, 
{
  name: '分段广告-信息流广告',
  key: 7,
  enable: false,
  rules: [
    {
      key: 0,
      matches: '@FrameLayout[clickable=true] > [text="广告"]',
      snapshotUrls: 'https://i.gkd.li/i/17082959',
      exampleUrls: 'https://i.gkd.li/4c59d307-ff35-4f38-adb8-d140191c03ec',
      activityIds: 'com.kugou.android.app.MediaActivity',
    },
    {
      key: 1,
      matches: 'TextView[text="关闭这条广告"]',
      snapshotUrls: 'https://i.gkd.li/i/17082986',
      exampleUrls: 'https://i.gkd.li/4a83d566-9fa1-4d13-a339-3ca9b354e384',
      activityIds: 'com.kugou.android.app.MediaActivity',
    }
      ]
}

**Comment by AIsouler** [comment]
![image](https://github.com/user-attachments/assets/24a16965-94ef-4e5e-9ae0-2f60fb89da07)

你也可以打开以下开关后，写好选择器选中后直接复制

![image](https://github.com/user-attachments/assets/15d49dba-8cf4-46e0-be34-da611272f453)
![image](https://github.com/user-attachments/assets/3c61d609-2b1d-4307-83f6-256252ffbfb8)
