### ISSUE TITLE
请求适配 脉脉 开屏广告

### ISSUE THREAD

**Issue by shuohao** [AIsouler/GKD_subscription#381]
### 一些验证

- [X] 我确保 **提供正确的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接，也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

[脉脉_MainActivity-1727315023083.zip](https://github.com/user-attachments/files/17141064/_MainActivity-1727315023083.zip)

大部分时间是无法跳过开屏广告，但是有时候可以

**Comment by AIsouler** [comment]
36f8db542e6131a2acc7c25a0e428637c232d7df

**Comment by AIsouler** [comment]
把能跳的广告快照也发一下，你可以先关闭规则再截快照

**Comment by shuohao** [comment]
> 把能跳的广告快照也发一下，你可以先关闭规则再截快照

![image](https://github.com/user-attachments/assets/aa3c68fd-47d0-496b-836d-340fb3d6ffd0)
github抽风了 附件死活传不上来了

**Comment by shuohao** [comment]
> 把能跳的广告快照也发一下，你可以先关闭规则再截快照

[脉脉_MainActivity-1727319931108.zip](https://github.com/user-attachments/files/17142209/_MainActivity-1727319931108.zip)

看下这个是不是可以
