### ISSUE TITLE
小米主题商店中广告无法自动点击关闭

### ISSUE THREAD

**Issue by EricKY26** [AIsouler/GKD_subscription#383]
### 一些验证

- [X] 我确保 **提供 误触/不执行规则 的界面的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入 误触/不执行规则 的界面的快照，BUG描述及其复现步骤(视频/截图)或者生成的快照链接，也可在后面补充其它信息
请注意: 
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

https://i.gkd.li/i/17143445
https://i.gkd.li/i/17143447
![Screenshot_2024-09-26-13-55-03-174_com android thememanager](https://github.com/user-attachments/assets/f220dbf4-162a-47f5-ba72-761ccfbe2544)
![Screenshot_2024-09-26-13-55-53-646_com android thememanager](https://github.com/user-attachments/assets/acfd644d-70c3-4080-b431-aa7efc8af355)
![Screenshot_2024-09-26-13-56-23-554_li songe gkd](https://github.com/user-attachments/assets/922f4245-d8e6-4ea1-bf2c-8b9ecc490406)

由于点击小米主题商店里广告的关闭按钮后弹出对话框之后 无法截取快照(无法点击悬浮窗也无法下拉状态栏) ，所以快照为点击关闭按钮之前的页面，附件截图为点击之后的效果，GKD也是会停在截图这个页面，无法执行下一步点击选项 “不感兴趣”

**Comment by EricKY26** [comment]
问题分别出现在主题商店的主页和主题详情页

**Comment by AIsouler** [comment]
没有快照无法适配，你可以尝试安装gkd最新构建版使用音量变化截快照https://github.com/gkd-kit/gkd/actions/runs/11010797538

**Comment by AIsouler** [comment]
你也可以尝试冻结智能服务这个软件，可去掉大部分小米系统广告

**Comment by EricKY26** [comment]
https://i.gkd.li/i/17146747
https://i.gkd.li/i/17146749
我用截屏触发的方式抓到快照了，发现是智能服务
附上log
https://f.gkd.li/17146766

**Comment by AIsouler** [comment]
开启智能服务对应规则
