### ISSUE TITLE
六只脚广告

### ISSUE THREAD

**Issue by Hw19951017** [AIsouler/GKD_subscription#389]
### 一些验证

- [X] 我确保 **提供正确的快照（不要提供截图，截图没有任何作用）**，否则我同意维护者直接关闭issue
- [X] 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD（包括beta版）](https://github.com/gkd-kit/gkd/releases/latest)
- [X] 我确保已阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue

### 请输入需要添加规则的界面的快照或者生成的链接，也可在后面补充其它信息
请注意:
1. 不提供快照或者仅提供截图的 issue 将被自动关闭
2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭

[六只脚_ProMainActivity-1728135634294.zip](https://github.com/user-attachments/files/17268032/_ProMainActivity-1728135634294.zip)

**Comment by AIsouler** [comment]
adf583bd510a445a3f5ef9cc8cd8bf8ba40a5903
你在另一个issue的评论下发就行了，没必要重新开一个

**Comment by Hw19951017** [comment]
![六只脚_ProMainActivity-1728457409261.zip](https://github.com/user-attachments/files/17303745/_ProMainActivity-1728457409261.zip)

**Comment by Hw19951017** [comment]
无法跳过

**Comment by AIsouler** [comment]
这个右下角的文本除了```立即申请```和```下载应用```还有吗，如果有的话就发一下快照
![image](https://github.com/user-attachments/assets/13cb37c0-bbd3-484b-93a4-bc6bfbacbb86)

**Comment by Hw19951017** [comment]
没有了，目前就发现这两个

**Comment by Hw19951017** [comment]
还有就是存在弹窗情况

**Comment by AIsouler** [comment]
> 还有就是存在弹窗情况

发快照

**Comment by Hw19951017** [comment]
![Screenshot_20241009_084348_com_topgether_sixfoot_ProMainActivity.jpg](https://github.com/user-attachments/assets/e3f29120-ff79-4f64-891d-81ed3af93d82)

这种弹窗，快照截不下来> > 还有就是存在弹窗情况
> 
> 发快照

**Comment by AIsouler** [comment]
这个你应该去gkd那边反馈

**Comment by AIsouler** [comment]
09390232d7191a401ef91de0368bd559a3704aa0
