### ISSUE TITLE
请求更新“微信-分段广告-订阅号消息内容-广告”

### ISSUE THREAD

**Issue by bbbiin** [AIsouler/GKD_subscription#423]
### 请输入需要适配界面的快照或者生成的链接，也可在后面补充其它信息

对于微信订阅号文章底部新类型广告，现有规则只点击一段——
一段：https://i.gkd.li/i/17464276
二段：https://i.gkd.li/i/17464284
三段：https://i.gkd.li/i/17464289

**Comment by AIsouler** [comment]
广告反馈节点```clickable=false```，为防止误触不予适配
