### ISSUE TITLE
交通银行 vivo应用商店

### ISSUE THREAD

**Issue by fxzxmicah** [AIsouler/GKD_subscription#435]
### 请输入需要适配界面的快照或者生成的链接，也可在后面补充其它信息

[交通银行_MainActivity-1730140829889.zip](https://github.com/user-attachments/files/17547536/_MainActivity-1730140829889.zip)
[应用商店_AppStoreTabActivity-1714202955060.zip](https://github.com/user-attachments/files/17547538/_AppStoreTabActivity-1714202955060.zip)

**Comment by fxzxmicah** [comment]
![Screenshot_20241101_141219](https://github.com/user-attachments/assets/a78b4e20-184b-4993-8e16-19e357fe0076)
我发现交通银行这个提示有时候在activity是null的时候就出现了，这样会导致点击触发得非常晚，这种有办法解决吗？

**Comment by AIsouler** [comment]
当识别不到某个界面的activityid时gkd会把这个软件的所有规则都在这个界面匹配，可能是规则太多导致阻塞了，你可以关闭这个软件的部分规则，或者在高级模式里开启shizuku界面识别
