### ISSUE TITLE
[Bug] 澎湃安装界面会自动点击取消更新

### ISSUE THREAD

**Issue by chiyomii** [AIsouler/GKD_subscription#447]
### 请提供 误触界面/出现问题界面 的快照，也可补充说明

[com.miui.packageinst_NewInstallerPrepareActivity-1730359611136.zip](https://github.com/user-attachments/files/17584538/com.miui.packageinst_NewInstallerPrepareActivity-1730359611136.zip)

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

![Screenshot_2024-10-31-15-29-13-334_li songe gkd-edit](https://github.com/user-attachments/assets/48e698c4-d3c5-4a60-916a-17aed8136cc8)

**Comment by AIsouler** [comment]
你确定这个误触是我的订阅导致的？
