### ISSUE TITLE
今日头条

### ISSUE THREAD

**Issue by git0706** [AIsouler/GKD_subscription#450]
### 请提供 需要适配界面 的快照，也可补充说明

[今日头条_MainActivity-1730476645307.zip](https://github.com/user-attachments/files/17602069/_MainActivity-1730476645307.zip)

**Comment by shuohao** [comment]
我的也是 今日头条开屏广告没跳过
[今日头条-1730514487384.zip](https://github.com/user-attachments/files/17605293/-1730514487384.zip)

**Comment by AIsouler** [comment]
> ### 请提供 需要适配界面 的快照，也可补充说明
> [今日头条_MainActivity-1730476645307.zip](https://github.com/user-attachments/files/17602069/_MainActivity-1730476645307.zip)

你的快照没有截图

![image](https://github.com/user-attachments/assets/116b2522-40f0-4bb7-96f0-ac8d58018dd3)

**Comment by AIsouler** [comment]
> 我的也是 今日头条开屏广告没跳过 [今日头条-1730514487384.zip](https://github.com/user-attachments/files/17605293/-1730514487384.zip)

6b4039c7b9a4c3aa163224e5ccb762ffd342c8ad
