### ISSUE TITLE
[Feature] 懒懒视频

### ISSUE THREAD

**Issue by git0706** [AIsouler/GKD_subscription#456]
### 请提供 需要适配界面 的快照，也可补充说明

[今日头条_MainActivity-1730476645307.zip](https://github.com/user-attachments/files/17610143/_MainActivity-1730476645307.zip)
这次应该有截图了

**Comment by AIsouler** [comment]
你应该授予gkd截图权限重新截取快照，而不是使用原来的快照替换截图，另外可以在原issue下面评论，没必要重新开一个

**Comment by git0706** [comment]
真是不好意思。因为我是直接下载ZIP到手机上的，但是没想到，第一次上传的ZIP包里的截图居然是空白的，奇怪的是我单独下载的快照图片又在手机里，所以我第二次上传zip包的时候是把单独的快照图放进了第一次的压缩包里。&nbsp;


?&nbsp;.&nbsp;&nbsp;?&nbsp;?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月3日(星期天) 晚上7:34
收件人: ***@***.***&gt;; 
抄送: "🇨 .  🇾 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AIsouler/GKD_subscription] 今日头条 (Issue #456)














 
你应该授予gkd截图权限重新截取快照，而不是使用原来的快照替换截图，另外可以在原issue下面评论，没必要重新开一个

**Comment by AIsouler** [comment]
没关系的，你可以重新截取一下，在gkd快照记录里点击快照查看就能看到是否有截图

**Comment by git0706** [comment]
![懒懒视频_BaseActivity-1738888791626.zip](https://github.com/user-attachments/files/18699314/_BaseActivity-1738888791626.zip)
