### ISSUE TITLE
[Feature] vivo自动安装软件  第一个点击继续安装  第二个点击完成

### ISSUE THREAD

**Issue by shuang-art** [AIsouler/GKD_subscription#457]
### 请提供 需要适配界面 的快照，也可补充说明

[软件包安装程序_NewInstallInstalling-1730635559744.zip](https://github.com/user-attachments/files/17610352/_NewInstallInstalling-1730635559744.zip)
[软件包安装程序_PackageInstallerActivity-1730635526336.zip](https://github.com/user-attachments/files/17610353/_PackageInstallerActivity-1730635526336.zip)

**Comment by AIsouler** [comment]
现有规则无效吗？

**Comment by shuang-art** [comment]
好像没有规则

**Comment by AIsouler** [comment]
有啊

**Comment by shuang-art** [comment]
![Screenshot_20241103_212438](https://github.com/user-attachments/assets/b9a7aaa8-7763-401f-bcab-4ed4fbeab932)
![Screenshot_20241103_212446](https://github.com/user-attachments/assets/1fab1f42-49a9-4729-814d-83b4f2409e9c)

**Comment by AIsouler** [comment]
右上角勾选显示系统应用

**Comment by shuang-art** [comment]
有了谢谢
