### ISSUE TITLE
[Bug] 光大银行

### ISSUE THREAD

**Issue by cyfgit** [AIsouler/GKD_subscription#461]
### 请提供 误触界面/出现问题界面 的快照，也可补充说明

光大银行app 开屏广告跳过失败

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

光大银行app 开屏广告跳过失败
[光大银行_HomeActivity-1730706698068.zip](https://github.com/user-attachments/files/17615257/_HomeActivity-1730706698068.zip)

**Comment by AIsouler** [comment]
这种情况应该请求适配
![image](https://github.com/user-attachments/assets/31903c40-cfd9-4d1b-93d1-4580e4351a69)
