### ISSUE TITLE
[Bug] 此规则在跳过B站开屏广告后，卡住无法加载进去！<急！！>

### ISSUE THREAD

**Issue by 873318031** [AIsouler/GKD_subscription#468]
### 请提供 误触界面/出现问题界面 的快照，也可补充说明

[Bug] 此规则在跳过B站开屏广告后，卡住无法加载进去！<急！！>

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

[Bug] 此规则在跳过B站开屏广告后，卡住无法加载进去！<急！！>

**Comment by AIsouler** [comment]
这是B站的问题，你可以关闭这条规则

**Comment by 873318031** [comment]
好吧，那这跳不了B站广告了&nbsp;


873318031
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月6日(星期三) 中午12:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AIsouler/GKD_subscription] [Bug] 此规则在跳过B站开屏广告后，卡住无法加载进去！<急！！&gt; (Issue #468)





 
这是B站的问题，你可以关闭这条规则
 
&mdash;
