### ISSUE TITLE
用户弄错两个不同软件的问题

### ISSUE THREAD

**Issue by hmy65** [AIsouler/GKD_subscription#470]
### 请提供 误触界面/出现问题界面 的快照，也可补充说明

其他问题

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

名称错误

**Comment by hmy65** [comment]
![fb7934c3f973d647c8ba2b17d3a055e](https://github.com/user-attachments/assets/c43fb3e6-c816-4767-8a75-219eadb4afd2)
![d785da72759e80402f285e3c2a222b5](https://github.com/user-attachments/assets/47ef59de-0134-44fd-9325-db8e3ec8e9c5)

**Comment by AIsouler** [comment]
这个主题商店包名不一样吧，你发一下快照

**Comment by hmy65** [comment]
主题壁纸 com.android.thememanager
主题商店 com.miui.themestore

**Comment by AIsouler** [comment]
从包名来看这是两个不同的软件
