### ISSUE TITLE
12306开屏广告无法去除

### ISSUE THREAD

**Issue by Colspace** [AIsouler/GKD_subscription#473]
### 请提供 误触界面/出现问题界面 的快照，也可补充说明

内置规则的，图片与这个不相符无法跳过

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

![Screenshot_2024-11-07-10-55-44-47_8c62b8ae0c9e9394fc7a6d0d95ed541c](https://github.com/user-attachments/assets/fe88f9cb-e342-4856-a748-4e7d15bc863f)

**Comment by AIsouler** [comment]
下次花点时间看一下
![image](https://github.com/user-attachments/assets/93d3c345-410d-4ca5-b034-c67847b6caf0)
