### ISSUE TITLE
B站视频播放下面的推荐广告

### ISSUE THREAD

**Issue by moumouye** [AIsouler/GKD_subscription#477]
### 请提供 需要适配界面 的快照，也可补充说明

[哔哩哔哩_UnitedBizDetailsActivity-1731052839342.zip](https://github.com/user-attachments/files/17675235/_UnitedBizDetailsActivity-1731052839342.zip)

B站下面的推荐广告太多了

**Comment by AIsouler** [comment]
这个广告还有第二段，发一下第二段的快照

**Comment by moumouye** [comment]
是这个二段的吗？
[Uploading 哔哩哔哩_UnitedBizDetailsActivity-1731055373599.zip…]()
 可以的话这个直播的推荐也可以屏蔽吗？

**Comment by AIsouler** [comment]
这个快照没上传成功，请重新传一下，这是正在上传的意思
![image](https://github.com/user-attachments/assets/d95d5b73-8564-4ffd-a040-9b47dd2b1c05)

**Comment by AIsouler** [comment]
你可以直接生成快照链接把链接发上来

**Comment by AIsouler** [comment]
这个是点击广告右下角三个点后出现的吗
![image](https://github.com/user-attachments/assets/2882a98c-0439-45bb-b3e1-c66fd5d6b2eb)
![image](https://github.com/user-attachments/assets/2ac3fd58-5aa8-41e1-af6a-c7d3e141d2f5)

**Comment by moumouye** [comment]
不是的，我要点击不感兴趣之后，我在发下

**Comment by AIsouler** [comment]
直播那个第二段也发一下

**Comment by moumouye** [comment]
[直播-我不想看](https://i.gkd.li/i/17676149)
[直播-点击后效果](https://i.gkd.li/i/17676167)

**Comment by moumouye** [comment]
广告花样太多了，这次看见小火箭的
[广告-小火箭效果的](https://i.gkd.li/i/17676212)
[三个小点-屏蔽广告.zip](https://github.com/user-attachments/files/17676323/_UnitedBizDetailsActivity-1731057907488.zip)
[点击后效果.zip](https://github.com/user-attachments/files/17676325/_UnitedBizDetailsActivity-1731057920241.zip)

这个上传又是抽筋，超时了，这次没弄好，用了压缩包

**Comment by AIsouler** [comment]
点击不感兴趣后的快照没必要发
