### ISSUE TITLE
[Bug] 最新规则bilibili青少年模式失效

### ISSUE THREAD

**Issue by PCreamix** [AIsouler/GKD_subscription#486]
### 请提供 误触界面/出现问题界面 的快照，也可补充说明

 最新规则bilibili青少年模式失效，可以跳过开屏广告，青少年模式不能触发，需要手动点击，上一版本可以正常使用

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

 最新规则bilibili青少年模式失效，青少年模式不能触发

**Comment by bobzjh** [comment]
bilibili我也遇到了，还有抖音的青少年模式最近也不行了。

**Comment by bbbiin** [comment]
https://i.gkd.li/i/17711909
