### ISSUE TITLE
[Feature] 请求适配bilibili互动弹幕

### ISSUE THREAD

**Issue by smrila** [AIsouler/GKD_subscription#487]
### 请提供 需要适配界面 的快照，也可补充说明

b站app端看视频，经常会弹出投票、选项、评分等弹窗，请求适配关闭

参考：
- https://search.bilibili.com/all?keyword=%E6%8A%95%E7%A5%A8%E5%BC%B9%E5%B9%95&search_source=1

**Comment by smrila** [comment]
[snapshot-1731241408371.zip](https://github.com/user-attachments/files/17691378/snapshot-1731241408371.zip)

**Comment by Snoopy1866** [comment]
关闭按钮没有节点，视频播放可以全屏，因此 position 也无法确定，此外，B 站视频的互动弹幕可以设置显示位置，因此，无法适配。
