### ISSUE TITLE
大麦开屏广告求适配或修复

### ISSUE THREAD

**Issue by xwz840525475** [AIsouler/GKD_subscription#488]
### 请提供 需要适配界面 的快照，也可补充说明

[大麦_SplashMainActivity-1731217001836.zip](https://github.com/user-attachments/files/17690381/_SplashMainActivity-1731217001836.zip)

**Comment by AIsouler** [comment]
在gkd高级设置里开启shizuku模拟点击，如果还不行的话我也没办法了
