### ISSUE TITLE
请求更新“应用包管理组件-功能类-自动安装/更新应用”规则

### ISSUE THREAD

**Issue by bbbiin** [AIsouler/GKD_subscription#490]
### 请提供 需要适配界面 的快照，也可补充说明

该规则不自动触发，下滑一次通知栏或重新切回该页面时才触发https://i.gkd.li/i/17690785

**Comment by Snoopy1866** [comment]
https://github.com/AIsouler/GKD_subscription/blob/136e0820f860c593c4733ffc15adddad73664ef0/src/apps/com.miui.packageinstaller.ts#L30-L46

规则看起来没问题。

**Comment by bbbiin** [comment]
v152版本规则依旧存在这个情况https://i.gkd.li/i/17691996

**Comment by Snoopy1866** [comment]
应该是少了一个 activityId

```json5
activityIds: 'com.miui.packageInstaller.ui.InstallPrepareAlertActivity',
```
