### ISSUE TITLE
[Bug] 微信的自动打开原图失效

### ISSUE THREAD

**Issue by SliverHydra** [AIsouler/GKD_subscription#492]
### 请提供 误触界面/出现问题界面 的快照，也可补充说明

![Screenshot_20241111_102309_com_tencent_mm_LauncherUI](https://github.com/user-attachments/assets/39670abf-ffc3-474d-bfed-6d9605419bf9)
![Screenshot_20241111_102316_li_songe_gkd_MainActivity](https://github.com/user-attachments/assets/0d1580f0-d863-40d4-8f34-5ddbd8985a62)

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

微信的自动打开原图失效，QQ 的自动打开原图是正常的，重启手机，卸载软件都试过了，麻烦大大看一下是什么问题？

**Comment by SliverHydra** [comment]
https://i.gkd.li/i/17698352

**Comment by AIsouler** [comment]
> https://i.gkd.li/i/17698352

快照数据缺失，请重新截取快照上传

**Comment by SliverHydra** [comment]
好的

**Comment by SliverHydra** [comment]
https://i.gkd.li/i/17698482

**Comment by SliverHydra** [comment]
好像他就是没反应😓，没有动作

**Comment by SliverHydra** [comment]
我还能提供啥不，大大

**Comment by AIsouler** [comment]
快照加载资源失败，貌似哪里出问题了，你能打开快照链接吗

**Comment by SliverHydra** [comment]
我可以自己打开

**Comment by SliverHydra** [comment]
那我打开截图么？

**Comment by AIsouler** [comment]
不用，截图没有任何作用，现在我打开不了快照链接，不知道哪里出了问题，你可以把快照保存到本地然后上传压缩包到这里

**Comment by SliverHydra** [comment]
[微信_LauncherUI-1731308186907.zip](https://github.com/user-attachments/files/17698937/_LauncherUI-1731308186907.zip)
[微信_LauncherUI-1731309191945.zip](https://github.com/user-attachments/files/17698941/_LauncherUI-1731309191945.zip)
