### ISSUE TITLE
飞书自动点击原图bug

### ISSUE THREAD

**Issue by Gausx** [AIsouler/GKD_subscription#494]
### 请提供 误触界面/出现问题界面 的快照（不要提供截图！！！），也可补充说明

[飞书_ChatWindowActivity-1731370430626.zip](https://github.com/user-attachments/files/17709397/_ChatWindowActivity-1731370430626.zip)

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

![Screenshot_2024-11-12-08-14-35-08_befd3b55c4270226022f86e9f9cafb33](https://github.com/user-attachments/assets/52ea4dfd-c157-4ed0-b95a-f3a62aa67509)

**Comment by AIsouler** [comment]
请问有什么问题呢

**Comment by AIsouler** [comment]
导入这个到本地试试
```
{
  id: 'com.ss.android.lark',
  name: '飞书',
  groups: [
    {
      key: 1,
      name: '功能类-勾选原图',
      rules: [
        {
          fastQuery: true,
          activityIds: '.chatwindow.ChatWindowActivity',
          matches: '[vid="layout_original_photo"][checked=false]',
          exampleUrls: 'https://e.gkd.li/3a0aee51-5a22-4ac8-be49-fd89f4eb0cc2',
          snapshotUrls: 'https://i.gkd.li/i/17710040',
        },
      ],
    },
  ],
}
```

**Comment by Gausx** [comment]
![Screenshot_2024-11-12-12-47-32-49_befd3b55c4270226022f86e9f9cafb33.jpg](https://github.com/user-attachments/assets/aca874a9-9e0f-4bfb-85c5-5c66894be76a)

-![飞书_ChatWindowActivity-1731386839350.zip](https://github.com/user-attachments/files/17711255/_ChatWindowActivity-1731386839350.zip)

还是一样的效果，不停的点击原图按钮

> 导入这个到本地试试，先关掉订阅里的
> ```
> {
>   id: 'com.ss.android.lark',
>   name: '飞书',
>   groups: [
>     {
>       key: 1,
>       name: '功能类-勾选原图',
>       rules: [
>         {
>           fastQuery: true,
>           activityIds: '.chatwindow.ChatWindowActivity',
>           matches: '[vid="layout_original_photo"][checked=false]',
>           exampleUrls: 'https://e.gkd.li/3a0aee51-5a22-4ac8-be49-fd89f4eb0cc2',
>           snapshotUrls: 'https://i.gkd.li/i/17710040',
>         },
>       ],
>     },
>   ],
> }
> ```

**Comment by AIsouler** [comment]
那无法适配，因为勾选原图的节点```checkable=false```

**Comment by AIsouler** [comment]
你关闭这条规则然后发一下勾选原图后的快照看看

**Comment by Gausx** [comment]
> 那无法适配，因为勾选原图的节点```checkable=false```

好的  感谢

**Comment by Gausx** [comment]
![飞书_ChatWindowActivity-1731387323330.zip](https://github.com/user-attachments/files/17711291/_ChatWindowActivity-1731387323330.zip)


> 你关闭这条规则然后发一下勾选原图后的快照看看

**Comment by AIsouler** [comment]
还是适配不了，我限制了次数为一次，你导入试试
```
{
  id: 'com.ss.android.lark',
  name: '飞书',
  groups: [
    {
      key: 1,
      name: '功能类-勾选原图',
      actionMaximum: 1,
      rules: [
        {
          fastQuery: true,
          activityIds: '.chatwindow.ChatWindowActivity',
          matches: '[vid="layout_original_photo"][checked=false]',
          exampleUrls: 'https://e.gkd.li/3a0aee51-5a22-4ac8-be49-fd89f4eb0cc2',
          snapshotUrls: 'https://i.gkd.li/i/17710040',
        },
      ],
    },
  ],
}
```

**Comment by Gausx** [comment]
这次可以了  实验了几下没有问题


> 还是适配不了，我限制了次数为一次，你导入试试，关闭其他的
> ```
> {
>   id: 'com.ss.android.lark',
>   name: '飞书',
>   groups: [
>     {
>       key: 1,
>       name: '功能类-勾选原图',
>       actionMaximum: 1,
>       rules: [
>         {
>           fastQuery: true,
>           activityIds: '.chatwindow.ChatWindowActivity',
>           matches: '[vid="layout_original_photo"][checked=false]',
>           exampleUrls: 'https://e.gkd.li/3a0aee51-5a22-4ac8-be49-fd89f4eb0cc2',
>           snapshotUrls: 'https://i.gkd.li/i/17710040',
>         },
>       ],
>     },
>   ],
> }
> ```
