### ISSUE TITLE
[Bug] 打开了微信的自动点击查看原图，但是尝试很多次  都没有自动点击   以下是快照   麻烦帮忙看看原因

### ISSUE THREAD

**Issue by Z46I4W5476SJA** [AIsouler/GKD_subscription#496]
### 请提供 误触界面/出现问题界面 的快照（不要提供截图！！！），也可补充说明

[微信_LauncherUI-1731422751485.zip](https://github.com/user-attachments/files/17718254/_LauncherUI-1731422751485.zip)

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

微信-功能类-自动查看原图

**Comment by AIsouler** [comment]
规则更新到了最新版吗？

**Comment by Z46I4W5476SJA** [comment]
> 规则更新到了最新版吗？

你好   早上我尝试了   更新到最新版本     已经可以正常点击了   非常感谢
