### ISSUE TITLE
抖音未成年模式有问题

### ISSUE THREAD

**Issue by bobzjh** [AIsouler/GKD_subscription#498]
### 请提供 误触界面/出现问题界面 的快照（不要提供截图！！！），也可补充说明

[抖音_MainActivity-1731449817810.zip](https://github.com/user-attachments/files/17725696/_MainActivity-1731449817810.zip)

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

抖音未成年模式关键词匹配出问题，应修改为matches: [
        '[text*="未成年人模式"]',
        '[text="关闭" || desc="关闭"]'

**Comment by AIsouler** [comment]
这些你是装看不见吗
![image](https://github.com/user-attachments/assets/48a7b770-59b7-4246-a304-7b04ed8bad9b)

**Comment by bobzjh** [comment]
> 这些你是装看不见吗 ![image](https://private-user-images.githubusercontent.com/57941037/385568242-48a7b770-59b7-4246-a304-7b04ed8bad9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0Njg4ODMsIm5iZiI6MTczMTQ2ODU4MywicGF0aCI6Ii81Nzk0MTAzNy8zODU1NjgyNDItNDhhN2I3NzAtNTliNy00MjQ2LWEzMDQtN2IwNGVkOGJhZDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAzMjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMGRiY2I5YTMyZDlmZDNkMWIyYjU4ZTc4YjA5NWVjZDRjMTk2MGVhNGRhNWY4ZDgwYjdlYjQ5ODc4OGUwMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9bJ6qy4bDC_H8uNFOH_1UnmoHqIlFnXRztMTwaRyUdc)

已上传快照
