### ISSUE TITLE
[Feature]  同花顺 去除 开屏广告

### ISSUE THREAD

**Issue by tiyuban123** [AIsouler/GKD_subscription#499]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

[Uploading 同花顺_Hexin-1731464988935.zip…]()

**Comment by tiyuban123** [comment]
[Uploading 同花顺_Hexin-1731464988935.zip…]()

**Comment by AIsouler** [comment]
你的快照没有上传成功，请重新上传
![image](https://github.com/user-attachments/assets/3b55c2bc-751a-4fc6-8d56-63b7fb0262c6)
这个是正在上传的意思，你等到没有uplaoding字样了再提交

**Comment by tiyuban123** [comment]
[同花顺_Hexin-1731464988935.zip](https://github.com/user-attachments/files/17725612/_Hexin-1731464988935.zip)

**Comment by tiyuban123** [comment]
> 你的快照没有上传成功，请重新上传 ![image](https://private-user-images.githubusercontent.com/57941037/385567754-3b55c2bc-751a-4fc6-8d56-63b7fb0262c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NzQ3NTYsIm5iZiI6MTczMTQ3NDQ1NiwicGF0aCI6Ii81Nzk0MTAzNy8zODU1Njc3NTQtM2I1NWMyYmMtNzUxYS00ZmM2LThkNTYtNjNiN2ZiMDI2MmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA1MDczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNDVkMTFiNzFkM2MyNmY2YjI0ZDlkMTVmN2RiMTc0NDUzYjZkMjAwMzRjYzA3MzBjNGYwNTM3NDg3OWY3MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2_eKhks2MamNtndQaBtS6Baipv41cdkk_wxZko2jSFs) 这个是正在上传的意思，你等到没有uplaoding字样了再提交

[同花顺_Hexin-1731464988935.zip](https://github.com/user-attachments/files/17726560/_Hexin-1731464988935.zip)

**Comment by AIsouler** [comment]
你导入到本地试试
```
{
  id: 'com.hexin.plat.android',
  name: '同花顺',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      priorityTime: 10000,
      rules: [
        {
          position: {
            left: 'width * 3.7',
            top: 'width * -6.9281',
          },
          matches: '@[id="android:id/title"][childCount=0] < LinearLayout < [parent=null]',
          exampleUrls: 'https://e.gkd.li/f9c7621d-8b2b-4ca8-9904-fe0bca61c43f',
          snapshotUrls: 'https://i.gkd.li/i/17726527',
        },
      ],
    },
  ],
}
```

**Comment by tiyuban123** [comment]
> 你导入到本地试试
> 
> ```
> {
>   id: 'com.hexin.plat.android',
>   name: '同花顺',
>   groups: [
>     {
>       key: 1,
>       name: '开屏广告',
>       matchTime: 10000,
>       actionMaximum: 1,
>       resetMatch: 'app',
>       priorityTime: 10000,
>       rules: [
>         {
>           position: {
>             left: 'width * 3.7',
>             top: 'width * -6.9281',
>           },
>           matches: '@[id="android:id/title"][childCount=0] < LinearLayout < [parent=null]',
>           exampleUrls: 'https://e.gkd.li/f9c7621d-8b2b-4ca8-9904-fe0bca61c43f',
>           snapshotUrls: 'https://i.gkd.li/i/17726527',
>         },
>       ],
>     },
>   ],
> }
> ```

可以去开屏广告了 感谢
