### ISSUE TITLE
小程序开屏广告求适配

### ISSUE THREAD

**Issue by pyb2000** [AIsouler/GKD_subscription#505]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

https://i.gkd.li/snapshot/1731660978740

**Comment by AIsouler** [comment]
这个链接我访问不了，你需要在快照页面右上角复制分享链接
![image](https://github.com/user-attachments/assets/e8dfc27c-57ec-4b0f-9b3c-c13b08bf88c4)

**Comment by pyb2000** [comment]
https://i.gkd.li/i/17772203 这样可以了么

**Comment by AIsouler** [comment]
无法适配
