### ISSUE TITLE
哔哩哔哩的“分段广告-首页推荐视频卡片广告”规则一直触发分享页面

### ISSUE THREAD

**Issue by bocchi810** [AIsouler/GKD_subscription#510]
### 请提供 误触界面/出现问题界面 的快照（不要提供截图！！！），也可补充说明

https://i.gkd.li/i/17789790

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

分段广告-首页推荐视频卡片广告
![Screenshot_20241117-181513](https://github.com/user-attachments/assets/52912fa6-d532-4f67-9b94-5849857eb2a9)

**Comment by AIsouler** [comment]
你的快照不对，这是误触之后的界面，不是误触界面

**Comment by bocchi810** [comment]
> 你的快照不对，这是误触之后的界面，不是误触界面

额，看我能不能再刷到相似的复现页面吧，但这个bug已经出现多次了

**Comment by AIsouler** [comment]
复现后你可以先关闭这条规则再截快照

**Comment by bocchi810** [comment]
新的快照
https://i.gkd.li/i/17848536

**Comment by aoguai** [comment]
补充一下，也可能是因为：

https://github.com/AIsouler/GKD_subscription/blob/d4fcc915581dba5e0f45e947241a63a56b4b6153/src/apps/tv.danmaku.bili.ts#L207

没匹配上导致的一直出发分享页面

例如 https://i.gkd.li/i/13625309

**Comment by AIsouler** [comment]
> 补充一下，也可能是因为：
> 
> https://github.com/AIsouler/GKD_subscription/blob/d4fcc915581dba5e0f45e947241a63a56b4b6153/src/apps/tv.danmaku.bili.ts#L207
> 
> 没匹配上导致的一直出发分享页面
> 
> 例如 https://i.gkd.li/i/13625309

0cd7c54c7d1de0ff54b48b5b7ff7898ba9052f3c
