### ISSUE TITLE
[Feature] 直播吧适配

### ISSUE THREAD

**Issue by Ctrl521** [AIsouler/GKD_subscription#515]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

[直播吧_MainActivity-1730927873083.zip](https://github.com/user-attachments/files/17823452/_MainActivity-1730927873083.zip)
[直播吧_MainActivity-1732061836234.zip](https://github.com/user-attachments/files/17823453/_MainActivity-1732061836234.zip)

**Comment by AIsouler** [comment]
建议更新一下gkd
