### ISSUE TITLE
[Feature] bilibili Play版本（漫游X修改版，包名和Play版一样）

### ISSUE THREAD

**Issue by FUKUA2010** [AIsouler/GKD_subscription#521]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

这个弹窗，点击了解按钮才能正常使用

[bilibili_MainActivityV2-1732165511222[1].zip](https://github.com/user-attachments/files/17840232/bilibili_MainActivityV2-1732165511222.1.zip)

**Comment by AIsouler** [comment]
导入到本地使用，不纳入仓库
```
{
  id: 'com.bilibili.app.in',
  name: 'bilibili',
  groups: [
    {
      key: 1,
      name: '通知提示-公告弹窗',
      desc: '点击[了解]',
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      rules: [
        {
          fastQuery: true,
          activityIds: 'tv.danmaku.bili.MainActivityV2',
          matches: [
            '[text="使用说明"][visibleToUser=true]',
            '[text="了解"][visibleToUser=true]',
          ],
          snapshotUrls: 'https://i.gkd.li/i/17840294',
        },
      ],
    },
  ],
}
```

**Comment by FUKUA2010** [comment]
> 导入到本地使用，不纳入仓库
> 
> ```
> {
>   id: 'com.bilibili.app.in',
>   name: 'bilibili',
>   groups: [
>     {
>       key: 1,
>       name: '通知提示-公告弹窗',
>       desc: '点击[了解]',
>       matchTime: 10000,
>       actionMaximum: 1,
>       resetMatch: 'app',
>       rules: [
>         {
>           fastQuery: true,
>           activityIds: 'tv.danmaku.bili.MainActivityV2',
>           matches: [
>             '[text="使用说明"][visibleToUser=true]',
>             '[text="了解"][visibleToUser=true]',
>           ],
>           snapshotUrls: 'https://i.gkd.li/i/17840294',
>         },
>       ],
>     },
>   ],
> }
> ```

好的，感谢大佬
