### ISSUE TITLE
[Feature] 微信自动抢红包没有延时

### ISSUE THREAD

**Issue by huijun3825** [AIsouler/GKD_subscription#522]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

希望微信自动抢红包设置随机延时功能或者自定义延时功能

**Comment by AIsouler** [comment]
为什么要加延时？

**Comment by Snoopy1866** [comment]
> 为什么要加延时？

~因为抢了客户发给领导的红包~

**Comment by AIsouler** [comment]
> > 为什么要加延时？
> 
> ~因为抢了客户发给领导的红包~

🤣🤣🤣
