### ISSUE TITLE
[Feature] 请求小米手机适配应用包管理组件，自动点击授权本次安装

### ISSUE THREAD

**Issue by pyb2000** [AIsouler/GKD_subscription#526]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

https://i.gkd.li/i/17868600

**Comment by AIsouler** [comment]
右上角关闭 ```安全守护``` 和 ```应用安全验证```

**Comment by AIsouler** [comment]
c710f0761003bceb75ffb8873528d2e4fdb08132

**Comment by pyb2000** [comment]
![Screenshot_2024-11-25-15-06-54-820_com miui packageinstaller](https://github.com/user-attachments/assets/2163a9e9-c770-4e4d-863b-6f07d01664f1)
![Screenshot_2024-11-25-15-06-54-820_com miui packageinstaller](https://github.com/user-attachments/assets/cf1f75b0-a96a-434f-b172-19174aff6df7)
关闭后依旧有弹窗的。
关闭安全守护和应用安全验证后重新快照如下https://i.gkd.li/i/17898736

**Comment by AIsouler** [comment]
请问特殊权限设置里是否允许了安装未知应用？

**Comment by pyb2000** [comment]
![Screenshot_2024-11-25-15-25-46-435_com miui securitycenter](https://github.com/user-attachments/assets/8c1aacd0-9eb2-458d-a370-ed67e8622e26)
![image](https://github.com/user-attachments/assets/0dc25f08-3a57-4a1a-a3ba-a71951a44b16)
![image](https://github.com/user-attachments/assets/2243a804-bdbf-4ceb-b8c2-fb8bed60a7b9)
能关的都关掉了

**Comment by AIsouler** [comment]
我指的是这个，你在里面找到via然后允许
![Screenshot_2024-11-25-15-30-23-895_com android settings-edit](https://github.com/user-attachments/assets/35eed871-694c-49e3-9c4d-2fe2f98344f6)

**Comment by pyb2000** [comment]
手动勾选安装未知应用权限后解除了弹窗了，感谢！

**Comment by AIsouler** [comment]
这个权限隐藏得太深了，我稍后适配一下吧
