### ISSUE TITLE
[Bug] 百度贴吧吧内签到执行两次

### ISSUE THREAD

**Issue by Apollo972** [AIsouler/GKD_subscription#538]
### 请提供 误触界面/出现问题界面 的快照（不要提供截图！！！），也可补充说明

[百度贴吧_ForumActivity-1732530498175.zip](https://github.com/user-attachments/files/17901519/_ForumActivity-1732530498175.zip)

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

签到进行两次，导致停留在补签界面

**Comment by Apollo972** [comment]
![Screenshot_20241125_185020](https://github.com/user-attachments/assets/f2f4b7be-c519-4612-b92e-396cbab59d81)

**Comment by AIsouler** [comment]
> 签到进行两次，导致停留在补签界面

能否录个屏发过来？

**Comment by Apollo972** [comment]
> > 签到进行两次，导致停留在补签界面
> 
> 能否录个屏发过来？

![Screenshot_20241125_195157.jpg](https://github.com/user-attachments/assets/d4c2ee1a-19ab-410a-bcc9-afff9c5865d1)

https://github.com/user-attachments/assets/690a62a1-9839-4282-9ba0-26895363be3c

录屏及该次触发记录

**Comment by AIsouler** [comment]
应该是二次弹窗改了，发一下这个页面的快照
![image](https://github.com/user-attachments/assets/d2ff5ee3-17ad-469e-8f7c-a634c1bf2700)

**Comment by Apollo972** [comment]
> 应该是二次弹窗改了，发一下这个页面的快照
> ![image](https://github.com/user-attachments/assets/d2ff5ee3-17ad-469e-8f7c-a634c1bf2700)
> 

![百度贴吧_TBWebContainerActivity-1732536150708.zip](https://github.com/user-attachments/files/17902589/_TBWebContainerActivity-1732536150708.zip)

**Comment by Apollo972** [comment]
> 应该是二次弹窗改了，发一下这个页面的快照 ![图像](https://private-user-images.githubusercontent.com/57941037/389516935-d2ff5ee3-17ad-469e-8f7c-a634c1bf2700.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MzcwMDEsIm5iZiI6MTczMjUzNjcwMSwicGF0aCI6Ii81Nzk0MTAzNy8zODk1MTY5MzUtZDJmZjVlZTMtMTdhZC00NjllLThmN2MtYTYzNGMxYmYyNzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDEyMTE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNWJhZmI5ZmY4ZTcyZTY0MDNlYjJlYWFiMTdmYTM0YTA1ZWEzZDAyZWUxY2NlMTUyNWE2Y2MxODBkOTIxZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vj3By_Bl9eBfTPNBKWwgClstyUO_XLoPaC5fZThKg0U)

[百度贴吧_TBWebContainerActivity-1732536150708.zip](https://github.com/user-attachments/files/17902692/_TBWebContainerActivity-1732536150708.zip)

**Comment by AIsouler** [comment]
应该是节点延迟消失导致的误触 f9bc8a0ee4933e9f776e5b42a18239916212484c
