### ISSUE TITLE
[Bug] 崩坏：星穹铁道签到失效

### ISSUE THREAD

**Issue by mabenhao** [AIsouler/GKD_subscription#539]
### 请提供 误触界面/出现问题界面 的快照（不要提供截图！！！），也可补充说明

快照：https://i.gkd.li/i/17903189

米游社，崩坏：星穹铁道的每日签到，不能自动领取

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

原选择器为：[text="《崩坏：星穹铁道》签到福利"] >4 View > View + TextView[visibleToUser=true]

我试了一下：[text="《崩坏：星穹铁道》签到福利"] >4 View > View + @TextView[visibleToUser=true]，发现能正常领取了，辛苦作者验证一下

**Comment by AIsouler** [comment]
```[text="《崩坏：星穹铁道》签到福利"] >4 View > View + TextView[visibleToUser=true]``` 和 ```[text="《崩坏：星穹铁道》签到福利"] >4 View > View + @TextView[visibleToUser=true]``` 是等价的，没有@的情况就选择末尾节点

**Comment by mabenhao** [comment]
只有崩铁的签到一直失败，原神和绝区零的都正常。我明天签到再看看吧，今天刚开始研究自己写规则

**Comment by AIsouler** [comment]
签到失败指的是不触发点击还是触发了但是没生效？

**Comment by mabenhao** [comment]
像是完全没执行任务一样，既没有领取，也没有返回到首页。但是我没有留意gkd里的触发记录，所以不知道是每点击还是没生效，需要等待明天0点再次签到

**Comment by AIsouler** [comment]
我这边是能正常触发的
![Screenshot_2024-11-25-21-23-48-692_li songe gkd](https://github.com/user-attachments/assets/61de5066-a806-4a31-b31f-49ea8e702533)
