### ISSUE TITLE
[Feature] 请问一下这种微信里面通过小程序听课的能否自动点击签到

### ISSUE THREAD

**Issue by ccav14** [AIsouler/GKD_subscription#556]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

[微信_AppBrandUI00-1733139383077.zip](https://github.com/user-attachments/files/17978347/_AppBrandUI00-1733139383077.zip)
[微信_AppBrandUI00-1733052713870.zip](https://github.com/user-attachments/files/17978350/_AppBrandUI00-1733052713870.zip)

**Comment by AIsouler** [comment]
你可以使用此选择器：```[text="立即签到"][visibleToUser=true]```

**Comment by ccav14** [comment]
> 你可以使用此选择器：`[text="立即签到"][visibleToUser=true]`

啊，这我不太会弄啊

**Comment by AIsouler** [comment]
![image](https://github.com/user-attachments/assets/c02fa347-6638-4069-ae73-27da2b0c66b6)

**Comment by ccav14** [comment]
> 你可以使用此选择器：`[text="立即签到"][visibleToUser=true]`

多谢提点，这几天按照别的回复里面提到的自己拼凑了一下规则，成功了
