### ISSUE TITLE
[Bug] 百度贴吧个人主页误触跳转会员界面

### ISSUE THREAD

**Issue by ohhshit** [AIsouler/GKD_subscription#566]
### 请提供 误触界面/出现问题界面 的快照（不要提供截图！！！），也可补充说明

[百度贴吧_TBWebContainerActivity-1733458447192.zip](https://github.com/user-attachments/files/18032669/_TBWebContainerActivity-1733458447192.zip)

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

百度贴吧 全屏广告-弹窗广告

**Comment by 156209258y** [comment]
[胖乖生活_InterstitialActivity-1733453489085.zip](https://github.com/user-attachments/files/18032964/_InterstitialActivity-1733453489085.zip)

**Comment by AIsouler** [comment]
> [胖乖生活_InterstitialActivity-1733453489085.zip](https://github.com/user-attachments/files/18032964/_InterstitialActivity-1733453489085.zip)

不要在已有issue下面发不相关的快照，你可以新开一个issue
