### ISSUE TITLE
[Feature] 胖乖生活

### ISSUE THREAD

**Issue by 156209258y** [AIsouler/GKD_subscription#568]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

[胖乖生活_InterstitialActivity-1733453489085.zip](https://github.com/user-attachments/files/18033125/_InterstitialActivity-1733453489085.zip)

**Comment by AIsouler** [comment]
9459dcfccb7bde44890a3e8cd1b00289ce1141b7
