### ISSUE TITLE
[Feature] 车 e 兴开屏广告

### ISSUE THREAD

**Issue by llovejunjie** [AIsouler/GKD_subscription#570]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

[车e兴_SplashActivity-1733553929045.zip](https://github.com/user-attachments/files/18046538/e._SplashActivity-1733553929045.zip)

**Comment by AIsouler** [comment]
全局规则有效，请确认是否开启了全局规则

**Comment by llovejunjie** [comment]
开了全局了，试了好多次，就这个软件开屏不跳

> 全局规则有效，请确认是否开启了全局规则

**Comment by llovejunjie** [comment]
> 全局规则有效，请确认是否开启了全局规则

触发记录里也显示触发了，但是没跳
![Screenshot_2024_1207_165256](https://github.com/user-attachments/assets/3d784672-3a5b-44c6-9c9e-78671dab17e5)

**Comment by AIsouler** [comment]
在高级模式里开启```shizuku模拟点击```试试呢？

**Comment by AIsouler** [comment]
应该是被另一个规则提前触发消耗完了次数，你发一下刚打开软件开屏广告还未加载出来时的快照

**Comment by llovejunjie** [comment]
> 在高级模式里开启`shizuku模拟点击`试试呢？

没有这个软件

**Comment by llovejunjie** [comment]
> 应该是被另一个规则提前触发消耗完了次数，你发一下刚打开软件开屏广告还未加载出来时的快照

好的
[车e兴_SplashActivity-1733562827392.zip](https://github.com/user-attachments/files/18047804/e._SplashActivity-1733562827392.zip)

**Comment by AIsouler** [comment]
你先暂时关闭开屏广告全局规则，然后导入以下规则，多次打开软件，把不能跳的开屏广告的快照发过来
```
{
  id: 'com.anshibo.activity',
  name: '车e兴',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      priorityTime: 10000,
      rules: [
        {
          matches: 'FrameLayout > FrameLayout[childCount>2] > @View[clickable=true][text=null][visibleToUser=true] + TextView[visibleToUser=true][text=null][index=parent.childCount.minus(1)]',
          exampleUrls: 'https://e.gkd.li/7f58925f-39dd-40c3-a8f1-f6e5268eced4',
          snapshotUrls: 'https://i.gkd.li/i/18046569',
        },
      ],
    },
  ],
}
```

**Comment by llovejunjie** [comment]
> 你先暂时关闭开屏广告全局规则，然后导入以下规则，多次打开软件，把不能跳的开屏广告的快照发过来
> 
> ```
> {
>   id: 'com.anshibo.activity',
>   name: '车e兴',
>   groups: [
>     {
>       key: 1,
>       name: '开屏广告',
>       matchTime: 10000,
>       actionMaximum: 1,
>       resetMatch: 'app',
>       priorityTime: 10000,
>       rules: [
>         {
>           matches: 'FrameLayout > FrameLayout[childCount>2] > @View[clickable=true][text=null][visibleToUser=true] + TextView[visibleToUser=true][text=null][index=parent.childCount.minus(1)]',
>           exampleUrls: 'https://e.gkd.li/7f58925f-39dd-40c3-a8f1-f6e5268eced4',
>           snapshotUrls: 'https://i.gkd.li/i/18046569',
>         },
>       ],
>     },
>   ],
> }
> ```

用你发的这个规则就可以正常关闭开屏广告了，试了好多次都可以

**Comment by AIsouler** [comment]
记得把全局规则开启

**Comment by llovejunjie** [comment]
> 记得把全局规则开启

好的，谢谢

**Comment by llovejunjie** [comment]
> 记得把全局规则开启

你上面发的这个规则，我是不是可以删掉了

**Comment by AIsouler** [comment]
下一次规则更新后就可以删掉了

**Comment by llovejunjie** [comment]
> 下一次规则更新后就可以删掉了

好的 非常感谢
