### ISSUE TITLE
[Feature] B站直播 粉丝团灯牌弹窗

### ISSUE THREAD

**Issue by skylayer** [AIsouler/GKD_subscription#571]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

https://i.gkd.li/snapshot/1733554692676

**Comment by skylayer** [comment]
> 你好 skylayer，请在评论中提供必要的快照，以便我们更好地帮助您，谢谢！
> 
> Hello skylayer. Please provide necessary snapshots in the comments so that we can better assist you. Thank you!

https://i.gkd.li/snapshot/1733554692676

**Comment by AIsouler** [comment]
这个链接我访问不了，你需要在快照页面右上角复制分享链接
![image](https://github.com/user-attachments/assets/d4c3802c-3d99-4914-9bfe-9eb267299038)

**Comment by skylayer** [comment]
https://i.gkd.li/i/18046573

**Comment by alifyudha** [comment]
> https://i.gkd.li/i/18046573

hey this might OOT but, do you still remember me? correct me if im wrong that your nick was Harvard Vandermark before? there is something i need to talk if you got a time hit me on my new telegram accounts because i forgot your old telegram username
