### ISSUE TITLE
[Feature] 廣告自動關閉，期望是非特定到軟件

### ISSUE THREAD

**Issue by keanking** [AIsouler/GKD_subscription#573]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

https://i.gkd.li/i/18053470

**Comment by keanking** [comment]
請問我要如何手動新增上

**Comment by AIsouler** [comment]
复制以下代码导入到本地订阅
```
{
  id: 'com.vlending.apps.mubeat',
  name: 'Mubeat',
  groups: [
    {
      key: 1,
      name: '全屏广告',
      desc: '点击关闭',
      rules: [
        {
          fastQuery: true,
          activityIds: '.activity.LauncherActivity',
          matches: '@[desc="Close Ad"][visibleToUser=true] > [text*="Ad"]',
          exampleUrls: 'https://e.gkd.li/86c7a56e-190d-4063-9b38-e8cfd71381e2',
          snapshotUrls: 'https://i.gkd.li/i/18053470',
        },
      ],
    },
  ],
}
```

**Comment by keanking** [comment]
> 复制以下代码导入到本地订阅
> 
> ```
> {
>   id: 'com.vlending.apps.mubeat',
>   name: 'Mubeat',
>   groups: [
>     {
>       key: 1,
>       name: '全屏广告',
>       desc: '点击关闭',
>       rules: [
>         {
>           fastQuery: true,
>           activityIds: '.activity.LauncherActivity',
>           matches: '@[desc="Close Ad"][visibleToUser=true] > [text*="Ad"]',
>           exampleUrls: 'https://e.gkd.li/86c7a56e-190d-4063-9b38-e8cfd71381e2',
>           snapshotUrls: 'https://i.gkd.li/i/18053470',
>         },
>       ],
>     },
>   ],
> }
> ```

感謝
