### ISSUE TITLE
[Bug] 虎扑信息流广告误触，更新了反馈选项

### ISSUE THREAD

**Issue by Chorson** [AIsouler/GKD_subscription#610]
### 请提供 误触界面/出现问题界面 的快照（不要提供截图！！！），也可补充说明

[虎扑_MainActivity-1734064264948.zip](https://github.com/user-attachments/files/18121272/_MainActivity-1734064264948.zip)

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

![Screenshot_20241213_123326](https://github.com/user-attachments/assets/e9ea6f39-d696-4d88-a245-380fa06126a9)
{
  id: 'com.hupu.games',
  name: '虎扑',
  groups: [
    {
      name: '局部广告-推荐流广告',
      key: 1,
      desc: '点击卡片右上角广告文字,出现广告反馈,点击屏蔽该广告',
      enable: false,
      quickFind: true,
      activityIds: [
        'com.hupu.games.main.MainActivity',
        'com.hupu.android.bbs.detail.PostDetailActivity',
        'com.hupu.topic.TopicActivity'
      ],
      rules: [
        {
          key: 0,
          matches: [
            '@[id="com.hupu.games:id/shield_view"] >2 [id="com.hupu.games:id/tv_tag"][text="广告"]'
          ],
          snapshotUrls: [
            'https://i.gkd.li/import/12511005',
            'https://i.gkd.li/import/13258026',
            'https://i.gkd.li/import/13259692'
          ]
        },
        {
          key: 1,
          preKeys: [
            0
          ],
          matches: [
            '@[clickable=true] > [id="com.hupu.games:id/tv_title"][text="屏蔽该广告"]'
          ],
          snapshotUrls: [
            'https://i.gkd.li/import/12511010',
            'https://i.gkd.li/import/12534848',
            'https://i.gkd.li/import/13259699'
          ]
        }
      ]
    }
  ]
}

**Comment by AIsouler** [comment]
这不是我的订阅，谁的订阅出问题你找谁去
![image](https://github.com/user-attachments/assets/6d5347db-5e5f-45f7-8fb5-84a14056c216)
