### ISSUE TITLE
[Bug] 第一次进入相册的弹窗，被安全服务的规则误触

### ISSUE THREAD

**Issue by mabenhao** [AIsouler/GKD_subscription#612]
### 请提供 误触界面/出现问题界面 的快照（不要提供截图！！！），也可补充说明

https://i.gkd.li/i/18126157

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

安全服务规则：'功能类-使用返回退出时直接点击[退出]'

**Comment by AIsouler** [comment]
奇怪，这个包名在有的设备上是叫手机管家，并且根据你给的快照现有规则并不能匹配上，应该不会误触才是

**Comment by AIsouler** [comment]
方便发一个手机管家的快照吗？我看看包名是什么

**Comment by Hi10101** [comment]
我的机型是小米15pro
https://i.gkd.li/i/18127373，需要的是这个界面的快照吗

**Comment by AIsouler** [comment]
包名居然是一样的
应该不会再误触了

**Comment by AIsouler** [comment]
gkd在获取不到activityid（也就是图中的null）时，会把这个软件的所有规则放到这个页面匹配，现在触发不了应该是能获取到activityid，不包含在规则里，所以没有触发，我已经优化了规则，更新后不会再误触了
