### ISSUE TITLE
[Feature] 爱奇艺两个规则

### ISSUE THREAD

**Issue by linuxgi** [AIsouler/GKD_subscription#613]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

GKD：版本1.9.3，已授权Shizuku。
AIsouler订阅规则：版本v164，全局规则的开屏广告已经开启。
手机系统：小米15Pro澎湃2.0.25.0

爱奇艺规则1：爱奇艺开屏广告
爱奇艺开屏广告，有跳过提示，但是实际跳不过去，看完开屏广告才能进去。
快照：https://www.123684.com/s/lV9rVv-15mKv

爱奇艺规则2：爱奇艺全屏广告-视频播放时的广告
爱奇艺视频播放暂停时，希望可以点击：关闭广告，放大暂停画面。
快照：https://www.123684.com/s/lV9rVv-45mKv

**Comment by linuxgi** [comment]
我使用123云盘上传的快照，看不到链接吗
快照1：https://www.123684.com/s/lV9rVv-15mKv
快照2：https://www.123684.com/s/lV9rVv-45mKv

**Comment by linuxgi** [comment]
> 你好 linuxgi，检测到您没有提供快照，请补充必要的快照！
> 
> 可在下方评论区补充

现在能看到链接吗，要换成蓝奏云吗，还是说要用github cookie分享出来才行

**Comment by AIsouler** [comment]
GitHub直接就能上传文件，网盘太麻烦了

**Comment by linuxgi** [comment]
> GitHub直接就能上传文件，网盘太麻烦了

忘记直接上传附件了，我现在补上
[
[爱奇艺_MainActivity-1734103522911.zip](https://github.com/user-attachments/files/18128545/_MainActivity-1734103522911.zip)
[爱奇艺_PlayerActivity-1734103605358.zip](https://github.com/user-attachments/files/18128546/_PlayerActivity-1734103605358.zip)
](url)

**Comment by AIsouler** [comment]
关闭规则里的开屏广告导入以下规则到本地订阅看能不能跳过
```
{
  id: 'com.qiyi.video',
  name: '爱奇艺',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      priorityTime: 10000,
      rules: [
        {
          fastQuery: true,
          matches: '@[clickable=true] >(1,2) [text="关闭"]',
          exampleUrls: 'https://e.gkd.li/9044d76f-f545-46b9-afde-29295c244abd',
          snapshotUrls: 'https://i.gkd.li/i/18134223',
        },
      ],
    },
  ],
}
```

**Comment by linuxgi** [comment]
> 你好 linuxgi，请及时回复，否则你的 issue 将在3天后自动关闭！

爱奇艺开屏广告，用上面的规则已经可以跳过了。

另外想问一下爱奇艺播放视频。暂停时出现的两种广告可以适配吗？
快照：
[爱奇艺_PlayerActivity-1734172445192.zip](https://github.com/user-attachments/files/18135522/_PlayerActivity-1734172445192.zip)
[爱奇艺_PlayerActivity-1734172451047.zip](https://github.com/user-attachments/files/18135523/_PlayerActivity-1734172451047.zip)
