### ISSUE TITLE
深度搜索插屏广告

### ISSUE THREAD

**Issue by taojinliang123** [AIsouler/GKD_subscription#617]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

https://i.gkd.li/i/18142759

**Comment by AIsouler** [comment]
快照无activityid
https://github.com/AIsouler/GKD_subscription/issues/480

**Comment by taojinliang123** [comment]
> 快照无activityid #480

https://i.gkd.li/i/18146842
