### ISSUE TITLE
[Bug] 翼支付：全屏广告-弹窗广告规则不生效

### ISSUE THREAD

**Issue by linuxgi** [AIsouler/GKD_subscription#619]
### 请提供 误触界面/出现问题界面 的快照（不要提供截图！！！），也可补充说明

翼支付APP-首页，全屏广告-弹窗广告规则不生效。
翼支付APP-首页-手机充值，全屏广告-弹窗广告规则不生效。
这两个弹窗出现的概率和频率都很高

快照：
[翼支付_MainActivity-1734339213540.zip](https://github.com/user-attachments/files/18150402/_MainActivity-1734339213540.zip)
[翼支付_MriverActivityBase$Main-1734339224870.zip](https://github.com/user-attachments/files/18150403/_MriverActivityBase.Main-1734339224870.zip)

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

翼支付APP规则：全屏广告-弹窗广告，不生效

**Comment by AIsouler** [comment]
另一个小程序不予适配，且无法适配
