### ISSUE TITLE
[Bug] 钉钉6.0.30版本误触

### ISSUE THREAD

**Issue by Guovin** [AIsouler/GKD_subscription#621]
### 请提供 误触界面/出现问题界面 的快照（不要提供截图！！！），也可补充说明

[钉钉_SplashActivity-1734417459556.zip](https://github.com/user-attachments/files/18161292/_SplashActivity-1734417459556.zip)

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

![dingding](https://github.com/user-attachments/assets/5d18aba5-03e7-48cd-89b9-bcc369ef59a8)
默认钉钉并没有开启任何规则，为什么进入钉钉首页会误触底部的聊天？

**Comment by Guovin** [comment]
[钉钉_SplashActivity-1734418616619.zip](https://github.com/user-attachments/files/18161453/_SplashActivity-1734418616619.zip)
![ding](https://github.com/user-attachments/assets/1407c3fd-0db2-42e5-9267-a43dd2bd852f)

查看确实是全局开屏广告规则导致误触，关闭就不会触发误触聊天了，但开屏广告无法跳过了，以上是聊天界面的快照

**Comment by AIsouler** [comment]
你发的这个快照我没有发现误触，你应该发错了，在哪个页面误触就发哪个页面的快照

**Comment by Guovin** [comment]
> 你发的这个快照我没有发现误触，你应该发错了，在哪个页面误触就发哪个页面的快照

确定是上面这个快照触发了，首次打开钉钉出现开屏广告触发跳过，然后进入聊天首页又触发了一次点击进入聊天

**Comment by AIsouler** [comment]
能否发个录屏？

**Comment by Guovin** [comment]
https://github.com/user-attachments/assets/d2aaf1c5-7ff2-467c-ab89-391776967f95

**Comment by Guovin** [comment]
> 你导入了除我以外的订阅吗？

没有，只有你一个订阅

**Comment by AIsouler** [comment]
已修复，今晚会发布一次更新

**Comment by AIsouler** [comment]
能否提供一下日志文件？

**Comment by Guovin** [comment]
> [钉钉_SplashActivity-1734418616619.zip](https://github.com/user-attachments/files/18161453/_SplashActivity-1734418616619.zip) ![ding](https://private-user-images.githubusercontent.com/37107669/396384546-1407c3fd-0db2-42e5-9267-a43dd2bd852f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjkyNDIsIm5iZiI6MTczNDUyODk0MiwicGF0aCI6Ii8zNzEwNzY2OS8zOTYzODQ1NDYtMTQwN2MzZmQtMGRiMi00MmU1LTkyNjctYTQzZGQyYmQ4NTJmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDEzMzU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNTQxNDk2NGYzYWNjMzNiNDI3MDhhZGJkYjcxMDZjMWZhZDI0ZDBkNWIxMjMwMDE5MjBmYjhiYjZmYTRjZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J8cusUDtC1cJmmzkE4XwKA20o6KiWZg5VQsglpn6hRA)
> 
> 查看确实是全局开屏广告规则导致误触，关闭就不会触发误触聊天了，但开屏广告无法跳过了，以上是聊天界面的快照

@AIsouler 这就是误触时触发的记录，一共两条，一条是开屏广告记录，一条是聊天首页误触记录

**Comment by Guovin** [comment]
刚刚更新了2小时前的规则没有误触了，昨天晚上的规则会误触，辛苦了。

**Comment by AIsouler** [comment]
> 刚刚更新了2小时前的规则没有误触了，昨天晚上的规则会误触，辛苦了。

我没有发布更新，你在哪更新的？

**Comment by Guovin** [comment]
> > 刚刚更新了2小时前的规则没有误触了，昨天晚上的规则会误触，辛苦了。
> 
> 我没有发布更新，你在哪更新的？

![Screenshot_2024-12-18-21-59-24-976_li songe gkd](https://github.com/user-attachments/assets/11be18ab-95af-45e7-a976-1bdd8b19cfa7)
但这确实是显示2小时前更新的，18点左右我看的是22小时前

**Comment by Guovin** [comment]
18点多时我打开钉钉还是会误触的，现在没有了

**Comment by AIsouler** [comment]
> > 已修复，今晚会发布一次更新
> 
> 更新后依旧触发该问题

也就是说你这里没更新规则就来反馈了，别浪费大家时间好不好

**Comment by Guovin** [comment]
> > > 已修复，今晚会发布一次更新
> > 
> > 
> > 更新后依旧触发该问题
> 
> 也就是说你这里没更新规则就来反馈了，别浪费大家时间好不好

只能说gkd显示更新时间导致误以为是已经更新了，18号18点30分我发现该问题依旧存在，查看gkd显示订阅更新时间是22小时前，也就是17号20点的更新，也就是你说的17号晚会更新一次，所以我才来报告问题依旧存在。直到18号22点我再次查看gkd显示订阅更新变成了2小时前（如上图）。

**Comment by AIsouler** [comment]
好的，其实你可以手动下拉更新的

**Comment by Guovin** [comment]
> 好的，其实你可以手动下拉更新的

OK，学到了，对于打扰到大家实属抱歉~
