### ISSUE TITLE
[Feature] bilibili 广告页面，以及StoryMode

### ISSUE THREAD

**Issue by chr431** [AIsouler/GKD_subscription#623]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

第一个是一个广告界面，第二个是希望能自动点击右下角第二个按键退出故事模式，因为b站首页有一些视频点进去默认是故事模式，用着很不习惯
[哔哩哔哩_UnitedBizDetailsActivity-1734429803452.zip](https://github.com/user-attachments/files/18163705/_UnitedBizDetailsActivity-1734429803452.zip)
[哔哩哔哩_StoryVideoActivity-1732420481243.zip](https://github.com/user-attachments/files/18163704/_StoryVideoActivity-1732420481243.zip)

**Comment by AIsouler** [comment]
退出故事模式后的快照发一下，需要显示按钮的快照

**Comment by AIsouler** [comment]
> 退出故事模式后的快照发一下，需要显示按钮的快照

不需要了
