### ISSUE TITLE
[Feature] 关闭酷狗速听

### ISSUE THREAD

**Issue by zutzo** [AIsouler/GKD_subscription#624]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

复现 
酷狗 v20 
打开酷狗会进入速听模式 无论是否有播放音乐
希望大佬能写规则自动关闭
[酷狗音乐_MediaActivity-1734434561717.zip](https://github.com/user-attachments/files/18164686/_MediaActivity-1734434561717.zip)
[酷狗音乐_MediaActivity-1734434592407.zip](https://github.com/user-attachments/files/18164688/_MediaActivity-1734434592407.zip)

**Comment by AIsouler** [comment]
是先点这个
![image](https://github.com/user-attachments/assets/a227b8f1-0d07-4fd1-9cbd-6ea6930308db)
再点这个吗？
![image](https://github.com/user-attachments/assets/65b6aeab-1a04-4de7-a3d1-6f1bbd0218e9)
