### ISSUE TITLE
[Bug]网易有道词典，从后台返回app的开屏广告会误触

### ISSUE THREAD

**Issue by Unbengabled** [AIsouler/GKD_subscription#627]
### 请提供 误触界面/出现问题界面 的快照（不要提供截图！！！），也可补充说明

https://i.gkd.li/i/18173926
这个是从多任务界面返回进入app后弹出的，会误触进入广告界面，可能是这个跳过按钮的位置变了

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

开屏广告-全局

**Comment by AIsouler** [comment]
用的是最新版订阅吗https://github.com/AIsouler/GKD_subscription/releases/tag/v167

**Comment by AIsouler** [comment]
发一下误触时的触发记录截图

**Comment by Unbengabled** [comment]
> 发一下误触时的触发记录截图

奇怪，现在又不误触了

**Comment by Unbengabled** [comment]
![Screenshot_20241218_171907](https://github.com/user-attachments/assets/00c92876-fd52-4bc4-9fb4-40ddf0b77fcf)
![Screenshot_20241218_171953](https://github.com/user-attachments/assets/a22c9f8a-0183-4018-9779-1cf53e1a10ac)
我记不清是具体哪一次触发是误触的了，只记得是在这个时间段内发生的

**Comment by AIsouler** [comment]
这个问题最新版已经修复了，你昨天用的不是最新版
![image](https://github.com/user-attachments/assets/217f6f22-c497-432e-a515-90537ae9961e)
