### ISSUE TITLE
微信订阅号分段式广告，最新订阅里面开启了，但是没效果。

### ISSUE THREAD

**Issue by callmelrj** [AIsouler/GKD_subscription#632]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

[微信_BizFlutterTLFlutterViewActivity-1734595093594.zip](https://github.com/user-attachments/files/18194407/_BizFlutterTLFlutterViewActivity-1734595093594.zip)
[微信_BizFlutterTLFlutterViewActivity-1734595097231.zip](https://github.com/user-attachments/files/18194409/_BizFlutterTLFlutterViewActivity-1734595097231.zip)
[微信_BizFlutterTLFlutterViewActivity-1734595101055.zip](https://github.com/user-attachments/files/18194411/_BizFlutterTLFlutterViewActivity-1734595101055.zip)
[微信_BizFlutterTLFlutterViewActivity-1734595104989.zip](https://github.com/user-attachments/files/18194412/_BizFlutterTLFlutterViewActivity-1734595104989.zip)

**Comment by AIsouler** [comment]
无法适配

**Comment by cug2006** [comment]
我的也是订阅号里的广告不管用了，前几天我记得还是秒关的，新换了手机后不知道咋弄的现在不行了。不过我试了甘霖的规则还是像老版的订阅反馈一样打开两个规则可以关掉广告，但是有点慢，估计有1-2秒反应时间。play版的8.0.49，
