### ISSUE TITLE
[Feature] 微信订阅号文章中间的广告、底部评论栏之前的广告都不能关闭了

### ISSUE THREAD

**Issue by shadowlaser** [AIsouler/GKD_subscription#637]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

https://i.gkd.li/snapshot/1734832905264
https://i.gkd.li/snapshot/1734835021748
https://i.gkd.li/snapshot/1734835025416
以上是底部广告快照，我发现是activityid变了
从
.plugin.brandservice.ui.timeline.preload.ui.TmplWebView
变成
.plugin.brandservice.ui.timeline.preload.ui.TmplWebViewMMUI

**Comment by shadowlaser** [comment]
[微信_TmplWebViewMMUI-1734835021748.zip](https://github.com/user-attachments/files/18242422/_TmplWebViewMMUI-1734835021748.zip)
[微信_TmplWebViewMMUI-1734835025416.zip](https://github.com/user-attachments/files/18242423/_TmplWebViewMMUI-1734835025416.zip)
[微信_TmplWebViewMMUI-1734832905264.zip](https://github.com/user-attachments/files/18242424/_TmplWebViewMMUI-1734832905264.zip)

**Comment by AIsouler** [comment]
广告反馈节点 ```clickable=false``` ，为防止误触不予适配
