### ISSUE TITLE
[Bug] 误触发

### ISSUE THREAD

**Issue by lab6612** [AIsouler/GKD_subscription#639]
### 请提供 误触界面/出现问题界面 的快照（不要提供截图！！！），也可补充说明

抖音，知乎，夸克搜索页面，输入gkd会触发 开屏广告-全局 这条规则，会自动点击搜索按钮

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

抖音，知乎，夸克搜索页面，输入gkd会触发 开屏广告-全局 这条规则，会自动点击搜索按钮

**Comment by lab6612** [comment]
https://raw.gitmirror.com/AIsouler/GKD_subscription/main/dist/AIsouler_gkd.json5

快照不会创建，这个链接我是随便输入的，看我文字描述

**Comment by lab6612** [comment]
https://raw.gitmirror.com/AIsouler/GKD_subscription/main/dist/AIsouler_gkd.json5

**Comment by AIsouler** [comment]
提issue的时候不是告诉你怎么获取快照了吗？
![image](https://github.com/user-attachments/assets/3c8be42c-7d0d-46e3-96bf-0ad542aca183)

**Comment by AIsouler** [comment]
另外我的订阅在抖音的搜索页是不会误触的，你应该是导入了其他订阅

**Comment by AIsouler** [comment]
f7697fed131bba3382b63684608f4769e2e54f51
976281d29921a0ab67d281cf4a28ea822ebedad5
