### ISSUE TITLE
[Feature] 微博轻享版 开屏广告

### ISSUE THREAD

**Issue by shuohao** [AIsouler/GKD_subscription#643]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

[微博轻享版-1734942435191.zip](https://github.com/user-attachments/files/18227272/-1734942435191.zip)

**Comment by AIsouler** [comment]
关闭订阅的开屏广告然后导入以下规则看看能不能跳过
```
{
  id: 'com.weico.international',
  name: '微博轻享版',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      matchTime: 10000,
      actionMaximum: 2,
      resetMatch: 'app',
      priorityTime: 10000,
      rules: [
        {
          fastQuery: true,
          matches: '[text*="跳过"][text.length<10][visibleToUser=true]',
          exampleUrls: 'https://e.gkd.li/baad8e41-2878-4b4e-bc0c-15c6bee5cfde',
          snapshotUrls: 'https://i.gkd.li/i/18227365',
        },
      ],
    },
  ],
}
```

**Comment by shuohao** [comment]
> 关闭订阅的开屏广告然后导入以下规则看看能不能跳过
> 
> ```
> {
>   id: 'com.weico.international',
>   name: '微博轻享版',
>   groups: [
>     {
>       key: 1,
>       name: '开屏广告',
>       matchTime: 10000,
>       actionMaximum: 2,
>       resetMatch: 'app',
>       priorityTime: 10000,
>       rules: [
>         {
>           fastQuery: true,
>           matches: '[text*="跳过"][text.length<10][visibleToUser=true]',
>           exampleUrls: 'https://e.gkd.li/baad8e41-2878-4b4e-bc0c-15c6bee5cfde',
>           snapshotUrls: 'https://i.gkd.li/i/18227365',
>         },
>       ],
>     },
>   ],
> }
> ```

不行

**Comment by AIsouler** [comment]
有点击提示吗？

**Comment by shuohao** [comment]
> 有点击提示吗？如果有，那么试试在高级设置里开启 `shizuku模拟点击` 看看能不能跳过

[微博轻享版_AdActivity-1734945342471.zip](https://github.com/user-attachments/files/18227688/_AdActivity-1734945342471.zip)
这微博太恶心了，又变成这种左上角圆圈型的，右上角 右下角 这货齐了 就差左下角了
