### ISSUE TITLE
[Feature] 小红书 开屏广告

### ISSUE THREAD

**Issue by shuohao** [AIsouler/GKD_subscription#644]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

[小红书_IndexActivityV2-1734943381490.zip](https://github.com/user-attachments/files/18227416/_IndexActivityV2-1734943381490.zip)

**Comment by AIsouler** [comment]
现有规则有效

**Comment by shuohao** [comment]
> 现有规则有效

小红书有触发记录，但是没跳过

**Comment by AIsouler** [comment]
在高级设置里开启 shizuku模拟点击 看看能不能跳过
