### ISSUE TITLE
[Feature] 哔哩哔哩-全屏广告-会员弹窗 无效

### ISSUE THREAD

**Issue by S-ZHIWEI** [AIsouler/GKD_subscription#645]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

[哔哩哔哩_VipWebActivity-1734971588945.zip](https://github.com/user-attachments/files/18231476/_VipWebActivity-1734971588945.zip)
Shizuku界面识别和模拟点击开了 GKD是1.9.3正式版 哔哩哔哩7.42.0

**Comment by AIsouler** [comment]
这个弹窗可以通过返回关闭吗

**Comment by S-ZHIWEI** [comment]
只能通过弹出的图片下那个x关闭
