### ISSUE TITLE
[Feature] 淘宝开屏广告

### ISSUE THREAD

**Issue by lq666-bit** [AIsouler/GKD_subscription#651]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

[淘宝_TBOrderListActivity-1735040486490.zip](https://github.com/user-attachments/files/18239190/_TBOrderListActivity-1735040486490.zip)

**Comment by AIsouler** [comment]
在这个广告页面的时候有点击提示吗？

**Comment by lq666-bit** [comment]
有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月24日(周二) 晚上8:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AIsouler/GKD_subscription] [Feature] 淘宝开屏广告 (Issue #651)




 
在这个广告页面的时候有点击提示吗？

**Comment by AIsouler** [comment]
在高级设置里开启 ```shizuku模拟点击``` 看看能不能跳过

**Comment by lq666-bit** [comment]
不能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月24日(周二) 晚上8:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AIsouler/GKD_subscription] [Feature] 淘宝开屏广告 (Issue #651)




 
在高级设置里开启 shizuku模拟点击 看看能不能跳过

**Comment by AIsouler** [comment]
导入这个试试呢
```
{
  id: 'com.taobao.taobao',
  name: '淘宝',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      priorityTime: 10000,
      rules: [
        {
          fastQuery: true,
          action: 'clickCenter',
          matches: '[vid*="close"] > [text*="跳过"][text.length<10][visibleToUser=true]',
          exampleUrls: 'https://e.gkd.li/912377a8-c446-4780-8fc9-76f3ae62c61e',
          snapshotUrls: 'https://i.gkd.li/i/18239310',
        },
      ],
    },
  ],
}
```

**Comment by AIsouler** [comment]
如果上面那个不行就导入这个试试
```
{
  id: 'com.taobao.taobao',
  name: '淘宝',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      matchTime: 10000,
      actionMaximum: 1,
      resetMatch: 'app',
      priorityTime: 10000,
      rules: [
        {
          fastQuery: true,
          actionDelay: 1000,
          action: 'clickCenter',
          matches: '[vid*="close"] > [text*="跳过"][text.length<10][visibleToUser=true]',
          exampleUrls: 'https://e.gkd.li/912377a8-c446-4780-8fc9-76f3ae62c61e',
          snapshotUrls: 'https://i.gkd.li/i/18239310',
        },
      ],
    },
  ],
}
```

**Comment by AIsouler** [comment]
如果还不行就导入这个试试，记得把之前导入的删掉
```
{
  id: 'com.taobao.taobao',
  name: '淘宝',
  groups: [
    {
      key: 1,
      name: '开屏广告',
      matchTime: 10000,
      actionMaximum: 2,
      resetMatch: 'app',
      priorityTime: 10000,
      rules: [
        {
          fastQuery: true,
          actionDelay: 1000,
          action: 'clickCenter',
          matches: '[vid*="close"] > [text*="跳过"][text.length<10][visibleToUser=true]',
          exampleUrls: 'https://e.gkd.li/912377a8-c446-4780-8fc9-76f3ae62c61e',
          snapshotUrls: 'https://i.gkd.li/i/18239310',
        },
      ],
    },
  ],
}
```

**Comment by lq666-bit** [comment]
好的，得试试，很难复现，因为这个是淘宝留在后台过一会热启动的开屏广告，冷启动没有广告

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月24日(周二) 晚上8:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AIsouler/GKD_subscription] [Feature] 淘宝开屏广告 (Issue #651)




 
如果还不行就导入这个试试，记得把之前导入的删掉
 {   id: 'com.taobao.taobao',   name: '淘宝',   groups: [     {       key: 1,       name: '开屏广告',       matchTime: 10000,       actionMaximum: 2,       resetMatch: 'app',       priorityTime: 10000,       rules: [         {           fastQuery: true,           actionDelay: 1000,           action: 'clickCenter',           matches: '[vid*="close"] &gt; [text*="跳过"][text.length<10][visibleToUser=true]',           exampleUrls: 'https://e.gkd.li/912377a8-c446-4780-8fc9-76f3ae62c61e',           snapshotUrls: 'https://i.gkd.li/i/18239310',         },       ],     },   ], }
