### ISSUE TITLE
[Feature] 请求适配

### ISSUE THREAD

**Issue by jiuban590** [AIsouler/GKD_subscription#652]
### 请提供 需要适配界面 的快照（不要提供截图！！！），也可补充说明

https://i.gkd.li/i/18242457

点击 立即解锁 今日畅听，优先级要大于 全屏广告-VIP弹窗，否则会被 全屏广告-VIP弹窗 规则关闭。

**Comment by AIsouler** [comment]
这个弹窗是它自动弹出来的还是你点击某个地方之后出来的？

**Comment by jiuban590** [comment]
> 这个弹窗是它自动弹出来的还是你点击某个地方之后出来的？

![IMG_20241225_130419](https://github.com/user-attachments/assets/62a36cba-ca5d-4bc8-9bbd-8109e8728b7a)
点击这个地方，看完一次广告也会自己弹出来
