### ISSUE TITLE
[Bug] 三星健康，或三星系应用，开屏界面会直接点击取消，并退出到主屏幕

### ISSUE THREAD

**Issue by zebwqfox** [AIsouler/GKD_subscription#658]
### 请提供 误触界面/出现问题界面 的快照（不要提供截图！！！），也可补充说明

[三星健康-1735322588234.zip](https://github.com/user-attachments/files/18262616/-1735322588234.zip)

### 请说明是哪一条规则 误触/出现问题（文字/触发记录界面截图）

![Screenshot_20241228_020623_Samsung Health](https://github.com/user-attachments/assets/b560761c-b71f-4d42-b0e4-21db0968d381)

**Comment by zebwqfox** [comment]
![Screenshot_20241228_021143_GKD](https://github.com/user-attachments/assets/21951d93-009f-4158-a008-60a85c2811f3)

**Comment by AIsouler** [comment]
> 三星系应用
需补充其他快照

**Comment by zebwqfox** [comment]
作者您好，今天经过测试-发现常用的三星应用中仅有三星健康才会发生这种情况，其他常用三星应用规则页面会提示
“此规则组已经在其 apps 字段中配置对当前应用的禁用, 因此无法手动开启规则组”
因此其他三星应用暂时没有发现其他问题
