### ISSUE TITLE
优酷暂停时中间的广告

### ISSUE THREAD

**Issue by suppermanzero** [AIsouler/GKD_subscription#71]
### 请输入需要添加规则的界面的快照或者生成的链接, 也可在后面补充其它信息
请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭

https://i.gkd.li/import/14321461

**Comment by suppermanzero** [comment]
优酷播放时右下角的广告：https://i.gkd.li/import/14321461

优酷暂停时中间的广告：https://i.gkd.li/import/14321469

**Comment by AIsouler** [comment]
下次把链接一次性发出来

**Comment by suppermanzero** [comment]
> 下次把链接一次性发出来

好的大佬
