### ISSUE TITLE
全局规则对 X 浏览器误触

### ISSUE THREAD

**Issue by Kisesy** [AIsouler/GKD_subscription#89]
当前全局规则会对 X 浏览器的搜索记录误触，如果里面包含 "跳过" 等关键词

![1000015468](https://github.com/AIsouler/GKD_subscription/assets/5843694/8c48f0ee-86ba-4953-bcb8-002ef4b16fc8)

![1000015470](https://github.com/AIsouler/GKD_subscription/assets/5843694/163e7643-fd13-428c-91c5-0e9ce5c6e989)

还有个录屏，但是手机传不上来

**Comment by AIsouler** [comment]
点击误触的规则选择“在此页面禁用此规则”或“在此应用禁用此规则”，x浏览器没有开屏广告建议选择“在此应用禁用此规则”

**Comment by AIsouler** [comment]
x浏览器是在禁用名单里的，你用的是修改版吗，能否发一个快照过来？

**Comment by AIsouler** [comment]
默认禁用是有x浏览器的，我用x浏览器没有复现这个问题

**Comment by AIsouler** [comment]
a3c17fb58dabeab0cb6236d2438c56ecc86dcb3a
